// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockStorageService is an autogenerated mock type for the StorageService type
type MockStorageService struct {
	mock.Mock
}

type MockStorageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorageService) EXPECT() *MockStorageService_Expecter {
	return &MockStorageService_Expecter{mock: &_m.Mock}
}

// GeneratePresignedPutURL provides a mock function with given fields: ctx, key, contentType, expiresIn
func (_m *MockStorageService) GeneratePresignedPutURL(ctx context.Context, key string, contentType string, expiresIn time.Duration) (string, error) {
	ret := _m.Called(ctx, key, contentType, expiresIn)

	if len(ret) == 0 {
		panic("no return value specified for GeneratePresignedPutURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) (string, error)); ok {
		return rf(ctx, key, contentType, expiresIn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) string); ok {
		r0 = rf(ctx, key, contentType, expiresIn)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Duration) error); ok {
		r1 = rf(ctx, key, contentType, expiresIn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorageService_GeneratePresignedPutURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GeneratePresignedPutURL'
type MockStorageService_GeneratePresignedPutURL_Call struct {
	*mock.Call
}

// GeneratePresignedPutURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - contentType string
//   - expiresIn time.Duration
func (_e *MockStorageService_Expecter) GeneratePresignedPutURL(ctx interface{}, key interface{}, contentType interface{}, expiresIn interface{}) *MockStorageService_GeneratePresignedPutURL_Call {
	return &MockStorageService_GeneratePresignedPutURL_Call{Call: _e.mock.On("GeneratePresignedPutURL", ctx, key, contentType, expiresIn)}
}

func (_c *MockStorageService_GeneratePresignedPutURL_Call) Run(run func(ctx context.Context, key string, contentType string, expiresIn time.Duration)) *MockStorageService_GeneratePresignedPutURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockStorageService_GeneratePresignedPutURL_Call) Return(_a0 string, _a1 error) *MockStorageService_GeneratePresignedPutURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorageService_GeneratePresignedPutURL_Call) RunAndReturn(run func(context.Context, string, string, time.Duration) (string, error)) *MockStorageService_GeneratePresignedPutURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetFile provides a mock function with given fields: ctx, key
func (_m *MockStorageService) GetFile(ctx context.Context, key string) ([]byte, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetFile")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorageService_GetFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFile'
type MockStorageService_GetFile_Call struct {
	*mock.Call
}

// GetFile is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorageService_Expecter) GetFile(ctx interface{}, key interface{}) *MockStorageService_GetFile_Call {
	return &MockStorageService_GetFile_Call{Call: _e.mock.On("GetFile", ctx, key)}
}

func (_c *MockStorageService_GetFile_Call) Run(run func(ctx context.Context, key string)) *MockStorageService_GetFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorageService_GetFile_Call) Return(_a0 []byte, _a1 error) *MockStorageService_GetFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorageService_GetFile_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *MockStorageService_GetFile_Call {
	_c.Call.Return(run)
	return _c
}

// SaveFile provides a mock function with given fields: ctx, file, filePath, fileName
func (_m *MockStorageService) SaveFile(ctx context.Context, file []byte, filePath string, fileName string) (string, error) {
	ret := _m.Called(ctx, file, filePath, fileName)

	if len(ret) == 0 {
		panic("no return value specified for SaveFile")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string, string) (string, error)); ok {
		return rf(ctx, file, filePath, fileName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string, string) string); ok {
		r0 = rf(ctx, file, filePath, fileName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, string, string) error); ok {
		r1 = rf(ctx, file, filePath, fileName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorageService_SaveFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveFile'
type MockStorageService_SaveFile_Call struct {
	*mock.Call
}

// SaveFile is a helper method to define mock.On call
//   - ctx context.Context
//   - file []byte
//   - filePath string
//   - fileName string
func (_e *MockStorageService_Expecter) SaveFile(ctx interface{}, file interface{}, filePath interface{}, fileName interface{}) *MockStorageService_SaveFile_Call {
	return &MockStorageService_SaveFile_Call{Call: _e.mock.On("SaveFile", ctx, file, filePath, fileName)}
}

func (_c *MockStorageService_SaveFile_Call) Run(run func(ctx context.Context, file []byte, filePath string, fileName string)) *MockStorageService_SaveFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockStorageService_SaveFile_Call) Return(_a0 string, _a1 error) *MockStorageService_SaveFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorageService_SaveFile_Call) RunAndReturn(run func(context.Context, []byte, string, string) (string, error)) *MockStorageService_SaveFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorageService creates a new instance of MockStorageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageService {
	mock := &MockStorageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
