with-expecter: true
dir: 'internal/store/mocks'
outpkg: mocks
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  github.com/ywl0806/yuno_kiroku/internal/store:
    interfaces:
      Transactor:
      TxStore:
      UserStore:
      FamilyStore:
      GroupStore:
      AlbumStore:
      AlbumGroupPermissionStore:
      IdentityStore:
      FaceStore:
      MediaItemStore:
      InviteTokenStore:
      KidStore:
      IdentityFaceImgStore:
      LikeStore:
      TagStore:
  github.com/ywl0806/yuno_kiroku/internal/services:
    config:
      dir: 'internal/services/mocks'
    interfaces:
      UserService:
      IdentityService:
      KidService:
      MediaItemService:
      LikeService:
      TagService:
      AlbumService:
      GroupService:
      InviteService:
      AuthService:
      ImageUploader:
      FaceRecognitionDispatcher:
  github.com/ywl0806/yuno_kiroku/pkg/storage:
    config:
      dir: 'pkg/storage/mocks'
    interfaces:
      StorageService:
