// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "github.com/ywl0806/yuno_kiroku/internal/db"
)

// MockTagService is an autogenerated mock type for the TagService type
type MockTagService struct {
	mock.Mock
}

type MockTagService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagService) EXPECT() *MockTagService_Expecter {
	return &MockTagService_Expecter{mock: &_m.Mock}
}

// AddTagToMediaItem provides a mock function with given fields: ctx, mediaItemID, tagID, userID
func (_m *MockTagService) AddTagToMediaItem(ctx context.Context, mediaItemID int32, tagID int32, userID int32) error {
	ret := _m.Called(ctx, mediaItemID, tagID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddTagToMediaItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32, int32) error); ok {
		r0 = rf(ctx, mediaItemID, tagID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTagService_AddTagToMediaItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTagToMediaItem'
type MockTagService_AddTagToMediaItem_Call struct {
	*mock.Call
}

// AddTagToMediaItem is a helper method to define mock.On call
//   - ctx context.Context
//   - mediaItemID int32
//   - tagID int32
//   - userID int32
func (_e *MockTagService_Expecter) AddTagToMediaItem(ctx interface{}, mediaItemID interface{}, tagID interface{}, userID interface{}) *MockTagService_AddTagToMediaItem_Call {
	return &MockTagService_AddTagToMediaItem_Call{Call: _e.mock.On("AddTagToMediaItem", ctx, mediaItemID, tagID, userID)}
}

func (_c *MockTagService_AddTagToMediaItem_Call) Run(run func(ctx context.Context, mediaItemID int32, tagID int32, userID int32)) *MockTagService_AddTagToMediaItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32), args[3].(int32))
	})
	return _c
}

func (_c *MockTagService_AddTagToMediaItem_Call) Return(_a0 error) *MockTagService_AddTagToMediaItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTagService_AddTagToMediaItem_Call) RunAndReturn(run func(context.Context, int32, int32, int32) error) *MockTagService_AddTagToMediaItem_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTag provides a mock function with given fields: ctx, familyID, userID, name
func (_m *MockTagService) CreateTag(ctx context.Context, familyID int32, userID int32, name string) (db.Tag, error) {
	ret := _m.Called(ctx, familyID, userID, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateTag")
	}

	var r0 db.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32, string) (db.Tag, error)); ok {
		return rf(ctx, familyID, userID, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32, string) db.Tag); ok {
		r0 = rf(ctx, familyID, userID, name)
	} else {
		r0 = ret.Get(0).(db.Tag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32, string) error); ok {
		r1 = rf(ctx, familyID, userID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTagService_CreateTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTag'
type MockTagService_CreateTag_Call struct {
	*mock.Call
}

// CreateTag is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID int32
//   - userID int32
//   - name string
func (_e *MockTagService_Expecter) CreateTag(ctx interface{}, familyID interface{}, userID interface{}, name interface{}) *MockTagService_CreateTag_Call {
	return &MockTagService_CreateTag_Call{Call: _e.mock.On("CreateTag", ctx, familyID, userID, name)}
}

func (_c *MockTagService_CreateTag_Call) Run(run func(ctx context.Context, familyID int32, userID int32, name string)) *MockTagService_CreateTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32), args[3].(string))
	})
	return _c
}

func (_c *MockTagService_CreateTag_Call) Return(_a0 db.Tag, _a1 error) *MockTagService_CreateTag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTagService_CreateTag_Call) RunAndReturn(run func(context.Context, int32, int32, string) (db.Tag, error)) *MockTagService_CreateTag_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTag provides a mock function with given fields: ctx, tagID, familyID
func (_m *MockTagService) DeleteTag(ctx context.Context, tagID int32, familyID int32) error {
	ret := _m.Called(ctx, tagID, familyID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) error); ok {
		r0 = rf(ctx, tagID, familyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTagService_DeleteTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTag'
type MockTagService_DeleteTag_Call struct {
	*mock.Call
}

// DeleteTag is a helper method to define mock.On call
//   - ctx context.Context
//   - tagID int32
//   - familyID int32
func (_e *MockTagService_Expecter) DeleteTag(ctx interface{}, tagID interface{}, familyID interface{}) *MockTagService_DeleteTag_Call {
	return &MockTagService_DeleteTag_Call{Call: _e.mock.On("DeleteTag", ctx, tagID, familyID)}
}

func (_c *MockTagService_DeleteTag_Call) Run(run func(ctx context.Context, tagID int32, familyID int32)) *MockTagService_DeleteTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *MockTagService_DeleteTag_Call) Return(_a0 error) *MockTagService_DeleteTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTagService_DeleteTag_Call) RunAndReturn(run func(context.Context, int32, int32) error) *MockTagService_DeleteTag_Call {
	_c.Call.Return(run)
	return _c
}

// GetTagsByFamilyID provides a mock function with given fields: ctx, familyID
func (_m *MockTagService) GetTagsByFamilyID(ctx context.Context, familyID int32) ([]db.Tag, error) {
	ret := _m.Called(ctx, familyID)

	if len(ret) == 0 {
		panic("no return value specified for GetTagsByFamilyID")
	}

	var r0 []db.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]db.Tag, error)); ok {
		return rf(ctx, familyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []db.Tag); ok {
		r0 = rf(ctx, familyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, familyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTagService_GetTagsByFamilyID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTagsByFamilyID'
type MockTagService_GetTagsByFamilyID_Call struct {
	*mock.Call
}

// GetTagsByFamilyID is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID int32
func (_e *MockTagService_Expecter) GetTagsByFamilyID(ctx interface{}, familyID interface{}) *MockTagService_GetTagsByFamilyID_Call {
	return &MockTagService_GetTagsByFamilyID_Call{Call: _e.mock.On("GetTagsByFamilyID", ctx, familyID)}
}

func (_c *MockTagService_GetTagsByFamilyID_Call) Run(run func(ctx context.Context, familyID int32)) *MockTagService_GetTagsByFamilyID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockTagService_GetTagsByFamilyID_Call) Return(_a0 []db.Tag, _a1 error) *MockTagService_GetTagsByFamilyID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTagService_GetTagsByFamilyID_Call) RunAndReturn(run func(context.Context, int32) ([]db.Tag, error)) *MockTagService_GetTagsByFamilyID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTagsForMediaItem provides a mock function with given fields: ctx, mediaItemID
func (_m *MockTagService) GetTagsForMediaItem(ctx context.Context, mediaItemID int32) ([]db.Tag, error) {
	ret := _m.Called(ctx, mediaItemID)

	if len(ret) == 0 {
		panic("no return value specified for GetTagsForMediaItem")
	}

	var r0 []db.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]db.Tag, error)); ok {
		return rf(ctx, mediaItemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []db.Tag); ok {
		r0 = rf(ctx, mediaItemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, mediaItemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTagService_GetTagsForMediaItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTagsForMediaItem'
type MockTagService_GetTagsForMediaItem_Call struct {
	*mock.Call
}

// GetTagsForMediaItem is a helper method to define mock.On call
//   - ctx context.Context
//   - mediaItemID int32
func (_e *MockTagService_Expecter) GetTagsForMediaItem(ctx interface{}, mediaItemID interface{}) *MockTagService_GetTagsForMediaItem_Call {
	return &MockTagService_GetTagsForMediaItem_Call{Call: _e.mock.On("GetTagsForMediaItem", ctx, mediaItemID)}
}

func (_c *MockTagService_GetTagsForMediaItem_Call) Run(run func(ctx context.Context, mediaItemID int32)) *MockTagService_GetTagsForMediaItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockTagService_GetTagsForMediaItem_Call) Return(_a0 []db.Tag, _a1 error) *MockTagService_GetTagsForMediaItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTagService_GetTagsForMediaItem_Call) RunAndReturn(run func(context.Context, int32) ([]db.Tag, error)) *MockTagService_GetTagsForMediaItem_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTagFromMediaItem provides a mock function with given fields: ctx, mediaItemID, tagID
func (_m *MockTagService) RemoveTagFromMediaItem(ctx context.Context, mediaItemID int32, tagID int32) error {
	ret := _m.Called(ctx, mediaItemID, tagID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTagFromMediaItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) error); ok {
		r0 = rf(ctx, mediaItemID, tagID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTagService_RemoveTagFromMediaItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTagFromMediaItem'
type MockTagService_RemoveTagFromMediaItem_Call struct {
	*mock.Call
}

// RemoveTagFromMediaItem is a helper method to define mock.On call
//   - ctx context.Context
//   - mediaItemID int32
//   - tagID int32
func (_e *MockTagService_Expecter) RemoveTagFromMediaItem(ctx interface{}, mediaItemID interface{}, tagID interface{}) *MockTagService_RemoveTagFromMediaItem_Call {
	return &MockTagService_RemoveTagFromMediaItem_Call{Call: _e.mock.On("RemoveTagFromMediaItem", ctx, mediaItemID, tagID)}
}

func (_c *MockTagService_RemoveTagFromMediaItem_Call) Run(run func(ctx context.Context, mediaItemID int32, tagID int32)) *MockTagService_RemoveTagFromMediaItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *MockTagService_RemoveTagFromMediaItem_Call) Return(_a0 error) *MockTagService_RemoveTagFromMediaItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTagService_RemoveTagFromMediaItem_Call) RunAndReturn(run func(context.Context, int32, int32) error) *MockTagService_RemoveTagFromMediaItem_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTagService creates a new instance of MockTagService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagService {
	mock := &MockTagService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
