// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "github.com/ywl0806/yuno_kiroku/internal/db"
)

// MockGroupService is an autogenerated mock type for the GroupService type
type MockGroupService struct {
	mock.Mock
}

type MockGroupService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupService) EXPECT() *MockGroupService_Expecter {
	return &MockGroupService_Expecter{mock: &_m.Mock}
}

// CreateGroup provides a mock function with given fields: ctx, familyID, name
func (_m *MockGroupService) CreateGroup(ctx context.Context, familyID int32, name string) (db.Group, error) {
	ret := _m.Called(ctx, familyID, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroup")
	}

	var r0 db.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string) (db.Group, error)); ok {
		return rf(ctx, familyID, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, string) db.Group); ok {
		r0 = rf(ctx, familyID, name)
	} else {
		r0 = ret.Get(0).(db.Group)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, string) error); ok {
		r1 = rf(ctx, familyID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupService_CreateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroup'
type MockGroupService_CreateGroup_Call struct {
	*mock.Call
}

// CreateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID int32
//   - name string
func (_e *MockGroupService_Expecter) CreateGroup(ctx interface{}, familyID interface{}, name interface{}) *MockGroupService_CreateGroup_Call {
	return &MockGroupService_CreateGroup_Call{Call: _e.mock.On("CreateGroup", ctx, familyID, name)}
}

func (_c *MockGroupService_CreateGroup_Call) Run(run func(ctx context.Context, familyID int32, name string)) *MockGroupService_CreateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(string))
	})
	return _c
}

func (_c *MockGroupService_CreateGroup_Call) Return(_a0 db.Group, _a1 error) *MockGroupService_CreateGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupService_CreateGroup_Call) RunAndReturn(run func(context.Context, int32, string) (db.Group, error)) *MockGroupService_CreateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteGroup provides a mock function with given fields: ctx, groupID, familyID
func (_m *MockGroupService) DeleteGroup(ctx context.Context, groupID int32, familyID int32) error {
	ret := _m.Called(ctx, groupID, familyID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) error); ok {
		r0 = rf(ctx, groupID, familyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupService_DeleteGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGroup'
type MockGroupService_DeleteGroup_Call struct {
	*mock.Call
}

// DeleteGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID int32
//   - familyID int32
func (_e *MockGroupService_Expecter) DeleteGroup(ctx interface{}, groupID interface{}, familyID interface{}) *MockGroupService_DeleteGroup_Call {
	return &MockGroupService_DeleteGroup_Call{Call: _e.mock.On("DeleteGroup", ctx, groupID, familyID)}
}

func (_c *MockGroupService_DeleteGroup_Call) Run(run func(ctx context.Context, groupID int32, familyID int32)) *MockGroupService_DeleteGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *MockGroupService_DeleteGroup_Call) Return(_a0 error) *MockGroupService_DeleteGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupService_DeleteGroup_Call) RunAndReturn(run func(context.Context, int32, int32) error) *MockGroupService_DeleteGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroups provides a mock function with given fields: ctx, familyID
func (_m *MockGroupService) GetGroups(ctx context.Context, familyID int32) ([]db.Group, error) {
	ret := _m.Called(ctx, familyID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroups")
	}

	var r0 []db.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]db.Group, error)); ok {
		return rf(ctx, familyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []db.Group); ok {
		r0 = rf(ctx, familyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, familyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupService_GetGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroups'
type MockGroupService_GetGroups_Call struct {
	*mock.Call
}

// GetGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID int32
func (_e *MockGroupService_Expecter) GetGroups(ctx interface{}, familyID interface{}) *MockGroupService_GetGroups_Call {
	return &MockGroupService_GetGroups_Call{Call: _e.mock.On("GetGroups", ctx, familyID)}
}

func (_c *MockGroupService_GetGroups_Call) Run(run func(ctx context.Context, familyID int32)) *MockGroupService_GetGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockGroupService_GetGroups_Call) Return(_a0 []db.Group, _a1 error) *MockGroupService_GetGroups_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupService_GetGroups_Call) RunAndReturn(run func(context.Context, int32) ([]db.Group, error)) *MockGroupService_GetGroups_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGroup provides a mock function with given fields: ctx, groupID, familyID, name
func (_m *MockGroupService) UpdateGroup(ctx context.Context, groupID int32, familyID int32, name string) (db.Group, error) {
	ret := _m.Called(ctx, groupID, familyID, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGroup")
	}

	var r0 db.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32, string) (db.Group, error)); ok {
		return rf(ctx, groupID, familyID, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32, string) db.Group); ok {
		r0 = rf(ctx, groupID, familyID, name)
	} else {
		r0 = ret.Get(0).(db.Group)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32, string) error); ok {
		r1 = rf(ctx, groupID, familyID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupService_UpdateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGroup'
type MockGroupService_UpdateGroup_Call struct {
	*mock.Call
}

// UpdateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID int32
//   - familyID int32
//   - name string
func (_e *MockGroupService_Expecter) UpdateGroup(ctx interface{}, groupID interface{}, familyID interface{}, name interface{}) *MockGroupService_UpdateGroup_Call {
	return &MockGroupService_UpdateGroup_Call{Call: _e.mock.On("UpdateGroup", ctx, groupID, familyID, name)}
}

func (_c *MockGroupService_UpdateGroup_Call) Run(run func(ctx context.Context, groupID int32, familyID int32, name string)) *MockGroupService_UpdateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32), args[3].(string))
	})
	return _c
}

func (_c *MockGroupService_UpdateGroup_Call) Return(_a0 db.Group, _a1 error) *MockGroupService_UpdateGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupService_UpdateGroup_Call) RunAndReturn(run func(context.Context, int32, int32, string) (db.Group, error)) *MockGroupService_UpdateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGroupService creates a new instance of MockGroupService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupService {
	mock := &MockGroupService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
