// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "github.com/ywl0806/yuno_kiroku/internal/db"
)

// MockInviteService is an autogenerated mock type for the InviteService type
type MockInviteService struct {
	mock.Mock
}

type MockInviteService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInviteService) EXPECT() *MockInviteService_Expecter {
	return &MockInviteService_Expecter{mock: &_m.Mock}
}

// CreateInviteToken provides a mock function with given fields: ctx, familyID, groupID, createdByUserID, familyTitle, customFamilyTitle
func (_m *MockInviteService) CreateInviteToken(ctx context.Context, familyID int32, groupID int32, createdByUserID int32, familyTitle string, customFamilyTitle string) (db.InviteToken, error) {
	ret := _m.Called(ctx, familyID, groupID, createdByUserID, familyTitle, customFamilyTitle)

	if len(ret) == 0 {
		panic("no return value specified for CreateInviteToken")
	}

	var r0 db.InviteToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32, int32, string, string) (db.InviteToken, error)); ok {
		return rf(ctx, familyID, groupID, createdByUserID, familyTitle, customFamilyTitle)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32, int32, string, string) db.InviteToken); ok {
		r0 = rf(ctx, familyID, groupID, createdByUserID, familyTitle, customFamilyTitle)
	} else {
		r0 = ret.Get(0).(db.InviteToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32, int32, string, string) error); ok {
		r1 = rf(ctx, familyID, groupID, createdByUserID, familyTitle, customFamilyTitle)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInviteService_CreateInviteToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInviteToken'
type MockInviteService_CreateInviteToken_Call struct {
	*mock.Call
}

// CreateInviteToken is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID int32
//   - groupID int32
//   - createdByUserID int32
//   - familyTitle string
//   - customFamilyTitle string
func (_e *MockInviteService_Expecter) CreateInviteToken(ctx interface{}, familyID interface{}, groupID interface{}, createdByUserID interface{}, familyTitle interface{}, customFamilyTitle interface{}) *MockInviteService_CreateInviteToken_Call {
	return &MockInviteService_CreateInviteToken_Call{Call: _e.mock.On("CreateInviteToken", ctx, familyID, groupID, createdByUserID, familyTitle, customFamilyTitle)}
}

func (_c *MockInviteService_CreateInviteToken_Call) Run(run func(ctx context.Context, familyID int32, groupID int32, createdByUserID int32, familyTitle string, customFamilyTitle string)) *MockInviteService_CreateInviteToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32), args[3].(int32), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockInviteService_CreateInviteToken_Call) Return(_a0 db.InviteToken, _a1 error) *MockInviteService_CreateInviteToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInviteService_CreateInviteToken_Call) RunAndReturn(run func(context.Context, int32, int32, int32, string, string) (db.InviteToken, error)) *MockInviteService_CreateInviteToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetValidInviteToken provides a mock function with given fields: ctx, token
func (_m *MockInviteService) GetValidInviteToken(ctx context.Context, token string) (int32, int32, string, string, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetValidInviteToken")
	}

	var r0 int32
	var r1 int32
	var r2 string
	var r3 string
	var r4 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int32, int32, string, string, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int32); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(int32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) int32); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Get(1).(int32)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) string); ok {
		r2 = rf(ctx, token)
	} else {
		r2 = ret.Get(2).(string)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string) string); ok {
		r3 = rf(ctx, token)
	} else {
		r3 = ret.Get(3).(string)
	}

	if rf, ok := ret.Get(4).(func(context.Context, string) error); ok {
		r4 = rf(ctx, token)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// MockInviteService_GetValidInviteToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetValidInviteToken'
type MockInviteService_GetValidInviteToken_Call struct {
	*mock.Call
}

// GetValidInviteToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockInviteService_Expecter) GetValidInviteToken(ctx interface{}, token interface{}) *MockInviteService_GetValidInviteToken_Call {
	return &MockInviteService_GetValidInviteToken_Call{Call: _e.mock.On("GetValidInviteToken", ctx, token)}
}

func (_c *MockInviteService_GetValidInviteToken_Call) Run(run func(ctx context.Context, token string)) *MockInviteService_GetValidInviteToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInviteService_GetValidInviteToken_Call) Return(familyID int32, groupID int32, familyTitle string, customFamilyTitle string, err error) *MockInviteService_GetValidInviteToken_Call {
	_c.Call.Return(familyID, groupID, familyTitle, customFamilyTitle, err)
	return _c
}

func (_c *MockInviteService_GetValidInviteToken_Call) RunAndReturn(run func(context.Context, string) (int32, int32, string, string, error)) *MockInviteService_GetValidInviteToken_Call {
	_c.Call.Return(run)
	return _c
}

// MarkInviteTokenUsed provides a mock function with given fields: ctx, token
func (_m *MockInviteService) MarkInviteTokenUsed(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for MarkInviteTokenUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInviteService_MarkInviteTokenUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkInviteTokenUsed'
type MockInviteService_MarkInviteTokenUsed_Call struct {
	*mock.Call
}

// MarkInviteTokenUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockInviteService_Expecter) MarkInviteTokenUsed(ctx interface{}, token interface{}) *MockInviteService_MarkInviteTokenUsed_Call {
	return &MockInviteService_MarkInviteTokenUsed_Call{Call: _e.mock.On("MarkInviteTokenUsed", ctx, token)}
}

func (_c *MockInviteService_MarkInviteTokenUsed_Call) Run(run func(ctx context.Context, token string)) *MockInviteService_MarkInviteTokenUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInviteService_MarkInviteTokenUsed_Call) Return(_a0 error) *MockInviteService_MarkInviteTokenUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInviteService_MarkInviteTokenUsed_Call) RunAndReturn(run func(context.Context, string) error) *MockInviteService_MarkInviteTokenUsed_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateInviteToken provides a mock function with given fields: ctx, token
func (_m *MockInviteService) ValidateInviteToken(ctx context.Context, token string) (string, string, int32, int32, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateInviteToken")
	}

	var r0 string
	var r1 string
	var r2 int32
	var r3 int32
	var r4 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, string, int32, int32, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) int32); ok {
		r2 = rf(ctx, token)
	} else {
		r2 = ret.Get(2).(int32)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string) int32); ok {
		r3 = rf(ctx, token)
	} else {
		r3 = ret.Get(3).(int32)
	}

	if rf, ok := ret.Get(4).(func(context.Context, string) error); ok {
		r4 = rf(ctx, token)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// MockInviteService_ValidateInviteToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateInviteToken'
type MockInviteService_ValidateInviteToken_Call struct {
	*mock.Call
}

// ValidateInviteToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockInviteService_Expecter) ValidateInviteToken(ctx interface{}, token interface{}) *MockInviteService_ValidateInviteToken_Call {
	return &MockInviteService_ValidateInviteToken_Call{Call: _e.mock.On("ValidateInviteToken", ctx, token)}
}

func (_c *MockInviteService_ValidateInviteToken_Call) Run(run func(ctx context.Context, token string)) *MockInviteService_ValidateInviteToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInviteService_ValidateInviteToken_Call) Return(familyName string, groupName string, familyID int32, groupID int32, err error) *MockInviteService_ValidateInviteToken_Call {
	_c.Call.Return(familyName, groupName, familyID, groupID, err)
	return _c
}

func (_c *MockInviteService_ValidateInviteToken_Call) RunAndReturn(run func(context.Context, string) (string, string, int32, int32, error)) *MockInviteService_ValidateInviteToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInviteService creates a new instance of MockInviteService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInviteService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInviteService {
	mock := &MockInviteService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
