// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "github.com/ywl0806/yuno_kiroku/internal/db"

	services "github.com/ywl0806/yuno_kiroku/internal/services"
)

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// GetKakaoAuthURL provides a mock function with given fields: state
func (_m *MockAuthService) GetKakaoAuthURL(state string) (string, bool) {
	ret := _m.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for GetKakaoAuthURL")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return rf(state)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(state)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(state)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockAuthService_GetKakaoAuthURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKakaoAuthURL'
type MockAuthService_GetKakaoAuthURL_Call struct {
	*mock.Call
}

// GetKakaoAuthURL is a helper method to define mock.On call
//   - state string
func (_e *MockAuthService_Expecter) GetKakaoAuthURL(state interface{}) *MockAuthService_GetKakaoAuthURL_Call {
	return &MockAuthService_GetKakaoAuthURL_Call{Call: _e.mock.On("GetKakaoAuthURL", state)}
}

func (_c *MockAuthService_GetKakaoAuthURL_Call) Run(run func(state string)) *MockAuthService_GetKakaoAuthURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAuthService_GetKakaoAuthURL_Call) Return(url string, configured bool) *MockAuthService_GetKakaoAuthURL_Call {
	_c.Call.Return(url, configured)
	return _c
}

func (_c *MockAuthService_GetKakaoAuthURL_Call) RunAndReturn(run func(string) (string, bool)) *MockAuthService_GetKakaoAuthURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetLineAuthURL provides a mock function with given fields: state
func (_m *MockAuthService) GetLineAuthURL(state string) (string, bool) {
	ret := _m.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for GetLineAuthURL")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return rf(state)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(state)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(state)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockAuthService_GetLineAuthURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLineAuthURL'
type MockAuthService_GetLineAuthURL_Call struct {
	*mock.Call
}

// GetLineAuthURL is a helper method to define mock.On call
//   - state string
func (_e *MockAuthService_Expecter) GetLineAuthURL(state interface{}) *MockAuthService_GetLineAuthURL_Call {
	return &MockAuthService_GetLineAuthURL_Call{Call: _e.mock.On("GetLineAuthURL", state)}
}

func (_c *MockAuthService_GetLineAuthURL_Call) Run(run func(state string)) *MockAuthService_GetLineAuthURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAuthService_GetLineAuthURL_Call) Return(url string, configured bool) *MockAuthService_GetLineAuthURL_Call {
	_c.Call.Return(url, configured)
	return _c
}

func (_c *MockAuthService_GetLineAuthURL_Call) RunAndReturn(run func(string) (string, bool)) *MockAuthService_GetLineAuthURL_Call {
	_c.Call.Return(run)
	return _c
}

// IssueOAuthAccessToken provides a mock function with given fields: user
func (_m *MockAuthService) IssueOAuthAccessToken(user *db.User) (string, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for IssueOAuthAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*db.User) (string, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(*db.User) string); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*db.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_IssueOAuthAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueOAuthAccessToken'
type MockAuthService_IssueOAuthAccessToken_Call struct {
	*mock.Call
}

// IssueOAuthAccessToken is a helper method to define mock.On call
//   - user *db.User
func (_e *MockAuthService_Expecter) IssueOAuthAccessToken(user interface{}) *MockAuthService_IssueOAuthAccessToken_Call {
	return &MockAuthService_IssueOAuthAccessToken_Call{Call: _e.mock.On("IssueOAuthAccessToken", user)}
}

func (_c *MockAuthService_IssueOAuthAccessToken_Call) Run(run func(user *db.User)) *MockAuthService_IssueOAuthAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*db.User))
	})
	return _c
}

func (_c *MockAuthService_IssueOAuthAccessToken_Call) Return(_a0 string, _a1 error) *MockAuthService_IssueOAuthAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_IssueOAuthAccessToken_Call) RunAndReturn(run func(*db.User) (string, error)) *MockAuthService_IssueOAuthAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, username, password
func (_m *MockAuthService) Login(ctx context.Context, username string, password string) (*services.LoginResult, error) {
	ret := _m.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *services.LoginResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*services.LoginResult, error)); ok {
		return rf(ctx, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *services.LoginResult); ok {
		r0 = rf(ctx, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.LoginResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockAuthService_Expecter) Login(ctx interface{}, username interface{}, password interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, username, password)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, username string, password string)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(_a0 *services.LoginResult, _a1 error) *MockAuthService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(context.Context, string, string) (*services.LoginResult, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessKakaoCallback provides a mock function with given fields: ctx, code, state
func (_m *MockAuthService) ProcessKakaoCallback(ctx context.Context, code string, state string) (*db.User, error) {
	ret := _m.Called(ctx, code, state)

	if len(ret) == 0 {
		panic("no return value specified for ProcessKakaoCallback")
	}

	var r0 *db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*db.User, error)); ok {
		return rf(ctx, code, state)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *db.User); ok {
		r0 = rf(ctx, code, state)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, code, state)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_ProcessKakaoCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessKakaoCallback'
type MockAuthService_ProcessKakaoCallback_Call struct {
	*mock.Call
}

// ProcessKakaoCallback is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - state string
func (_e *MockAuthService_Expecter) ProcessKakaoCallback(ctx interface{}, code interface{}, state interface{}) *MockAuthService_ProcessKakaoCallback_Call {
	return &MockAuthService_ProcessKakaoCallback_Call{Call: _e.mock.On("ProcessKakaoCallback", ctx, code, state)}
}

func (_c *MockAuthService_ProcessKakaoCallback_Call) Run(run func(ctx context.Context, code string, state string)) *MockAuthService_ProcessKakaoCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthService_ProcessKakaoCallback_Call) Return(_a0 *db.User, _a1 error) *MockAuthService_ProcessKakaoCallback_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_ProcessKakaoCallback_Call) RunAndReturn(run func(context.Context, string, string) (*db.User, error)) *MockAuthService_ProcessKakaoCallback_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessLineCallback provides a mock function with given fields: ctx, code, state
func (_m *MockAuthService) ProcessLineCallback(ctx context.Context, code string, state string) (*db.User, error) {
	ret := _m.Called(ctx, code, state)

	if len(ret) == 0 {
		panic("no return value specified for ProcessLineCallback")
	}

	var r0 *db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*db.User, error)); ok {
		return rf(ctx, code, state)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *db.User); ok {
		r0 = rf(ctx, code, state)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, code, state)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_ProcessLineCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessLineCallback'
type MockAuthService_ProcessLineCallback_Call struct {
	*mock.Call
}

// ProcessLineCallback is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - state string
func (_e *MockAuthService_Expecter) ProcessLineCallback(ctx interface{}, code interface{}, state interface{}) *MockAuthService_ProcessLineCallback_Call {
	return &MockAuthService_ProcessLineCallback_Call{Call: _e.mock.On("ProcessLineCallback", ctx, code, state)}
}

func (_c *MockAuthService_ProcessLineCallback_Call) Run(run func(ctx context.Context, code string, state string)) *MockAuthService_ProcessLineCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthService_ProcessLineCallback_Call) Return(_a0 *db.User, _a1 error) *MockAuthService_ProcessLineCallback_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_ProcessLineCallback_Call) RunAndReturn(run func(context.Context, string, string) (*db.User, error)) *MockAuthService_ProcessLineCallback_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveInviteState provides a mock function with given fields: ctx, state
func (_m *MockAuthService) ResolveInviteState(ctx context.Context, state string) (*services.InviteState, error) {
	ret := _m.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for ResolveInviteState")
	}

	var r0 *services.InviteState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*services.InviteState, error)); ok {
		return rf(ctx, state)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *services.InviteState); ok {
		r0 = rf(ctx, state)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.InviteState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, state)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_ResolveInviteState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveInviteState'
type MockAuthService_ResolveInviteState_Call struct {
	*mock.Call
}

// ResolveInviteState is a helper method to define mock.On call
//   - ctx context.Context
//   - state string
func (_e *MockAuthService_Expecter) ResolveInviteState(ctx interface{}, state interface{}) *MockAuthService_ResolveInviteState_Call {
	return &MockAuthService_ResolveInviteState_Call{Call: _e.mock.On("ResolveInviteState", ctx, state)}
}

func (_c *MockAuthService_ResolveInviteState_Call) Run(run func(ctx context.Context, state string)) *MockAuthService_ResolveInviteState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_ResolveInviteState_Call) Return(_a0 *services.InviteState, _a1 error) *MockAuthService_ResolveInviteState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_ResolveInviteState_Call) RunAndReturn(run func(context.Context, string) (*services.InviteState, error)) *MockAuthService_ResolveInviteState_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
