// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockLikeService is an autogenerated mock type for the LikeService type
type MockLikeService struct {
	mock.Mock
}

type MockLikeService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLikeService) EXPECT() *MockLikeService_Expecter {
	return &MockLikeService_Expecter{mock: &_m.Mock}
}

// IsMediaItemLiked provides a mock function with given fields: ctx, mediaItemID, userID
func (_m *MockLikeService) IsMediaItemLiked(ctx context.Context, mediaItemID int32, userID int32) (bool, error) {
	ret := _m.Called(ctx, mediaItemID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsMediaItemLiked")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) (bool, error)); ok {
		return rf(ctx, mediaItemID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) bool); ok {
		r0 = rf(ctx, mediaItemID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32) error); ok {
		r1 = rf(ctx, mediaItemID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLikeService_IsMediaItemLiked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsMediaItemLiked'
type MockLikeService_IsMediaItemLiked_Call struct {
	*mock.Call
}

// IsMediaItemLiked is a helper method to define mock.On call
//   - ctx context.Context
//   - mediaItemID int32
//   - userID int32
func (_e *MockLikeService_Expecter) IsMediaItemLiked(ctx interface{}, mediaItemID interface{}, userID interface{}) *MockLikeService_IsMediaItemLiked_Call {
	return &MockLikeService_IsMediaItemLiked_Call{Call: _e.mock.On("IsMediaItemLiked", ctx, mediaItemID, userID)}
}

func (_c *MockLikeService_IsMediaItemLiked_Call) Run(run func(ctx context.Context, mediaItemID int32, userID int32)) *MockLikeService_IsMediaItemLiked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *MockLikeService_IsMediaItemLiked_Call) Return(_a0 bool, _a1 error) *MockLikeService_IsMediaItemLiked_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLikeService_IsMediaItemLiked_Call) RunAndReturn(run func(context.Context, int32, int32) (bool, error)) *MockLikeService_IsMediaItemLiked_Call {
	_c.Call.Return(run)
	return _c
}

// LikeMediaItem provides a mock function with given fields: ctx, mediaItemID, userID
func (_m *MockLikeService) LikeMediaItem(ctx context.Context, mediaItemID int32, userID int32) error {
	ret := _m.Called(ctx, mediaItemID, userID)

	if len(ret) == 0 {
		panic("no return value specified for LikeMediaItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) error); ok {
		r0 = rf(ctx, mediaItemID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLikeService_LikeMediaItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LikeMediaItem'
type MockLikeService_LikeMediaItem_Call struct {
	*mock.Call
}

// LikeMediaItem is a helper method to define mock.On call
//   - ctx context.Context
//   - mediaItemID int32
//   - userID int32
func (_e *MockLikeService_Expecter) LikeMediaItem(ctx interface{}, mediaItemID interface{}, userID interface{}) *MockLikeService_LikeMediaItem_Call {
	return &MockLikeService_LikeMediaItem_Call{Call: _e.mock.On("LikeMediaItem", ctx, mediaItemID, userID)}
}

func (_c *MockLikeService_LikeMediaItem_Call) Run(run func(ctx context.Context, mediaItemID int32, userID int32)) *MockLikeService_LikeMediaItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *MockLikeService_LikeMediaItem_Call) Return(_a0 error) *MockLikeService_LikeMediaItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLikeService_LikeMediaItem_Call) RunAndReturn(run func(context.Context, int32, int32) error) *MockLikeService_LikeMediaItem_Call {
	_c.Call.Return(run)
	return _c
}

// UnlikeMediaItem provides a mock function with given fields: ctx, mediaItemID, userID
func (_m *MockLikeService) UnlikeMediaItem(ctx context.Context, mediaItemID int32, userID int32) error {
	ret := _m.Called(ctx, mediaItemID, userID)

	if len(ret) == 0 {
		panic("no return value specified for UnlikeMediaItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) error); ok {
		r0 = rf(ctx, mediaItemID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLikeService_UnlikeMediaItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlikeMediaItem'
type MockLikeService_UnlikeMediaItem_Call struct {
	*mock.Call
}

// UnlikeMediaItem is a helper method to define mock.On call
//   - ctx context.Context
//   - mediaItemID int32
//   - userID int32
func (_e *MockLikeService_Expecter) UnlikeMediaItem(ctx interface{}, mediaItemID interface{}, userID interface{}) *MockLikeService_UnlikeMediaItem_Call {
	return &MockLikeService_UnlikeMediaItem_Call{Call: _e.mock.On("UnlikeMediaItem", ctx, mediaItemID, userID)}
}

func (_c *MockLikeService_UnlikeMediaItem_Call) Run(run func(ctx context.Context, mediaItemID int32, userID int32)) *MockLikeService_UnlikeMediaItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *MockLikeService_UnlikeMediaItem_Call) Return(_a0 error) *MockLikeService_UnlikeMediaItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLikeService_UnlikeMediaItem_Call) RunAndReturn(run func(context.Context, int32, int32) error) *MockLikeService_UnlikeMediaItem_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLikeService creates a new instance of MockLikeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLikeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLikeService {
	mock := &MockLikeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
