// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "github.com/ywl0806/yuno_kiroku/internal/db"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, params
func (_m *MockUserService) CreateUser(ctx context.Context, params db.CreateUserParams) (db.User, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) (db.User, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) db.User); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateUserParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - params db.CreateUserParams
func (_e *MockUserService_Expecter) CreateUser(ctx interface{}, params interface{}) *MockUserService_CreateUser_Call {
	return &MockUserService_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, params)}
}

func (_c *MockUserService_CreateUser_Call) Run(run func(ctx context.Context, params db.CreateUserParams)) *MockUserService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateUserParams))
	})
	return _c
}

func (_c *MockUserService_CreateUser_Call) Return(_a0 db.User, _a1 error) *MockUserService_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_CreateUser_Call) RunAndReturn(run func(context.Context, db.CreateUserParams) (db.User, error)) *MockUserService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindOrCreateUserOAuth provides a mock function with given fields: ctx, provider, providerUserID, displayName, familyID, groupID, familyTitle, customFamilyTitle
func (_m *MockUserService) FindOrCreateUserOAuth(ctx context.Context, provider string, providerUserID string, displayName string, familyID int32, groupID int32, familyTitle string, customFamilyTitle string) (db.User, error) {
	ret := _m.Called(ctx, provider, providerUserID, displayName, familyID, groupID, familyTitle, customFamilyTitle)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreateUserOAuth")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int32, int32, string, string) (db.User, error)); ok {
		return rf(ctx, provider, providerUserID, displayName, familyID, groupID, familyTitle, customFamilyTitle)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int32, int32, string, string) db.User); ok {
		r0 = rf(ctx, provider, providerUserID, displayName, familyID, groupID, familyTitle, customFamilyTitle)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int32, int32, string, string) error); ok {
		r1 = rf(ctx, provider, providerUserID, displayName, familyID, groupID, familyTitle, customFamilyTitle)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_FindOrCreateUserOAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrCreateUserOAuth'
type MockUserService_FindOrCreateUserOAuth_Call struct {
	*mock.Call
}

// FindOrCreateUserOAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - providerUserID string
//   - displayName string
//   - familyID int32
//   - groupID int32
//   - familyTitle string
//   - customFamilyTitle string
func (_e *MockUserService_Expecter) FindOrCreateUserOAuth(ctx interface{}, provider interface{}, providerUserID interface{}, displayName interface{}, familyID interface{}, groupID interface{}, familyTitle interface{}, customFamilyTitle interface{}) *MockUserService_FindOrCreateUserOAuth_Call {
	return &MockUserService_FindOrCreateUserOAuth_Call{Call: _e.mock.On("FindOrCreateUserOAuth", ctx, provider, providerUserID, displayName, familyID, groupID, familyTitle, customFamilyTitle)}
}

func (_c *MockUserService_FindOrCreateUserOAuth_Call) Run(run func(ctx context.Context, provider string, providerUserID string, displayName string, familyID int32, groupID int32, familyTitle string, customFamilyTitle string)) *MockUserService_FindOrCreateUserOAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(int32), args[5].(int32), args[6].(string), args[7].(string))
	})
	return _c
}

func (_c *MockUserService_FindOrCreateUserOAuth_Call) Return(_a0 db.User, _a1 error) *MockUserService_FindOrCreateUserOAuth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_FindOrCreateUserOAuth_Call) RunAndReturn(run func(context.Context, string, string, string, int32, int32, string, string) (db.User, error)) *MockUserService_FindOrCreateUserOAuth_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByProvider provides a mock function with given fields: ctx, provider, providerUserID
func (_m *MockUserService) FindUserByProvider(ctx context.Context, provider string, providerUserID string) (db.User, error) {
	ret := _m.Called(ctx, provider, providerUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByProvider")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (db.User, error)); ok {
		return rf(ctx, provider, providerUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) db.User); ok {
		r0 = rf(ctx, provider, providerUserID)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, provider, providerUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_FindUserByProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByProvider'
type MockUserService_FindUserByProvider_Call struct {
	*mock.Call
}

// FindUserByProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - providerUserID string
func (_e *MockUserService_Expecter) FindUserByProvider(ctx interface{}, provider interface{}, providerUserID interface{}) *MockUserService_FindUserByProvider_Call {
	return &MockUserService_FindUserByProvider_Call{Call: _e.mock.On("FindUserByProvider", ctx, provider, providerUserID)}
}

func (_c *MockUserService_FindUserByProvider_Call) Run(run func(ctx context.Context, provider string, providerUserID string)) *MockUserService_FindUserByProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserService_FindUserByProvider_Call) Return(_a0 db.User, _a1 error) *MockUserService_FindUserByProvider_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_FindUserByProvider_Call) RunAndReturn(run func(context.Context, string, string) (db.User, error)) *MockUserService_FindUserByProvider_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByUsername provides a mock function with given fields: ctx, username
func (_m *MockUserService) FindUserByUsername(ctx context.Context, username string) (db.User, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByUsername")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.User); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_FindUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByUsername'
type MockUserService_FindUserByUsername_Call struct {
	*mock.Call
}

// FindUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserService_Expecter) FindUserByUsername(ctx interface{}, username interface{}) *MockUserService_FindUserByUsername_Call {
	return &MockUserService_FindUserByUsername_Call{Call: _e.mock.On("FindUserByUsername", ctx, username)}
}

func (_c *MockUserService_FindUserByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserService_FindUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserService_FindUserByUsername_Call) Return(_a0 db.User, _a1 error) *MockUserService_FindUserByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_FindUserByUsername_Call) RunAndReturn(run func(context.Context, string) (db.User, error)) *MockUserService_FindUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetMembers provides a mock function with given fields: ctx, familyID
func (_m *MockUserService) GetMembers(ctx context.Context, familyID int32) ([]db.User, error) {
	ret := _m.Called(ctx, familyID)

	if len(ret) == 0 {
		panic("no return value specified for GetMembers")
	}

	var r0 []db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]db.User, error)); ok {
		return rf(ctx, familyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []db.User); ok {
		r0 = rf(ctx, familyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, familyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_GetMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMembers'
type MockUserService_GetMembers_Call struct {
	*mock.Call
}

// GetMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID int32
func (_e *MockUserService_Expecter) GetMembers(ctx interface{}, familyID interface{}) *MockUserService_GetMembers_Call {
	return &MockUserService_GetMembers_Call{Call: _e.mock.On("GetMembers", ctx, familyID)}
}

func (_c *MockUserService_GetMembers_Call) Run(run func(ctx context.Context, familyID int32)) *MockUserService_GetMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockUserService_GetMembers_Call) Return(_a0 []db.User, _a1 error) *MockUserService_GetMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetMembers_Call) RunAndReturn(run func(context.Context, int32) ([]db.User, error)) *MockUserService_GetMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, userID, familyID
func (_m *MockUserService) GetUserByID(ctx context.Context, userID int32, familyID int32) (db.User, error) {
	ret := _m.Called(ctx, userID, familyID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) (db.User, error)); ok {
		return rf(ctx, userID, familyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) db.User); ok {
		r0 = rf(ctx, userID, familyID)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32) error); ok {
		r1 = rf(ctx, userID, familyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserService_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int32
//   - familyID int32
func (_e *MockUserService_Expecter) GetUserByID(ctx interface{}, userID interface{}, familyID interface{}) *MockUserService_GetUserByID_Call {
	return &MockUserService_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID, familyID)}
}

func (_c *MockUserService_GetUserByID_Call) Run(run func(ctx context.Context, userID int32, familyID int32)) *MockUserService_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *MockUserService_GetUserByID_Call) Return(_a0 db.User, _a1 error) *MockUserService_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetUserByID_Call) RunAndReturn(run func(context.Context, int32, int32) (db.User, error)) *MockUserService_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMe provides a mock function with given fields: ctx, userID, name
func (_m *MockUserService) UpdateMe(ctx context.Context, userID int32, name string) (db.User, error) {
	ret := _m.Called(ctx, userID, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMe")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string) (db.User, error)); ok {
		return rf(ctx, userID, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, string) db.User); ok {
		r0 = rf(ctx, userID, name)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, string) error); ok {
		r1 = rf(ctx, userID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_UpdateMe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMe'
type MockUserService_UpdateMe_Call struct {
	*mock.Call
}

// UpdateMe is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int32
//   - name string
func (_e *MockUserService_Expecter) UpdateMe(ctx interface{}, userID interface{}, name interface{}) *MockUserService_UpdateMe_Call {
	return &MockUserService_UpdateMe_Call{Call: _e.mock.On("UpdateMe", ctx, userID, name)}
}

func (_c *MockUserService_UpdateMe_Call) Run(run func(ctx context.Context, userID int32, name string)) *MockUserService_UpdateMe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(string))
	})
	return _c
}

func (_c *MockUserService_UpdateMe_Call) Return(_a0 db.User, _a1 error) *MockUserService_UpdateMe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_UpdateMe_Call) RunAndReturn(run func(context.Context, int32, string) (db.User, error)) *MockUserService_UpdateMe_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMember provides a mock function with given fields: ctx, memberID, familyID, groupID, familyTitle, customFamilyTitle
func (_m *MockUserService) UpdateMember(ctx context.Context, memberID int32, familyID int32, groupID int32, familyTitle string, customFamilyTitle string) (db.User, error) {
	ret := _m.Called(ctx, memberID, familyID, groupID, familyTitle, customFamilyTitle)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMember")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32, int32, string, string) (db.User, error)); ok {
		return rf(ctx, memberID, familyID, groupID, familyTitle, customFamilyTitle)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32, int32, string, string) db.User); ok {
		r0 = rf(ctx, memberID, familyID, groupID, familyTitle, customFamilyTitle)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32, int32, string, string) error); ok {
		r1 = rf(ctx, memberID, familyID, groupID, familyTitle, customFamilyTitle)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_UpdateMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMember'
type MockUserService_UpdateMember_Call struct {
	*mock.Call
}

// UpdateMember is a helper method to define mock.On call
//   - ctx context.Context
//   - memberID int32
//   - familyID int32
//   - groupID int32
//   - familyTitle string
//   - customFamilyTitle string
func (_e *MockUserService_Expecter) UpdateMember(ctx interface{}, memberID interface{}, familyID interface{}, groupID interface{}, familyTitle interface{}, customFamilyTitle interface{}) *MockUserService_UpdateMember_Call {
	return &MockUserService_UpdateMember_Call{Call: _e.mock.On("UpdateMember", ctx, memberID, familyID, groupID, familyTitle, customFamilyTitle)}
}

func (_c *MockUserService_UpdateMember_Call) Run(run func(ctx context.Context, memberID int32, familyID int32, groupID int32, familyTitle string, customFamilyTitle string)) *MockUserService_UpdateMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32), args[3].(int32), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockUserService_UpdateMember_Call) Return(_a0 db.User, _a1 error) *MockUserService_UpdateMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_UpdateMember_Call) RunAndReturn(run func(context.Context, int32, int32, int32, string, string) (db.User, error)) *MockUserService_UpdateMember_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateCreateUserParams provides a mock function with given fields: ctx, params
func (_m *MockUserService) ValidateCreateUserParams(ctx context.Context, params db.CreateUserParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCreateUserParams")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_ValidateCreateUserParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateCreateUserParams'
type MockUserService_ValidateCreateUserParams_Call struct {
	*mock.Call
}

// ValidateCreateUserParams is a helper method to define mock.On call
//   - ctx context.Context
//   - params db.CreateUserParams
func (_e *MockUserService_Expecter) ValidateCreateUserParams(ctx interface{}, params interface{}) *MockUserService_ValidateCreateUserParams_Call {
	return &MockUserService_ValidateCreateUserParams_Call{Call: _e.mock.On("ValidateCreateUserParams", ctx, params)}
}

func (_c *MockUserService_ValidateCreateUserParams_Call) Run(run func(ctx context.Context, params db.CreateUserParams)) *MockUserService_ValidateCreateUserParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateUserParams))
	})
	return _c
}

func (_c *MockUserService_ValidateCreateUserParams_Call) Return(_a0 error) *MockUserService_ValidateCreateUserParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_ValidateCreateUserParams_Call) RunAndReturn(run func(context.Context, db.CreateUserParams) error) *MockUserService_ValidateCreateUserParams_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
