// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "github.com/ywl0806/yuno_kiroku/internal/db"

	time "time"
)

// MockKidService is an autogenerated mock type for the KidService type
type MockKidService struct {
	mock.Mock
}

type MockKidService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKidService) EXPECT() *MockKidService_Expecter {
	return &MockKidService_Expecter{mock: &_m.Mock}
}

// CreateKid provides a mock function with given fields: ctx, familyID, name, birthDate, identityID
func (_m *MockKidService) CreateKid(ctx context.Context, familyID int32, name *string, birthDate *time.Time, identityID *int32) (db.Kid, error) {
	ret := _m.Called(ctx, familyID, name, birthDate, identityID)

	if len(ret) == 0 {
		panic("no return value specified for CreateKid")
	}

	var r0 db.Kid
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, *string, *time.Time, *int32) (db.Kid, error)); ok {
		return rf(ctx, familyID, name, birthDate, identityID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, *string, *time.Time, *int32) db.Kid); ok {
		r0 = rf(ctx, familyID, name, birthDate, identityID)
	} else {
		r0 = ret.Get(0).(db.Kid)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, *string, *time.Time, *int32) error); ok {
		r1 = rf(ctx, familyID, name, birthDate, identityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKidService_CreateKid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKid'
type MockKidService_CreateKid_Call struct {
	*mock.Call
}

// CreateKid is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID int32
//   - name *string
//   - birthDate *time.Time
//   - identityID *int32
func (_e *MockKidService_Expecter) CreateKid(ctx interface{}, familyID interface{}, name interface{}, birthDate interface{}, identityID interface{}) *MockKidService_CreateKid_Call {
	return &MockKidService_CreateKid_Call{Call: _e.mock.On("CreateKid", ctx, familyID, name, birthDate, identityID)}
}

func (_c *MockKidService_CreateKid_Call) Run(run func(ctx context.Context, familyID int32, name *string, birthDate *time.Time, identityID *int32)) *MockKidService_CreateKid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(*string), args[3].(*time.Time), args[4].(*int32))
	})
	return _c
}

func (_c *MockKidService_CreateKid_Call) Return(_a0 db.Kid, _a1 error) *MockKidService_CreateKid_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKidService_CreateKid_Call) RunAndReturn(run func(context.Context, int32, *string, *time.Time, *int32) (db.Kid, error)) *MockKidService_CreateKid_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteKid provides a mock function with given fields: ctx, id
func (_m *MockKidService) DeleteKid(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteKid")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKidService_DeleteKid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteKid'
type MockKidService_DeleteKid_Call struct {
	*mock.Call
}

// DeleteKid is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockKidService_Expecter) DeleteKid(ctx interface{}, id interface{}) *MockKidService_DeleteKid_Call {
	return &MockKidService_DeleteKid_Call{Call: _e.mock.On("DeleteKid", ctx, id)}
}

func (_c *MockKidService_DeleteKid_Call) Run(run func(ctx context.Context, id int32)) *MockKidService_DeleteKid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockKidService_DeleteKid_Call) Return(_a0 error) *MockKidService_DeleteKid_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKidService_DeleteKid_Call) RunAndReturn(run func(context.Context, int32) error) *MockKidService_DeleteKid_Call {
	_c.Call.Return(run)
	return _c
}

// GetKidByID provides a mock function with given fields: ctx, id
func (_m *MockKidService) GetKidByID(ctx context.Context, id int32) (db.Kid, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetKidByID")
	}

	var r0 db.Kid
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (db.Kid, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) db.Kid); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Kid)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKidService_GetKidByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKidByID'
type MockKidService_GetKidByID_Call struct {
	*mock.Call
}

// GetKidByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockKidService_Expecter) GetKidByID(ctx interface{}, id interface{}) *MockKidService_GetKidByID_Call {
	return &MockKidService_GetKidByID_Call{Call: _e.mock.On("GetKidByID", ctx, id)}
}

func (_c *MockKidService_GetKidByID_Call) Run(run func(ctx context.Context, id int32)) *MockKidService_GetKidByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockKidService_GetKidByID_Call) Return(_a0 db.Kid, _a1 error) *MockKidService_GetKidByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKidService_GetKidByID_Call) RunAndReturn(run func(context.Context, int32) (db.Kid, error)) *MockKidService_GetKidByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetKids provides a mock function with given fields: ctx, familyID
func (_m *MockKidService) GetKids(ctx context.Context, familyID int32) ([]db.Kid, error) {
	ret := _m.Called(ctx, familyID)

	if len(ret) == 0 {
		panic("no return value specified for GetKids")
	}

	var r0 []db.Kid
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]db.Kid, error)); ok {
		return rf(ctx, familyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []db.Kid); ok {
		r0 = rf(ctx, familyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Kid)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, familyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKidService_GetKids_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKids'
type MockKidService_GetKids_Call struct {
	*mock.Call
}

// GetKids is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID int32
func (_e *MockKidService_Expecter) GetKids(ctx interface{}, familyID interface{}) *MockKidService_GetKids_Call {
	return &MockKidService_GetKids_Call{Call: _e.mock.On("GetKids", ctx, familyID)}
}

func (_c *MockKidService_GetKids_Call) Run(run func(ctx context.Context, familyID int32)) *MockKidService_GetKids_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockKidService_GetKids_Call) Return(_a0 []db.Kid, _a1 error) *MockKidService_GetKids_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKidService_GetKids_Call) RunAndReturn(run func(context.Context, int32) ([]db.Kid, error)) *MockKidService_GetKids_Call {
	_c.Call.Return(run)
	return _c
}

// GetKidsWithFaceImg provides a mock function with given fields: ctx, familyID, year, month
func (_m *MockKidService) GetKidsWithFaceImg(ctx context.Context, familyID int32, year int, month int) ([]db.GetKidsWithRandomFaceImgRow, error) {
	ret := _m.Called(ctx, familyID, year, month)

	if len(ret) == 0 {
		panic("no return value specified for GetKidsWithFaceImg")
	}

	var r0 []db.GetKidsWithRandomFaceImgRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int, int) ([]db.GetKidsWithRandomFaceImgRow, error)); ok {
		return rf(ctx, familyID, year, month)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int, int) []db.GetKidsWithRandomFaceImgRow); ok {
		r0 = rf(ctx, familyID, year, month)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetKidsWithRandomFaceImgRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int, int) error); ok {
		r1 = rf(ctx, familyID, year, month)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKidService_GetKidsWithFaceImg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKidsWithFaceImg'
type MockKidService_GetKidsWithFaceImg_Call struct {
	*mock.Call
}

// GetKidsWithFaceImg is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID int32
//   - year int
//   - month int
func (_e *MockKidService_Expecter) GetKidsWithFaceImg(ctx interface{}, familyID interface{}, year interface{}, month interface{}) *MockKidService_GetKidsWithFaceImg_Call {
	return &MockKidService_GetKidsWithFaceImg_Call{Call: _e.mock.On("GetKidsWithFaceImg", ctx, familyID, year, month)}
}

func (_c *MockKidService_GetKidsWithFaceImg_Call) Run(run func(ctx context.Context, familyID int32, year int, month int)) *MockKidService_GetKidsWithFaceImg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockKidService_GetKidsWithFaceImg_Call) Return(_a0 []db.GetKidsWithRandomFaceImgRow, _a1 error) *MockKidService_GetKidsWithFaceImg_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKidService_GetKidsWithFaceImg_Call) RunAndReturn(run func(context.Context, int32, int, int) ([]db.GetKidsWithRandomFaceImgRow, error)) *MockKidService_GetKidsWithFaceImg_Call {
	_c.Call.Return(run)
	return _c
}

// GetKidsWithFaceImgFast provides a mock function with given fields: ctx, familyID, currentYear, currentMonth
func (_m *MockKidService) GetKidsWithFaceImgFast(ctx context.Context, familyID int32, currentYear int, currentMonth int) ([]db.GetKidsWithRandomFaceImgRow, error) {
	ret := _m.Called(ctx, familyID, currentYear, currentMonth)

	if len(ret) == 0 {
		panic("no return value specified for GetKidsWithFaceImgFast")
	}

	var r0 []db.GetKidsWithRandomFaceImgRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int, int) ([]db.GetKidsWithRandomFaceImgRow, error)); ok {
		return rf(ctx, familyID, currentYear, currentMonth)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int, int) []db.GetKidsWithRandomFaceImgRow); ok {
		r0 = rf(ctx, familyID, currentYear, currentMonth)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetKidsWithRandomFaceImgRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int, int) error); ok {
		r1 = rf(ctx, familyID, currentYear, currentMonth)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKidService_GetKidsWithFaceImgFast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKidsWithFaceImgFast'
type MockKidService_GetKidsWithFaceImgFast_Call struct {
	*mock.Call
}

// GetKidsWithFaceImgFast is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID int32
//   - currentYear int
//   - currentMonth int
func (_e *MockKidService_Expecter) GetKidsWithFaceImgFast(ctx interface{}, familyID interface{}, currentYear interface{}, currentMonth interface{}) *MockKidService_GetKidsWithFaceImgFast_Call {
	return &MockKidService_GetKidsWithFaceImgFast_Call{Call: _e.mock.On("GetKidsWithFaceImgFast", ctx, familyID, currentYear, currentMonth)}
}

func (_c *MockKidService_GetKidsWithFaceImgFast_Call) Run(run func(ctx context.Context, familyID int32, currentYear int, currentMonth int)) *MockKidService_GetKidsWithFaceImgFast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockKidService_GetKidsWithFaceImgFast_Call) Return(_a0 []db.GetKidsWithRandomFaceImgRow, _a1 error) *MockKidService_GetKidsWithFaceImgFast_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKidService_GetKidsWithFaceImgFast_Call) RunAndReturn(run func(context.Context, int32, int, int) ([]db.GetKidsWithRandomFaceImgRow, error)) *MockKidService_GetKidsWithFaceImgFast_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateKid provides a mock function with given fields: ctx, id, name, birthDate, identityID
func (_m *MockKidService) UpdateKid(ctx context.Context, id int32, name *string, birthDate *time.Time, identityID *int32) (db.Kid, error) {
	ret := _m.Called(ctx, id, name, birthDate, identityID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateKid")
	}

	var r0 db.Kid
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, *string, *time.Time, *int32) (db.Kid, error)); ok {
		return rf(ctx, id, name, birthDate, identityID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, *string, *time.Time, *int32) db.Kid); ok {
		r0 = rf(ctx, id, name, birthDate, identityID)
	} else {
		r0 = ret.Get(0).(db.Kid)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, *string, *time.Time, *int32) error); ok {
		r1 = rf(ctx, id, name, birthDate, identityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockKidService_UpdateKid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateKid'
type MockKidService_UpdateKid_Call struct {
	*mock.Call
}

// UpdateKid is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - name *string
//   - birthDate *time.Time
//   - identityID *int32
func (_e *MockKidService_Expecter) UpdateKid(ctx interface{}, id interface{}, name interface{}, birthDate interface{}, identityID interface{}) *MockKidService_UpdateKid_Call {
	return &MockKidService_UpdateKid_Call{Call: _e.mock.On("UpdateKid", ctx, id, name, birthDate, identityID)}
}

func (_c *MockKidService_UpdateKid_Call) Run(run func(ctx context.Context, id int32, name *string, birthDate *time.Time, identityID *int32)) *MockKidService_UpdateKid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(*string), args[3].(*time.Time), args[4].(*int32))
	})
	return _c
}

func (_c *MockKidService_UpdateKid_Call) Return(_a0 db.Kid, _a1 error) *MockKidService_UpdateKid_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockKidService_UpdateKid_Call) RunAndReturn(run func(context.Context, int32, *string, *time.Time, *int32) (db.Kid, error)) *MockKidService_UpdateKid_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKidService creates a new instance of MockKidService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKidService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKidService {
	mock := &MockKidService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
