// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	db "github.com/ywl0806/yuno_kiroku/internal/db"
	enums "github.com/ywl0806/yuno_kiroku/internal/enums"

	mock "github.com/stretchr/testify/mock"

	services "github.com/ywl0806/yuno_kiroku/internal/services"

	time "time"
)

// MockMediaItemService is an autogenerated mock type for the MediaItemService type
type MockMediaItemService struct {
	mock.Mock
}

type MockMediaItemService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMediaItemService) EXPECT() *MockMediaItemService_Expecter {
	return &MockMediaItemService_Expecter{mock: &_m.Mock}
}

// CreatePresignedUpload provides a mock function with given fields: ctx, fileName, contentType, familyId, albumId, uploadBatchID
func (_m *MockMediaItemService) CreatePresignedUpload(ctx context.Context, fileName string, contentType string, familyId int32, albumId int32, uploadBatchID int32) (*services.PresignedUploadResult, error) {
	ret := _m.Called(ctx, fileName, contentType, familyId, albumId, uploadBatchID)

	if len(ret) == 0 {
		panic("no return value specified for CreatePresignedUpload")
	}

	var r0 *services.PresignedUploadResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int32, int32, int32) (*services.PresignedUploadResult, error)); ok {
		return rf(ctx, fileName, contentType, familyId, albumId, uploadBatchID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int32, int32, int32) *services.PresignedUploadResult); ok {
		r0 = rf(ctx, fileName, contentType, familyId, albumId, uploadBatchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.PresignedUploadResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int32, int32, int32) error); ok {
		r1 = rf(ctx, fileName, contentType, familyId, albumId, uploadBatchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaItemService_CreatePresignedUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePresignedUpload'
type MockMediaItemService_CreatePresignedUpload_Call struct {
	*mock.Call
}

// CreatePresignedUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - fileName string
//   - contentType string
//   - familyId int32
//   - albumId int32
//   - uploadBatchID int32
func (_e *MockMediaItemService_Expecter) CreatePresignedUpload(ctx interface{}, fileName interface{}, contentType interface{}, familyId interface{}, albumId interface{}, uploadBatchID interface{}) *MockMediaItemService_CreatePresignedUpload_Call {
	return &MockMediaItemService_CreatePresignedUpload_Call{Call: _e.mock.On("CreatePresignedUpload", ctx, fileName, contentType, familyId, albumId, uploadBatchID)}
}

func (_c *MockMediaItemService_CreatePresignedUpload_Call) Run(run func(ctx context.Context, fileName string, contentType string, familyId int32, albumId int32, uploadBatchID int32)) *MockMediaItemService_CreatePresignedUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int32), args[4].(int32), args[5].(int32))
	})
	return _c
}

func (_c *MockMediaItemService_CreatePresignedUpload_Call) Return(_a0 *services.PresignedUploadResult, _a1 error) *MockMediaItemService_CreatePresignedUpload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaItemService_CreatePresignedUpload_Call) RunAndReturn(run func(context.Context, string, string, int32, int32, int32) (*services.PresignedUploadResult, error)) *MockMediaItemService_CreatePresignedUpload_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUploadBatch provides a mock function with given fields: ctx, familyId, albumId
func (_m *MockMediaItemService) CreateUploadBatch(ctx context.Context, familyId int32, albumId int32) (*db.UploadBatch, error) {
	ret := _m.Called(ctx, familyId, albumId)

	if len(ret) == 0 {
		panic("no return value specified for CreateUploadBatch")
	}

	var r0 *db.UploadBatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) (*db.UploadBatch, error)); ok {
		return rf(ctx, familyId, albumId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) *db.UploadBatch); ok {
		r0 = rf(ctx, familyId, albumId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.UploadBatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32) error); ok {
		r1 = rf(ctx, familyId, albumId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaItemService_CreateUploadBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUploadBatch'
type MockMediaItemService_CreateUploadBatch_Call struct {
	*mock.Call
}

// CreateUploadBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - familyId int32
//   - albumId int32
func (_e *MockMediaItemService_Expecter) CreateUploadBatch(ctx interface{}, familyId interface{}, albumId interface{}) *MockMediaItemService_CreateUploadBatch_Call {
	return &MockMediaItemService_CreateUploadBatch_Call{Call: _e.mock.On("CreateUploadBatch", ctx, familyId, albumId)}
}

func (_c *MockMediaItemService_CreateUploadBatch_Call) Run(run func(ctx context.Context, familyId int32, albumId int32)) *MockMediaItemService_CreateUploadBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *MockMediaItemService_CreateUploadBatch_Call) Return(_a0 *db.UploadBatch, _a1 error) *MockMediaItemService_CreateUploadBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaItemService_CreateUploadBatch_Call) RunAndReturn(run func(context.Context, int32, int32) (*db.UploadBatch, error)) *MockMediaItemService_CreateUploadBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetMediaItemRange provides a mock function with given fields: ctx, groupId
func (_m *MockMediaItemService) GetMediaItemRange(ctx context.Context, groupId int32) ([]services.MediaItemRange, error) {
	ret := _m.Called(ctx, groupId)

	if len(ret) == 0 {
		panic("no return value specified for GetMediaItemRange")
	}

	var r0 []services.MediaItemRange
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]services.MediaItemRange, error)); ok {
		return rf(ctx, groupId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []services.MediaItemRange); ok {
		r0 = rf(ctx, groupId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]services.MediaItemRange)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, groupId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaItemService_GetMediaItemRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMediaItemRange'
type MockMediaItemService_GetMediaItemRange_Call struct {
	*mock.Call
}

// GetMediaItemRange is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId int32
func (_e *MockMediaItemService_Expecter) GetMediaItemRange(ctx interface{}, groupId interface{}) *MockMediaItemService_GetMediaItemRange_Call {
	return &MockMediaItemService_GetMediaItemRange_Call{Call: _e.mock.On("GetMediaItemRange", ctx, groupId)}
}

func (_c *MockMediaItemService_GetMediaItemRange_Call) Run(run func(ctx context.Context, groupId int32)) *MockMediaItemService_GetMediaItemRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockMediaItemService_GetMediaItemRange_Call) Return(_a0 []services.MediaItemRange, _a1 error) *MockMediaItemService_GetMediaItemRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaItemService_GetMediaItemRange_Call) RunAndReturn(run func(context.Context, int32) ([]services.MediaItemRange, error)) *MockMediaItemService_GetMediaItemRange_Call {
	_c.Call.Return(run)
	return _c
}

// GetMediaItemsByTakenAt provides a mock function with given fields: ctx, groupID, userID, from, to
func (_m *MockMediaItemService) GetMediaItemsByTakenAt(ctx context.Context, groupID int32, userID int32, from time.Time, to time.Time) ([]db.GetMediaItemsByTakenAtRow, error) {
	ret := _m.Called(ctx, groupID, userID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetMediaItemsByTakenAt")
	}

	var r0 []db.GetMediaItemsByTakenAtRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32, time.Time, time.Time) ([]db.GetMediaItemsByTakenAtRow, error)); ok {
		return rf(ctx, groupID, userID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32, time.Time, time.Time) []db.GetMediaItemsByTakenAtRow); ok {
		r0 = rf(ctx, groupID, userID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetMediaItemsByTakenAtRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32, time.Time, time.Time) error); ok {
		r1 = rf(ctx, groupID, userID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaItemService_GetMediaItemsByTakenAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMediaItemsByTakenAt'
type MockMediaItemService_GetMediaItemsByTakenAt_Call struct {
	*mock.Call
}

// GetMediaItemsByTakenAt is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID int32
//   - userID int32
//   - from time.Time
//   - to time.Time
func (_e *MockMediaItemService_Expecter) GetMediaItemsByTakenAt(ctx interface{}, groupID interface{}, userID interface{}, from interface{}, to interface{}) *MockMediaItemService_GetMediaItemsByTakenAt_Call {
	return &MockMediaItemService_GetMediaItemsByTakenAt_Call{Call: _e.mock.On("GetMediaItemsByTakenAt", ctx, groupID, userID, from, to)}
}

func (_c *MockMediaItemService_GetMediaItemsByTakenAt_Call) Run(run func(ctx context.Context, groupID int32, userID int32, from time.Time, to time.Time)) *MockMediaItemService_GetMediaItemsByTakenAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32), args[3].(time.Time), args[4].(time.Time))
	})
	return _c
}

func (_c *MockMediaItemService_GetMediaItemsByTakenAt_Call) Return(_a0 []db.GetMediaItemsByTakenAtRow, _a1 error) *MockMediaItemService_GetMediaItemsByTakenAt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaItemService_GetMediaItemsByTakenAt_Call) RunAndReturn(run func(context.Context, int32, int32, time.Time, time.Time) ([]db.GetMediaItemsByTakenAtRow, error)) *MockMediaItemService_GetMediaItemsByTakenAt_Call {
	_c.Call.Return(run)
	return _c
}

// GetMediaItemsByUploadBatch provides a mock function with given fields: ctx, uploadBatchID, userID, page
func (_m *MockMediaItemService) GetMediaItemsByUploadBatch(ctx context.Context, uploadBatchID int32, userID int32, page int) (*services.UploadBatchItemsResult, error) {
	ret := _m.Called(ctx, uploadBatchID, userID, page)

	if len(ret) == 0 {
		panic("no return value specified for GetMediaItemsByUploadBatch")
	}

	var r0 *services.UploadBatchItemsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32, int) (*services.UploadBatchItemsResult, error)); ok {
		return rf(ctx, uploadBatchID, userID, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32, int) *services.UploadBatchItemsResult); ok {
		r0 = rf(ctx, uploadBatchID, userID, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.UploadBatchItemsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32, int) error); ok {
		r1 = rf(ctx, uploadBatchID, userID, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaItemService_GetMediaItemsByUploadBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMediaItemsByUploadBatch'
type MockMediaItemService_GetMediaItemsByUploadBatch_Call struct {
	*mock.Call
}

// GetMediaItemsByUploadBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - uploadBatchID int32
//   - userID int32
//   - page int
func (_e *MockMediaItemService_Expecter) GetMediaItemsByUploadBatch(ctx interface{}, uploadBatchID interface{}, userID interface{}, page interface{}) *MockMediaItemService_GetMediaItemsByUploadBatch_Call {
	return &MockMediaItemService_GetMediaItemsByUploadBatch_Call{Call: _e.mock.On("GetMediaItemsByUploadBatch", ctx, uploadBatchID, userID, page)}
}

func (_c *MockMediaItemService_GetMediaItemsByUploadBatch_Call) Run(run func(ctx context.Context, uploadBatchID int32, userID int32, page int)) *MockMediaItemService_GetMediaItemsByUploadBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32), args[3].(int))
	})
	return _c
}

func (_c *MockMediaItemService_GetMediaItemsByUploadBatch_Call) Return(_a0 *services.UploadBatchItemsResult, _a1 error) *MockMediaItemService_GetMediaItemsByUploadBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaItemService_GetMediaItemsByUploadBatch_Call) RunAndReturn(run func(context.Context, int32, int32, int) (*services.UploadBatchItemsResult, error)) *MockMediaItemService_GetMediaItemsByUploadBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetUploadBatchesWithThumbnails provides a mock function with given fields: ctx, groupID, page
func (_m *MockMediaItemService) GetUploadBatchesWithThumbnails(ctx context.Context, groupID int32, page int) ([]services.UploadBatchWithThumbnails, bool, error) {
	ret := _m.Called(ctx, groupID, page)

	if len(ret) == 0 {
		panic("no return value specified for GetUploadBatchesWithThumbnails")
	}

	var r0 []services.UploadBatchWithThumbnails
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int) ([]services.UploadBatchWithThumbnails, bool, error)); ok {
		return rf(ctx, groupID, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int) []services.UploadBatchWithThumbnails); ok {
		r0 = rf(ctx, groupID, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]services.UploadBatchWithThumbnails)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int) bool); ok {
		r1 = rf(ctx, groupID, page)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int32, int) error); ok {
		r2 = rf(ctx, groupID, page)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockMediaItemService_GetUploadBatchesWithThumbnails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUploadBatchesWithThumbnails'
type MockMediaItemService_GetUploadBatchesWithThumbnails_Call struct {
	*mock.Call
}

// GetUploadBatchesWithThumbnails is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID int32
//   - page int
func (_e *MockMediaItemService_Expecter) GetUploadBatchesWithThumbnails(ctx interface{}, groupID interface{}, page interface{}) *MockMediaItemService_GetUploadBatchesWithThumbnails_Call {
	return &MockMediaItemService_GetUploadBatchesWithThumbnails_Call{Call: _e.mock.On("GetUploadBatchesWithThumbnails", ctx, groupID, page)}
}

func (_c *MockMediaItemService_GetUploadBatchesWithThumbnails_Call) Run(run func(ctx context.Context, groupID int32, page int)) *MockMediaItemService_GetUploadBatchesWithThumbnails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int))
	})
	return _c
}

func (_c *MockMediaItemService_GetUploadBatchesWithThumbnails_Call) Return(_a0 []services.UploadBatchWithThumbnails, _a1 bool, _a2 error) *MockMediaItemService_GetUploadBatchesWithThumbnails_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockMediaItemService_GetUploadBatchesWithThumbnails_Call) RunAndReturn(run func(context.Context, int32, int) ([]services.UploadBatchWithThumbnails, bool, error)) *MockMediaItemService_GetUploadBatchesWithThumbnails_Call {
	_c.Call.Return(run)
	return _c
}

// GetUploadStatuses provides a mock function with given fields: ctx, uploadBatchID
func (_m *MockMediaItemService) GetUploadStatuses(ctx context.Context, uploadBatchID int32) ([]db.GetUploadStatusesRow, error) {
	ret := _m.Called(ctx, uploadBatchID)

	if len(ret) == 0 {
		panic("no return value specified for GetUploadStatuses")
	}

	var r0 []db.GetUploadStatusesRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]db.GetUploadStatusesRow, error)); ok {
		return rf(ctx, uploadBatchID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []db.GetUploadStatusesRow); ok {
		r0 = rf(ctx, uploadBatchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetUploadStatusesRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, uploadBatchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaItemService_GetUploadStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUploadStatuses'
type MockMediaItemService_GetUploadStatuses_Call struct {
	*mock.Call
}

// GetUploadStatuses is a helper method to define mock.On call
//   - ctx context.Context
//   - uploadBatchID int32
func (_e *MockMediaItemService_Expecter) GetUploadStatuses(ctx interface{}, uploadBatchID interface{}) *MockMediaItemService_GetUploadStatuses_Call {
	return &MockMediaItemService_GetUploadStatuses_Call{Call: _e.mock.On("GetUploadStatuses", ctx, uploadBatchID)}
}

func (_c *MockMediaItemService_GetUploadStatuses_Call) Run(run func(ctx context.Context, uploadBatchID int32)) *MockMediaItemService_GetUploadStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockMediaItemService_GetUploadStatuses_Call) Return(_a0 []db.GetUploadStatusesRow, _a1 error) *MockMediaItemService_GetUploadStatuses_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaItemService_GetUploadStatuses_Call) RunAndReturn(run func(context.Context, int32) ([]db.GetUploadStatusesRow, error)) *MockMediaItemService_GetUploadStatuses_Call {
	_c.Call.Return(run)
	return _c
}

// SearchMediaItems provides a mock function with given fields: ctx, groupID, userID, from, to, albumID, identityIDs, liked, tagIDs, page
func (_m *MockMediaItemService) SearchMediaItems(ctx context.Context, groupID int32, userID int32, from *time.Time, to *time.Time, albumID *int32, identityIDs []int32, liked bool, tagIDs []int32, page int) (*services.SearchMediaItemsResult, error) {
	ret := _m.Called(ctx, groupID, userID, from, to, albumID, identityIDs, liked, tagIDs, page)

	if len(ret) == 0 {
		panic("no return value specified for SearchMediaItems")
	}

	var r0 *services.SearchMediaItemsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32, *time.Time, *time.Time, *int32, []int32, bool, []int32, int) (*services.SearchMediaItemsResult, error)); ok {
		return rf(ctx, groupID, userID, from, to, albumID, identityIDs, liked, tagIDs, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32, *time.Time, *time.Time, *int32, []int32, bool, []int32, int) *services.SearchMediaItemsResult); ok {
		r0 = rf(ctx, groupID, userID, from, to, albumID, identityIDs, liked, tagIDs, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.SearchMediaItemsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32, *time.Time, *time.Time, *int32, []int32, bool, []int32, int) error); ok {
		r1 = rf(ctx, groupID, userID, from, to, albumID, identityIDs, liked, tagIDs, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaItemService_SearchMediaItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchMediaItems'
type MockMediaItemService_SearchMediaItems_Call struct {
	*mock.Call
}

// SearchMediaItems is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID int32
//   - userID int32
//   - from *time.Time
//   - to *time.Time
//   - albumID *int32
//   - identityIDs []int32
//   - liked bool
//   - tagIDs []int32
//   - page int
func (_e *MockMediaItemService_Expecter) SearchMediaItems(ctx interface{}, groupID interface{}, userID interface{}, from interface{}, to interface{}, albumID interface{}, identityIDs interface{}, liked interface{}, tagIDs interface{}, page interface{}) *MockMediaItemService_SearchMediaItems_Call {
	return &MockMediaItemService_SearchMediaItems_Call{Call: _e.mock.On("SearchMediaItems", ctx, groupID, userID, from, to, albumID, identityIDs, liked, tagIDs, page)}
}

func (_c *MockMediaItemService_SearchMediaItems_Call) Run(run func(ctx context.Context, groupID int32, userID int32, from *time.Time, to *time.Time, albumID *int32, identityIDs []int32, liked bool, tagIDs []int32, page int)) *MockMediaItemService_SearchMediaItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32), args[3].(*time.Time), args[4].(*time.Time), args[5].(*int32), args[6].([]int32), args[7].(bool), args[8].([]int32), args[9].(int))
	})
	return _c
}

func (_c *MockMediaItemService_SearchMediaItems_Call) Return(_a0 *services.SearchMediaItemsResult, _a1 error) *MockMediaItemService_SearchMediaItems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaItemService_SearchMediaItems_Call) RunAndReturn(run func(context.Context, int32, int32, *time.Time, *time.Time, *int32, []int32, bool, []int32, int) (*services.SearchMediaItemsResult, error)) *MockMediaItemService_SearchMediaItems_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMediaItemUploadStatus provides a mock function with given fields: ctx, mediaItemID, uploadStatus
func (_m *MockMediaItemService) UpdateMediaItemUploadStatus(ctx context.Context, mediaItemID int32, uploadStatus enums.UploadStatus) error {
	ret := _m.Called(ctx, mediaItemID, uploadStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMediaItemUploadStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, enums.UploadStatus) error); ok {
		r0 = rf(ctx, mediaItemID, uploadStatus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMediaItemService_UpdateMediaItemUploadStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMediaItemUploadStatus'
type MockMediaItemService_UpdateMediaItemUploadStatus_Call struct {
	*mock.Call
}

// UpdateMediaItemUploadStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - mediaItemID int32
//   - uploadStatus enums.UploadStatus
func (_e *MockMediaItemService_Expecter) UpdateMediaItemUploadStatus(ctx interface{}, mediaItemID interface{}, uploadStatus interface{}) *MockMediaItemService_UpdateMediaItemUploadStatus_Call {
	return &MockMediaItemService_UpdateMediaItemUploadStatus_Call{Call: _e.mock.On("UpdateMediaItemUploadStatus", ctx, mediaItemID, uploadStatus)}
}

func (_c *MockMediaItemService_UpdateMediaItemUploadStatus_Call) Run(run func(ctx context.Context, mediaItemID int32, uploadStatus enums.UploadStatus)) *MockMediaItemService_UpdateMediaItemUploadStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(enums.UploadStatus))
	})
	return _c
}

func (_c *MockMediaItemService_UpdateMediaItemUploadStatus_Call) Return(_a0 error) *MockMediaItemService_UpdateMediaItemUploadStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaItemService_UpdateMediaItemUploadStatus_Call) RunAndReturn(run func(context.Context, int32, enums.UploadStatus) error) *MockMediaItemService_UpdateMediaItemUploadStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMediaItemService creates a new instance of MockMediaItemService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMediaItemService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMediaItemService {
	mock := &MockMediaItemService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
