// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	services "github.com/ywl0806/yuno_kiroku/internal/services"
)

// MockFaceRecognitionDispatcher is an autogenerated mock type for the FaceRecognitionDispatcher type
type MockFaceRecognitionDispatcher struct {
	mock.Mock
}

type MockFaceRecognitionDispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFaceRecognitionDispatcher) EXPECT() *MockFaceRecognitionDispatcher_Expecter {
	return &MockFaceRecognitionDispatcher_Expecter{mock: &_m.Mock}
}

// Dispatch provides a mock function with given fields: ctx, params
func (_m *MockFaceRecognitionDispatcher) Dispatch(ctx context.Context, params services.FaceRecognitionJobParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Dispatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, services.FaceRecognitionJobParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFaceRecognitionDispatcher_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type MockFaceRecognitionDispatcher_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - ctx context.Context
//   - params services.FaceRecognitionJobParams
func (_e *MockFaceRecognitionDispatcher_Expecter) Dispatch(ctx interface{}, params interface{}) *MockFaceRecognitionDispatcher_Dispatch_Call {
	return &MockFaceRecognitionDispatcher_Dispatch_Call{Call: _e.mock.On("Dispatch", ctx, params)}
}

func (_c *MockFaceRecognitionDispatcher_Dispatch_Call) Run(run func(ctx context.Context, params services.FaceRecognitionJobParams)) *MockFaceRecognitionDispatcher_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(services.FaceRecognitionJobParams))
	})
	return _c
}

func (_c *MockFaceRecognitionDispatcher_Dispatch_Call) Return(_a0 error) *MockFaceRecognitionDispatcher_Dispatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFaceRecognitionDispatcher_Dispatch_Call) RunAndReturn(run func(context.Context, services.FaceRecognitionJobParams) error) *MockFaceRecognitionDispatcher_Dispatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFaceRecognitionDispatcher creates a new instance of MockFaceRecognitionDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFaceRecognitionDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFaceRecognitionDispatcher {
	mock := &MockFaceRecognitionDispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
