// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockImageUploader is an autogenerated mock type for the ImageUploader type
type MockImageUploader struct {
	mock.Mock
}

type MockImageUploader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageUploader) EXPECT() *MockImageUploader_Expecter {
	return &MockImageUploader_Expecter{mock: &_m.Mock}
}

// BuildOriginalKey provides a mock function with given fields: familyId, mediaItemId, fileName
func (_m *MockImageUploader) BuildOriginalKey(familyId int32, mediaItemId int32, fileName string) string {
	ret := _m.Called(familyId, mediaItemId, fileName)

	if len(ret) == 0 {
		panic("no return value specified for BuildOriginalKey")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int32, int32, string) string); ok {
		r0 = rf(familyId, mediaItemId, fileName)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockImageUploader_BuildOriginalKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildOriginalKey'
type MockImageUploader_BuildOriginalKey_Call struct {
	*mock.Call
}

// BuildOriginalKey is a helper method to define mock.On call
//   - familyId int32
//   - mediaItemId int32
//   - fileName string
func (_e *MockImageUploader_Expecter) BuildOriginalKey(familyId interface{}, mediaItemId interface{}, fileName interface{}) *MockImageUploader_BuildOriginalKey_Call {
	return &MockImageUploader_BuildOriginalKey_Call{Call: _e.mock.On("BuildOriginalKey", familyId, mediaItemId, fileName)}
}

func (_c *MockImageUploader_BuildOriginalKey_Call) Run(run func(familyId int32, mediaItemId int32, fileName string)) *MockImageUploader_BuildOriginalKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int32), args[1].(int32), args[2].(string))
	})
	return _c
}

func (_c *MockImageUploader_BuildOriginalKey_Call) Return(_a0 string) *MockImageUploader_BuildOriginalKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImageUploader_BuildOriginalKey_Call) RunAndReturn(run func(int32, int32, string) string) *MockImageUploader_BuildOriginalKey_Call {
	_c.Call.Return(run)
	return _c
}

// GeneratePresignedPutURL provides a mock function with given fields: ctx, key, contentType, expiresIn
func (_m *MockImageUploader) GeneratePresignedPutURL(ctx context.Context, key string, contentType string, expiresIn time.Duration) (string, error) {
	ret := _m.Called(ctx, key, contentType, expiresIn)

	if len(ret) == 0 {
		panic("no return value specified for GeneratePresignedPutURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) (string, error)); ok {
		return rf(ctx, key, contentType, expiresIn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) string); ok {
		r0 = rf(ctx, key, contentType, expiresIn)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Duration) error); ok {
		r1 = rf(ctx, key, contentType, expiresIn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImageUploader_GeneratePresignedPutURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GeneratePresignedPutURL'
type MockImageUploader_GeneratePresignedPutURL_Call struct {
	*mock.Call
}

// GeneratePresignedPutURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - contentType string
//   - expiresIn time.Duration
func (_e *MockImageUploader_Expecter) GeneratePresignedPutURL(ctx interface{}, key interface{}, contentType interface{}, expiresIn interface{}) *MockImageUploader_GeneratePresignedPutURL_Call {
	return &MockImageUploader_GeneratePresignedPutURL_Call{Call: _e.mock.On("GeneratePresignedPutURL", ctx, key, contentType, expiresIn)}
}

func (_c *MockImageUploader_GeneratePresignedPutURL_Call) Run(run func(ctx context.Context, key string, contentType string, expiresIn time.Duration)) *MockImageUploader_GeneratePresignedPutURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockImageUploader_GeneratePresignedPutURL_Call) Return(_a0 string, _a1 error) *MockImageUploader_GeneratePresignedPutURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImageUploader_GeneratePresignedPutURL_Call) RunAndReturn(run func(context.Context, string, string, time.Duration) (string, error)) *MockImageUploader_GeneratePresignedPutURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetFile provides a mock function with given fields: ctx, key
func (_m *MockImageUploader) GetFile(ctx context.Context, key string) ([]byte, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetFile")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImageUploader_GetFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFile'
type MockImageUploader_GetFile_Call struct {
	*mock.Call
}

// GetFile is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockImageUploader_Expecter) GetFile(ctx interface{}, key interface{}) *MockImageUploader_GetFile_Call {
	return &MockImageUploader_GetFile_Call{Call: _e.mock.On("GetFile", ctx, key)}
}

func (_c *MockImageUploader_GetFile_Call) Run(run func(ctx context.Context, key string)) *MockImageUploader_GetFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockImageUploader_GetFile_Call) Return(_a0 []byte, _a1 error) *MockImageUploader_GetFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImageUploader_GetFile_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *MockImageUploader_GetFile_Call {
	_c.Call.Return(run)
	return _c
}

// SaveFile provides a mock function with given fields: ctx, data, folder, fileName
func (_m *MockImageUploader) SaveFile(ctx context.Context, data []byte, folder string, fileName string) (string, error) {
	ret := _m.Called(ctx, data, folder, fileName)

	if len(ret) == 0 {
		panic("no return value specified for SaveFile")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string, string) (string, error)); ok {
		return rf(ctx, data, folder, fileName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string, string) string); ok {
		r0 = rf(ctx, data, folder, fileName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, string, string) error); ok {
		r1 = rf(ctx, data, folder, fileName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImageUploader_SaveFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveFile'
type MockImageUploader_SaveFile_Call struct {
	*mock.Call
}

// SaveFile is a helper method to define mock.On call
//   - ctx context.Context
//   - data []byte
//   - folder string
//   - fileName string
func (_e *MockImageUploader_Expecter) SaveFile(ctx interface{}, data interface{}, folder interface{}, fileName interface{}) *MockImageUploader_SaveFile_Call {
	return &MockImageUploader_SaveFile_Call{Call: _e.mock.On("SaveFile", ctx, data, folder, fileName)}
}

func (_c *MockImageUploader_SaveFile_Call) Run(run func(ctx context.Context, data []byte, folder string, fileName string)) *MockImageUploader_SaveFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockImageUploader_SaveFile_Call) Return(_a0 string, _a1 error) *MockImageUploader_SaveFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImageUploader_SaveFile_Call) RunAndReturn(run func(context.Context, []byte, string, string) (string, error)) *MockImageUploader_SaveFile_Call {
	_c.Call.Return(run)
	return _c
}

// UploadOriginal provides a mock function with given fields: ctx, data, familyId, mediaItemId, ext
func (_m *MockImageUploader) UploadOriginal(ctx context.Context, data []byte, familyId int32, mediaItemId int32, ext string) (string, error) {
	ret := _m.Called(ctx, data, familyId, mediaItemId, ext)

	if len(ret) == 0 {
		panic("no return value specified for UploadOriginal")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, int32, int32, string) (string, error)); ok {
		return rf(ctx, data, familyId, mediaItemId, ext)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, int32, int32, string) string); ok {
		r0 = rf(ctx, data, familyId, mediaItemId, ext)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, int32, int32, string) error); ok {
		r1 = rf(ctx, data, familyId, mediaItemId, ext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImageUploader_UploadOriginal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadOriginal'
type MockImageUploader_UploadOriginal_Call struct {
	*mock.Call
}

// UploadOriginal is a helper method to define mock.On call
//   - ctx context.Context
//   - data []byte
//   - familyId int32
//   - mediaItemId int32
//   - ext string
func (_e *MockImageUploader_Expecter) UploadOriginal(ctx interface{}, data interface{}, familyId interface{}, mediaItemId interface{}, ext interface{}) *MockImageUploader_UploadOriginal_Call {
	return &MockImageUploader_UploadOriginal_Call{Call: _e.mock.On("UploadOriginal", ctx, data, familyId, mediaItemId, ext)}
}

func (_c *MockImageUploader_UploadOriginal_Call) Run(run func(ctx context.Context, data []byte, familyId int32, mediaItemId int32, ext string)) *MockImageUploader_UploadOriginal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(int32), args[3].(int32), args[4].(string))
	})
	return _c
}

func (_c *MockImageUploader_UploadOriginal_Call) Return(_a0 string, _a1 error) *MockImageUploader_UploadOriginal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImageUploader_UploadOriginal_Call) RunAndReturn(run func(context.Context, []byte, int32, int32, string) (string, error)) *MockImageUploader_UploadOriginal_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockImageUploader creates a new instance of MockImageUploader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageUploader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageUploader {
	mock := &MockImageUploader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
