// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "github.com/ywl0806/yuno_kiroku/internal/db"

	services "github.com/ywl0806/yuno_kiroku/internal/services"
)

// MockAlbumService is an autogenerated mock type for the AlbumService type
type MockAlbumService struct {
	mock.Mock
}

type MockAlbumService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlbumService) EXPECT() *MockAlbumService_Expecter {
	return &MockAlbumService_Expecter{mock: &_m.Mock}
}

// CreateAlbum provides a mock function with given fields: ctx, familyID, name, perms
func (_m *MockAlbumService) CreateAlbum(ctx context.Context, familyID int32, name string, perms []services.GroupPermission) (db.Album, error) {
	ret := _m.Called(ctx, familyID, name, perms)

	if len(ret) == 0 {
		panic("no return value specified for CreateAlbum")
	}

	var r0 db.Album
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string, []services.GroupPermission) (db.Album, error)); ok {
		return rf(ctx, familyID, name, perms)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, string, []services.GroupPermission) db.Album); ok {
		r0 = rf(ctx, familyID, name, perms)
	} else {
		r0 = ret.Get(0).(db.Album)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, string, []services.GroupPermission) error); ok {
		r1 = rf(ctx, familyID, name, perms)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlbumService_CreateAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAlbum'
type MockAlbumService_CreateAlbum_Call struct {
	*mock.Call
}

// CreateAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID int32
//   - name string
//   - perms []services.GroupPermission
func (_e *MockAlbumService_Expecter) CreateAlbum(ctx interface{}, familyID interface{}, name interface{}, perms interface{}) *MockAlbumService_CreateAlbum_Call {
	return &MockAlbumService_CreateAlbum_Call{Call: _e.mock.On("CreateAlbum", ctx, familyID, name, perms)}
}

func (_c *MockAlbumService_CreateAlbum_Call) Run(run func(ctx context.Context, familyID int32, name string, perms []services.GroupPermission)) *MockAlbumService_CreateAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(string), args[3].([]services.GroupPermission))
	})
	return _c
}

func (_c *MockAlbumService_CreateAlbum_Call) Return(_a0 db.Album, _a1 error) *MockAlbumService_CreateAlbum_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlbumService_CreateAlbum_Call) RunAndReturn(run func(context.Context, int32, string, []services.GroupPermission) (db.Album, error)) *MockAlbumService_CreateAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAlbum provides a mock function with given fields: ctx, albumID, familyID
func (_m *MockAlbumService) DeleteAlbum(ctx context.Context, albumID int32, familyID int32) error {
	ret := _m.Called(ctx, albumID, familyID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAlbum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) error); ok {
		r0 = rf(ctx, albumID, familyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAlbumService_DeleteAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAlbum'
type MockAlbumService_DeleteAlbum_Call struct {
	*mock.Call
}

// DeleteAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - albumID int32
//   - familyID int32
func (_e *MockAlbumService_Expecter) DeleteAlbum(ctx interface{}, albumID interface{}, familyID interface{}) *MockAlbumService_DeleteAlbum_Call {
	return &MockAlbumService_DeleteAlbum_Call{Call: _e.mock.On("DeleteAlbum", ctx, albumID, familyID)}
}

func (_c *MockAlbumService_DeleteAlbum_Call) Run(run func(ctx context.Context, albumID int32, familyID int32)) *MockAlbumService_DeleteAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *MockAlbumService_DeleteAlbum_Call) Return(_a0 error) *MockAlbumService_DeleteAlbum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlbumService_DeleteAlbum_Call) RunAndReturn(run func(context.Context, int32, int32) error) *MockAlbumService_DeleteAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlbumWithPermissions provides a mock function with given fields: ctx, albumID, familyID
func (_m *MockAlbumService) GetAlbumWithPermissions(ctx context.Context, albumID int32, familyID int32) (db.Album, []db.AlbumGroupsPermission, error) {
	ret := _m.Called(ctx, albumID, familyID)

	if len(ret) == 0 {
		panic("no return value specified for GetAlbumWithPermissions")
	}

	var r0 db.Album
	var r1 []db.AlbumGroupsPermission
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) (db.Album, []db.AlbumGroupsPermission, error)); ok {
		return rf(ctx, albumID, familyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) db.Album); ok {
		r0 = rf(ctx, albumID, familyID)
	} else {
		r0 = ret.Get(0).(db.Album)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32) []db.AlbumGroupsPermission); ok {
		r1 = rf(ctx, albumID, familyID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]db.AlbumGroupsPermission)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int32, int32) error); ok {
		r2 = rf(ctx, albumID, familyID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAlbumService_GetAlbumWithPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlbumWithPermissions'
type MockAlbumService_GetAlbumWithPermissions_Call struct {
	*mock.Call
}

// GetAlbumWithPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - albumID int32
//   - familyID int32
func (_e *MockAlbumService_Expecter) GetAlbumWithPermissions(ctx interface{}, albumID interface{}, familyID interface{}) *MockAlbumService_GetAlbumWithPermissions_Call {
	return &MockAlbumService_GetAlbumWithPermissions_Call{Call: _e.mock.On("GetAlbumWithPermissions", ctx, albumID, familyID)}
}

func (_c *MockAlbumService_GetAlbumWithPermissions_Call) Run(run func(ctx context.Context, albumID int32, familyID int32)) *MockAlbumService_GetAlbumWithPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *MockAlbumService_GetAlbumWithPermissions_Call) Return(_a0 db.Album, _a1 []db.AlbumGroupsPermission, _a2 error) *MockAlbumService_GetAlbumWithPermissions_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAlbumService_GetAlbumWithPermissions_Call) RunAndReturn(run func(context.Context, int32, int32) (db.Album, []db.AlbumGroupsPermission, error)) *MockAlbumService_GetAlbumWithPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlbumsForWrite provides a mock function with given fields: ctx, familyId, groupId
func (_m *MockAlbumService) GetAlbumsForWrite(ctx context.Context, familyId int32, groupId int32) ([]db.Album, error) {
	ret := _m.Called(ctx, familyId, groupId)

	if len(ret) == 0 {
		panic("no return value specified for GetAlbumsForWrite")
	}

	var r0 []db.Album
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) ([]db.Album, error)); ok {
		return rf(ctx, familyId, groupId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) []db.Album); ok {
		r0 = rf(ctx, familyId, groupId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Album)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32) error); ok {
		r1 = rf(ctx, familyId, groupId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlbumService_GetAlbumsForWrite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlbumsForWrite'
type MockAlbumService_GetAlbumsForWrite_Call struct {
	*mock.Call
}

// GetAlbumsForWrite is a helper method to define mock.On call
//   - ctx context.Context
//   - familyId int32
//   - groupId int32
func (_e *MockAlbumService_Expecter) GetAlbumsForWrite(ctx interface{}, familyId interface{}, groupId interface{}) *MockAlbumService_GetAlbumsForWrite_Call {
	return &MockAlbumService_GetAlbumsForWrite_Call{Call: _e.mock.On("GetAlbumsForWrite", ctx, familyId, groupId)}
}

func (_c *MockAlbumService_GetAlbumsForWrite_Call) Run(run func(ctx context.Context, familyId int32, groupId int32)) *MockAlbumService_GetAlbumsForWrite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *MockAlbumService_GetAlbumsForWrite_Call) Return(_a0 []db.Album, _a1 error) *MockAlbumService_GetAlbumsForWrite_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlbumService_GetAlbumsForWrite_Call) RunAndReturn(run func(context.Context, int32, int32) ([]db.Album, error)) *MockAlbumService_GetAlbumsForWrite_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlbumsOptions provides a mock function with given fields: ctx, familyID, groupID
func (_m *MockAlbumService) GetAlbumsOptions(ctx context.Context, familyID int32, groupID int32) ([]db.GetAlbumsOptionsRow, error) {
	ret := _m.Called(ctx, familyID, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetAlbumsOptions")
	}

	var r0 []db.GetAlbumsOptionsRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) ([]db.GetAlbumsOptionsRow, error)); ok {
		return rf(ctx, familyID, groupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) []db.GetAlbumsOptionsRow); ok {
		r0 = rf(ctx, familyID, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetAlbumsOptionsRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32) error); ok {
		r1 = rf(ctx, familyID, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlbumService_GetAlbumsOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlbumsOptions'
type MockAlbumService_GetAlbumsOptions_Call struct {
	*mock.Call
}

// GetAlbumsOptions is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID int32
//   - groupID int32
func (_e *MockAlbumService_Expecter) GetAlbumsOptions(ctx interface{}, familyID interface{}, groupID interface{}) *MockAlbumService_GetAlbumsOptions_Call {
	return &MockAlbumService_GetAlbumsOptions_Call{Call: _e.mock.On("GetAlbumsOptions", ctx, familyID, groupID)}
}

func (_c *MockAlbumService_GetAlbumsOptions_Call) Run(run func(ctx context.Context, familyID int32, groupID int32)) *MockAlbumService_GetAlbumsOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *MockAlbumService_GetAlbumsOptions_Call) Return(_a0 []db.GetAlbumsOptionsRow, _a1 error) *MockAlbumService_GetAlbumsOptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlbumService_GetAlbumsOptions_Call) RunAndReturn(run func(context.Context, int32, int32) ([]db.GetAlbumsOptionsRow, error)) *MockAlbumService_GetAlbumsOptions_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllAlbums provides a mock function with given fields: ctx, familyID
func (_m *MockAlbumService) GetAllAlbums(ctx context.Context, familyID int32) ([]db.Album, error) {
	ret := _m.Called(ctx, familyID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAlbums")
	}

	var r0 []db.Album
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]db.Album, error)); ok {
		return rf(ctx, familyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []db.Album); ok {
		r0 = rf(ctx, familyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Album)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, familyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlbumService_GetAllAlbums_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllAlbums'
type MockAlbumService_GetAllAlbums_Call struct {
	*mock.Call
}

// GetAllAlbums is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID int32
func (_e *MockAlbumService_Expecter) GetAllAlbums(ctx interface{}, familyID interface{}) *MockAlbumService_GetAllAlbums_Call {
	return &MockAlbumService_GetAllAlbums_Call{Call: _e.mock.On("GetAllAlbums", ctx, familyID)}
}

func (_c *MockAlbumService_GetAllAlbums_Call) Run(run func(ctx context.Context, familyID int32)) *MockAlbumService_GetAllAlbums_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockAlbumService_GetAllAlbums_Call) Return(_a0 []db.Album, _a1 error) *MockAlbumService_GetAllAlbums_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlbumService_GetAllAlbums_Call) RunAndReturn(run func(context.Context, int32) ([]db.Album, error)) *MockAlbumService_GetAllAlbums_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAlbum provides a mock function with given fields: ctx, albumID, familyID, name, perms
func (_m *MockAlbumService) UpdateAlbum(ctx context.Context, albumID int32, familyID int32, name string, perms []services.GroupPermission) (db.Album, error) {
	ret := _m.Called(ctx, albumID, familyID, name, perms)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAlbum")
	}

	var r0 db.Album
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32, string, []services.GroupPermission) (db.Album, error)); ok {
		return rf(ctx, albumID, familyID, name, perms)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32, string, []services.GroupPermission) db.Album); ok {
		r0 = rf(ctx, albumID, familyID, name, perms)
	} else {
		r0 = ret.Get(0).(db.Album)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32, string, []services.GroupPermission) error); ok {
		r1 = rf(ctx, albumID, familyID, name, perms)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlbumService_UpdateAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAlbum'
type MockAlbumService_UpdateAlbum_Call struct {
	*mock.Call
}

// UpdateAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - albumID int32
//   - familyID int32
//   - name string
//   - perms []services.GroupPermission
func (_e *MockAlbumService_Expecter) UpdateAlbum(ctx interface{}, albumID interface{}, familyID interface{}, name interface{}, perms interface{}) *MockAlbumService_UpdateAlbum_Call {
	return &MockAlbumService_UpdateAlbum_Call{Call: _e.mock.On("UpdateAlbum", ctx, albumID, familyID, name, perms)}
}

func (_c *MockAlbumService_UpdateAlbum_Call) Run(run func(ctx context.Context, albumID int32, familyID int32, name string, perms []services.GroupPermission)) *MockAlbumService_UpdateAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32), args[3].(string), args[4].([]services.GroupPermission))
	})
	return _c
}

func (_c *MockAlbumService_UpdateAlbum_Call) Return(_a0 db.Album, _a1 error) *MockAlbumService_UpdateAlbum_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlbumService_UpdateAlbum_Call) RunAndReturn(run func(context.Context, int32, int32, string, []services.GroupPermission) (db.Album, error)) *MockAlbumService_UpdateAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAlbumService creates a new instance of MockAlbumService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlbumService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlbumService {
	mock := &MockAlbumService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
