// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "github.com/ywl0806/yuno_kiroku/internal/db"
)

// MockIdentityService is an autogenerated mock type for the IdentityService type
type MockIdentityService struct {
	mock.Mock
}

type MockIdentityService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdentityService) EXPECT() *MockIdentityService_Expecter {
	return &MockIdentityService_Expecter{mock: &_m.Mock}
}

// CreateIdentity provides a mock function with given fields: ctx, familyId
func (_m *MockIdentityService) CreateIdentity(ctx context.Context, familyId int32) (db.Identity, error) {
	ret := _m.Called(ctx, familyId)

	if len(ret) == 0 {
		panic("no return value specified for CreateIdentity")
	}

	var r0 db.Identity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (db.Identity, error)); ok {
		return rf(ctx, familyId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) db.Identity); ok {
		r0 = rf(ctx, familyId)
	} else {
		r0 = ret.Get(0).(db.Identity)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, familyId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIdentityService_CreateIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIdentity'
type MockIdentityService_CreateIdentity_Call struct {
	*mock.Call
}

// CreateIdentity is a helper method to define mock.On call
//   - ctx context.Context
//   - familyId int32
func (_e *MockIdentityService_Expecter) CreateIdentity(ctx interface{}, familyId interface{}) *MockIdentityService_CreateIdentity_Call {
	return &MockIdentityService_CreateIdentity_Call{Call: _e.mock.On("CreateIdentity", ctx, familyId)}
}

func (_c *MockIdentityService_CreateIdentity_Call) Run(run func(ctx context.Context, familyId int32)) *MockIdentityService_CreateIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockIdentityService_CreateIdentity_Call) Return(_a0 db.Identity, _a1 error) *MockIdentityService_CreateIdentity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIdentityService_CreateIdentity_Call) RunAndReturn(run func(context.Context, int32) (db.Identity, error)) *MockIdentityService_CreateIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// FindIdentitiesByFamilyId provides a mock function with given fields: ctx, familyId
func (_m *MockIdentityService) FindIdentitiesByFamilyId(ctx context.Context, familyId int32) ([]db.Identity, error) {
	ret := _m.Called(ctx, familyId)

	if len(ret) == 0 {
		panic("no return value specified for FindIdentitiesByFamilyId")
	}

	var r0 []db.Identity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]db.Identity, error)); ok {
		return rf(ctx, familyId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []db.Identity); ok {
		r0 = rf(ctx, familyId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Identity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, familyId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIdentityService_FindIdentitiesByFamilyId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindIdentitiesByFamilyId'
type MockIdentityService_FindIdentitiesByFamilyId_Call struct {
	*mock.Call
}

// FindIdentitiesByFamilyId is a helper method to define mock.On call
//   - ctx context.Context
//   - familyId int32
func (_e *MockIdentityService_Expecter) FindIdentitiesByFamilyId(ctx interface{}, familyId interface{}) *MockIdentityService_FindIdentitiesByFamilyId_Call {
	return &MockIdentityService_FindIdentitiesByFamilyId_Call{Call: _e.mock.On("FindIdentitiesByFamilyId", ctx, familyId)}
}

func (_c *MockIdentityService_FindIdentitiesByFamilyId_Call) Run(run func(ctx context.Context, familyId int32)) *MockIdentityService_FindIdentitiesByFamilyId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockIdentityService_FindIdentitiesByFamilyId_Call) Return(_a0 []db.Identity, _a1 error) *MockIdentityService_FindIdentitiesByFamilyId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIdentityService_FindIdentitiesByFamilyId_Call) RunAndReturn(run func(context.Context, int32) ([]db.Identity, error)) *MockIdentityService_FindIdentitiesByFamilyId_Call {
	_c.Call.Return(run)
	return _c
}

// FindIdentityByIdAndFamilyId provides a mock function with given fields: ctx, id, familyId
func (_m *MockIdentityService) FindIdentityByIdAndFamilyId(ctx context.Context, id int32, familyId int32) (db.Identity, error) {
	ret := _m.Called(ctx, id, familyId)

	if len(ret) == 0 {
		panic("no return value specified for FindIdentityByIdAndFamilyId")
	}

	var r0 db.Identity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) (db.Identity, error)); ok {
		return rf(ctx, id, familyId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) db.Identity); ok {
		r0 = rf(ctx, id, familyId)
	} else {
		r0 = ret.Get(0).(db.Identity)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32) error); ok {
		r1 = rf(ctx, id, familyId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIdentityService_FindIdentityByIdAndFamilyId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindIdentityByIdAndFamilyId'
type MockIdentityService_FindIdentityByIdAndFamilyId_Call struct {
	*mock.Call
}

// FindIdentityByIdAndFamilyId is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - familyId int32
func (_e *MockIdentityService_Expecter) FindIdentityByIdAndFamilyId(ctx interface{}, id interface{}, familyId interface{}) *MockIdentityService_FindIdentityByIdAndFamilyId_Call {
	return &MockIdentityService_FindIdentityByIdAndFamilyId_Call{Call: _e.mock.On("FindIdentityByIdAndFamilyId", ctx, id, familyId)}
}

func (_c *MockIdentityService_FindIdentityByIdAndFamilyId_Call) Run(run func(ctx context.Context, id int32, familyId int32)) *MockIdentityService_FindIdentityByIdAndFamilyId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *MockIdentityService_FindIdentityByIdAndFamilyId_Call) Return(_a0 db.Identity, _a1 error) *MockIdentityService_FindIdentityByIdAndFamilyId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIdentityService_FindIdentityByIdAndFamilyId_Call) RunAndReturn(run func(context.Context, int32, int32) (db.Identity, error)) *MockIdentityService_FindIdentityByIdAndFamilyId_Call {
	_c.Call.Return(run)
	return _c
}

// FindNewestIdentityFaceImgByFamilyId provides a mock function with given fields: ctx, familyId, onlyNotLinked, withKidIds, withUserIds
func (_m *MockIdentityService) FindNewestIdentityFaceImgByFamilyId(ctx context.Context, familyId int32, onlyNotLinked bool, withKidIds []int32, withUserIds []int32) ([]db.FindNewestIdentityFaceImgByFamilyIdRow, error) {
	ret := _m.Called(ctx, familyId, onlyNotLinked, withKidIds, withUserIds)

	if len(ret) == 0 {
		panic("no return value specified for FindNewestIdentityFaceImgByFamilyId")
	}

	var r0 []db.FindNewestIdentityFaceImgByFamilyIdRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, bool, []int32, []int32) ([]db.FindNewestIdentityFaceImgByFamilyIdRow, error)); ok {
		return rf(ctx, familyId, onlyNotLinked, withKidIds, withUserIds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, bool, []int32, []int32) []db.FindNewestIdentityFaceImgByFamilyIdRow); ok {
		r0 = rf(ctx, familyId, onlyNotLinked, withKidIds, withUserIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.FindNewestIdentityFaceImgByFamilyIdRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, bool, []int32, []int32) error); ok {
		r1 = rf(ctx, familyId, onlyNotLinked, withKidIds, withUserIds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIdentityService_FindNewestIdentityFaceImgByFamilyId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNewestIdentityFaceImgByFamilyId'
type MockIdentityService_FindNewestIdentityFaceImgByFamilyId_Call struct {
	*mock.Call
}

// FindNewestIdentityFaceImgByFamilyId is a helper method to define mock.On call
//   - ctx context.Context
//   - familyId int32
//   - onlyNotLinked bool
//   - withKidIds []int32
//   - withUserIds []int32
func (_e *MockIdentityService_Expecter) FindNewestIdentityFaceImgByFamilyId(ctx interface{}, familyId interface{}, onlyNotLinked interface{}, withKidIds interface{}, withUserIds interface{}) *MockIdentityService_FindNewestIdentityFaceImgByFamilyId_Call {
	return &MockIdentityService_FindNewestIdentityFaceImgByFamilyId_Call{Call: _e.mock.On("FindNewestIdentityFaceImgByFamilyId", ctx, familyId, onlyNotLinked, withKidIds, withUserIds)}
}

func (_c *MockIdentityService_FindNewestIdentityFaceImgByFamilyId_Call) Run(run func(ctx context.Context, familyId int32, onlyNotLinked bool, withKidIds []int32, withUserIds []int32)) *MockIdentityService_FindNewestIdentityFaceImgByFamilyId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(bool), args[3].([]int32), args[4].([]int32))
	})
	return _c
}

func (_c *MockIdentityService_FindNewestIdentityFaceImgByFamilyId_Call) Return(_a0 []db.FindNewestIdentityFaceImgByFamilyIdRow, _a1 error) *MockIdentityService_FindNewestIdentityFaceImgByFamilyId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIdentityService_FindNewestIdentityFaceImgByFamilyId_Call) RunAndReturn(run func(context.Context, int32, bool, []int32, []int32) ([]db.FindNewestIdentityFaceImgByFamilyIdRow, error)) *MockIdentityService_FindNewestIdentityFaceImgByFamilyId_Call {
	_c.Call.Return(run)
	return _c
}

// GetIdentityOptions provides a mock function with given fields: ctx, familyID
func (_m *MockIdentityService) GetIdentityOptions(ctx context.Context, familyID int32) ([]db.GetIdentityOptionsRow, error) {
	ret := _m.Called(ctx, familyID)

	if len(ret) == 0 {
		panic("no return value specified for GetIdentityOptions")
	}

	var r0 []db.GetIdentityOptionsRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]db.GetIdentityOptionsRow, error)); ok {
		return rf(ctx, familyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []db.GetIdentityOptionsRow); ok {
		r0 = rf(ctx, familyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetIdentityOptionsRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, familyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIdentityService_GetIdentityOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIdentityOptions'
type MockIdentityService_GetIdentityOptions_Call struct {
	*mock.Call
}

// GetIdentityOptions is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID int32
func (_e *MockIdentityService_Expecter) GetIdentityOptions(ctx interface{}, familyID interface{}) *MockIdentityService_GetIdentityOptions_Call {
	return &MockIdentityService_GetIdentityOptions_Call{Call: _e.mock.On("GetIdentityOptions", ctx, familyID)}
}

func (_c *MockIdentityService_GetIdentityOptions_Call) Run(run func(ctx context.Context, familyID int32)) *MockIdentityService_GetIdentityOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockIdentityService_GetIdentityOptions_Call) Return(_a0 []db.GetIdentityOptionsRow, _a1 error) *MockIdentityService_GetIdentityOptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIdentityService_GetIdentityOptions_Call) RunAndReturn(run func(context.Context, int32) ([]db.GetIdentityOptionsRow, error)) *MockIdentityService_GetIdentityOptions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIdentityService creates a new instance of MockIdentityService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdentityService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdentityService {
	mock := &MockIdentityService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
