// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "github.com/ywl0806/yuno_kiroku/internal/db"
)

// MockUserStore is an autogenerated mock type for the UserStore type
type MockUserStore struct {
	mock.Mock
}

type MockUserStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserStore) EXPECT() *MockUserStore_Expecter {
	return &MockUserStore_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, params
func (_m *MockUserStore) CreateUser(ctx context.Context, params db.CreateUserParams) (db.User, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) (db.User, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) db.User); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateUserParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserStore_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserStore_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - params db.CreateUserParams
func (_e *MockUserStore_Expecter) CreateUser(ctx interface{}, params interface{}) *MockUserStore_CreateUser_Call {
	return &MockUserStore_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, params)}
}

func (_c *MockUserStore_CreateUser_Call) Run(run func(ctx context.Context, params db.CreateUserParams)) *MockUserStore_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateUserParams))
	})
	return _c
}

func (_c *MockUserStore_CreateUser_Call) Return(_a0 db.User, _a1 error) *MockUserStore_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserStore_CreateUser_Call) RunAndReturn(run func(context.Context, db.CreateUserParams) (db.User, error)) *MockUserStore_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserOAuth provides a mock function with given fields: ctx, params
func (_m *MockUserStore) CreateUserOAuth(ctx context.Context, params db.CreateUserOAuthParams) (db.User, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserOAuth")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateUserOAuthParams) (db.User, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateUserOAuthParams) db.User); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateUserOAuthParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserStore_CreateUserOAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserOAuth'
type MockUserStore_CreateUserOAuth_Call struct {
	*mock.Call
}

// CreateUserOAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - params db.CreateUserOAuthParams
func (_e *MockUserStore_Expecter) CreateUserOAuth(ctx interface{}, params interface{}) *MockUserStore_CreateUserOAuth_Call {
	return &MockUserStore_CreateUserOAuth_Call{Call: _e.mock.On("CreateUserOAuth", ctx, params)}
}

func (_c *MockUserStore_CreateUserOAuth_Call) Run(run func(ctx context.Context, params db.CreateUserOAuthParams)) *MockUserStore_CreateUserOAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateUserOAuthParams))
	})
	return _c
}

func (_c *MockUserStore_CreateUserOAuth_Call) Return(_a0 db.User, _a1 error) *MockUserStore_CreateUserOAuth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserStore_CreateUserOAuth_Call) RunAndReturn(run func(context.Context, db.CreateUserOAuthParams) (db.User, error)) *MockUserStore_CreateUserOAuth_Call {
	_c.Call.Return(run)
	return _c
}

// FindMembersByFamilyID provides a mock function with given fields: ctx, familyID
func (_m *MockUserStore) FindMembersByFamilyID(ctx context.Context, familyID int32) ([]db.User, error) {
	ret := _m.Called(ctx, familyID)

	if len(ret) == 0 {
		panic("no return value specified for FindMembersByFamilyID")
	}

	var r0 []db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]db.User, error)); ok {
		return rf(ctx, familyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []db.User); ok {
		r0 = rf(ctx, familyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, familyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserStore_FindMembersByFamilyID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMembersByFamilyID'
type MockUserStore_FindMembersByFamilyID_Call struct {
	*mock.Call
}

// FindMembersByFamilyID is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID int32
func (_e *MockUserStore_Expecter) FindMembersByFamilyID(ctx interface{}, familyID interface{}) *MockUserStore_FindMembersByFamilyID_Call {
	return &MockUserStore_FindMembersByFamilyID_Call{Call: _e.mock.On("FindMembersByFamilyID", ctx, familyID)}
}

func (_c *MockUserStore_FindMembersByFamilyID_Call) Run(run func(ctx context.Context, familyID int32)) *MockUserStore_FindMembersByFamilyID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockUserStore_FindMembersByFamilyID_Call) Return(_a0 []db.User, _a1 error) *MockUserStore_FindMembersByFamilyID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserStore_FindMembersByFamilyID_Call) RunAndReturn(run func(context.Context, int32) ([]db.User, error)) *MockUserStore_FindMembersByFamilyID_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByID provides a mock function with given fields: ctx, id, familyID
func (_m *MockUserStore) FindUserByID(ctx context.Context, id int32, familyID int32) (db.User, error) {
	ret := _m.Called(ctx, id, familyID)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByID")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) (db.User, error)); ok {
		return rf(ctx, id, familyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) db.User); ok {
		r0 = rf(ctx, id, familyID)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32) error); ok {
		r1 = rf(ctx, id, familyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserStore_FindUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByID'
type MockUserStore_FindUserByID_Call struct {
	*mock.Call
}

// FindUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - familyID int32
func (_e *MockUserStore_Expecter) FindUserByID(ctx interface{}, id interface{}, familyID interface{}) *MockUserStore_FindUserByID_Call {
	return &MockUserStore_FindUserByID_Call{Call: _e.mock.On("FindUserByID", ctx, id, familyID)}
}

func (_c *MockUserStore_FindUserByID_Call) Run(run func(ctx context.Context, id int32, familyID int32)) *MockUserStore_FindUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *MockUserStore_FindUserByID_Call) Return(_a0 db.User, _a1 error) *MockUserStore_FindUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserStore_FindUserByID_Call) RunAndReturn(run func(context.Context, int32, int32) (db.User, error)) *MockUserStore_FindUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByProvider provides a mock function with given fields: ctx, provider, providerUserID
func (_m *MockUserStore) FindUserByProvider(ctx context.Context, provider string, providerUserID string) (db.User, error) {
	ret := _m.Called(ctx, provider, providerUserID)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByProvider")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (db.User, error)); ok {
		return rf(ctx, provider, providerUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) db.User); ok {
		r0 = rf(ctx, provider, providerUserID)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, provider, providerUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserStore_FindUserByProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByProvider'
type MockUserStore_FindUserByProvider_Call struct {
	*mock.Call
}

// FindUserByProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - providerUserID string
func (_e *MockUserStore_Expecter) FindUserByProvider(ctx interface{}, provider interface{}, providerUserID interface{}) *MockUserStore_FindUserByProvider_Call {
	return &MockUserStore_FindUserByProvider_Call{Call: _e.mock.On("FindUserByProvider", ctx, provider, providerUserID)}
}

func (_c *MockUserStore_FindUserByProvider_Call) Run(run func(ctx context.Context, provider string, providerUserID string)) *MockUserStore_FindUserByProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserStore_FindUserByProvider_Call) Return(_a0 db.User, _a1 error) *MockUserStore_FindUserByProvider_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserStore_FindUserByProvider_Call) RunAndReturn(run func(context.Context, string, string) (db.User, error)) *MockUserStore_FindUserByProvider_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByUsername provides a mock function with given fields: ctx, username
func (_m *MockUserStore) FindUserByUsername(ctx context.Context, username string) (db.User, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByUsername")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.User); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserStore_FindUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByUsername'
type MockUserStore_FindUserByUsername_Call struct {
	*mock.Call
}

// FindUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserStore_Expecter) FindUserByUsername(ctx interface{}, username interface{}) *MockUserStore_FindUserByUsername_Call {
	return &MockUserStore_FindUserByUsername_Call{Call: _e.mock.On("FindUserByUsername", ctx, username)}
}

func (_c *MockUserStore_FindUserByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserStore_FindUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserStore_FindUserByUsername_Call) Return(_a0 db.User, _a1 error) *MockUserStore_FindUserByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserStore_FindUserByUsername_Call) RunAndReturn(run func(context.Context, string) (db.User, error)) *MockUserStore_FindUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMember provides a mock function with given fields: ctx, arg
func (_m *MockUserStore) UpdateMember(ctx context.Context, arg db.UpdateMemberParams) (db.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMember")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateMemberParams) (db.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateMemberParams) db.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateMemberParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserStore_UpdateMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMember'
type MockUserStore_UpdateMember_Call struct {
	*mock.Call
}

// UpdateMember is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateMemberParams
func (_e *MockUserStore_Expecter) UpdateMember(ctx interface{}, arg interface{}) *MockUserStore_UpdateMember_Call {
	return &MockUserStore_UpdateMember_Call{Call: _e.mock.On("UpdateMember", ctx, arg)}
}

func (_c *MockUserStore_UpdateMember_Call) Run(run func(ctx context.Context, arg db.UpdateMemberParams)) *MockUserStore_UpdateMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateMemberParams))
	})
	return _c
}

func (_c *MockUserStore_UpdateMember_Call) Return(_a0 db.User, _a1 error) *MockUserStore_UpdateMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserStore_UpdateMember_Call) RunAndReturn(run func(context.Context, db.UpdateMemberParams) (db.User, error)) *MockUserStore_UpdateMember_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserName provides a mock function with given fields: ctx, arg
func (_m *MockUserStore) UpdateUserName(ctx context.Context, arg db.UpdateUserNameParams) (db.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserName")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateUserNameParams) (db.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateUserNameParams) db.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateUserNameParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserStore_UpdateUserName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserName'
type MockUserStore_UpdateUserName_Call struct {
	*mock.Call
}

// UpdateUserName is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateUserNameParams
func (_e *MockUserStore_Expecter) UpdateUserName(ctx interface{}, arg interface{}) *MockUserStore_UpdateUserName_Call {
	return &MockUserStore_UpdateUserName_Call{Call: _e.mock.On("UpdateUserName", ctx, arg)}
}

func (_c *MockUserStore_UpdateUserName_Call) Run(run func(ctx context.Context, arg db.UpdateUserNameParams)) *MockUserStore_UpdateUserName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateUserNameParams))
	})
	return _c
}

func (_c *MockUserStore_UpdateUserName_Call) Return(_a0 db.User, _a1 error) *MockUserStore_UpdateUserName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserStore_UpdateUserName_Call) RunAndReturn(run func(context.Context, db.UpdateUserNameParams) (db.User, error)) *MockUserStore_UpdateUserName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserStore creates a new instance of MockUserStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserStore {
	mock := &MockUserStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
