// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	store "github.com/ywl0806/yuno_kiroku/internal/store"
)

// MockTxStore is an autogenerated mock type for the TxStore type
type MockTxStore struct {
	mock.Mock
}

type MockTxStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxStore) EXPECT() *MockTxStore_Expecter {
	return &MockTxStore_Expecter{mock: &_m.Mock}
}

// Album provides a mock function with no fields
func (_m *MockTxStore) Album() store.AlbumStore {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Album")
	}

	var r0 store.AlbumStore
	if rf, ok := ret.Get(0).(func() store.AlbumStore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.AlbumStore)
		}
	}

	return r0
}

// MockTxStore_Album_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Album'
type MockTxStore_Album_Call struct {
	*mock.Call
}

// Album is a helper method to define mock.On call
func (_e *MockTxStore_Expecter) Album() *MockTxStore_Album_Call {
	return &MockTxStore_Album_Call{Call: _e.mock.On("Album")}
}

func (_c *MockTxStore_Album_Call) Run(run func()) *MockTxStore_Album_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTxStore_Album_Call) Return(_a0 store.AlbumStore) *MockTxStore_Album_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxStore_Album_Call) RunAndReturn(run func() store.AlbumStore) *MockTxStore_Album_Call {
	_c.Call.Return(run)
	return _c
}

// AlbumGroupPermission provides a mock function with no fields
func (_m *MockTxStore) AlbumGroupPermission() store.AlbumGroupPermissionStore {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AlbumGroupPermission")
	}

	var r0 store.AlbumGroupPermissionStore
	if rf, ok := ret.Get(0).(func() store.AlbumGroupPermissionStore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.AlbumGroupPermissionStore)
		}
	}

	return r0
}

// MockTxStore_AlbumGroupPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AlbumGroupPermission'
type MockTxStore_AlbumGroupPermission_Call struct {
	*mock.Call
}

// AlbumGroupPermission is a helper method to define mock.On call
func (_e *MockTxStore_Expecter) AlbumGroupPermission() *MockTxStore_AlbumGroupPermission_Call {
	return &MockTxStore_AlbumGroupPermission_Call{Call: _e.mock.On("AlbumGroupPermission")}
}

func (_c *MockTxStore_AlbumGroupPermission_Call) Run(run func()) *MockTxStore_AlbumGroupPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTxStore_AlbumGroupPermission_Call) Return(_a0 store.AlbumGroupPermissionStore) *MockTxStore_AlbumGroupPermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxStore_AlbumGroupPermission_Call) RunAndReturn(run func() store.AlbumGroupPermissionStore) *MockTxStore_AlbumGroupPermission_Call {
	_c.Call.Return(run)
	return _c
}

// Face provides a mock function with no fields
func (_m *MockTxStore) Face() store.FaceStore {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Face")
	}

	var r0 store.FaceStore
	if rf, ok := ret.Get(0).(func() store.FaceStore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.FaceStore)
		}
	}

	return r0
}

// MockTxStore_Face_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Face'
type MockTxStore_Face_Call struct {
	*mock.Call
}

// Face is a helper method to define mock.On call
func (_e *MockTxStore_Expecter) Face() *MockTxStore_Face_Call {
	return &MockTxStore_Face_Call{Call: _e.mock.On("Face")}
}

func (_c *MockTxStore_Face_Call) Run(run func()) *MockTxStore_Face_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTxStore_Face_Call) Return(_a0 store.FaceStore) *MockTxStore_Face_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxStore_Face_Call) RunAndReturn(run func() store.FaceStore) *MockTxStore_Face_Call {
	_c.Call.Return(run)
	return _c
}

// Family provides a mock function with no fields
func (_m *MockTxStore) Family() store.FamilyStore {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Family")
	}

	var r0 store.FamilyStore
	if rf, ok := ret.Get(0).(func() store.FamilyStore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.FamilyStore)
		}
	}

	return r0
}

// MockTxStore_Family_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Family'
type MockTxStore_Family_Call struct {
	*mock.Call
}

// Family is a helper method to define mock.On call
func (_e *MockTxStore_Expecter) Family() *MockTxStore_Family_Call {
	return &MockTxStore_Family_Call{Call: _e.mock.On("Family")}
}

func (_c *MockTxStore_Family_Call) Run(run func()) *MockTxStore_Family_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTxStore_Family_Call) Return(_a0 store.FamilyStore) *MockTxStore_Family_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxStore_Family_Call) RunAndReturn(run func() store.FamilyStore) *MockTxStore_Family_Call {
	_c.Call.Return(run)
	return _c
}

// Group provides a mock function with no fields
func (_m *MockTxStore) Group() store.GroupStore {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Group")
	}

	var r0 store.GroupStore
	if rf, ok := ret.Get(0).(func() store.GroupStore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.GroupStore)
		}
	}

	return r0
}

// MockTxStore_Group_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Group'
type MockTxStore_Group_Call struct {
	*mock.Call
}

// Group is a helper method to define mock.On call
func (_e *MockTxStore_Expecter) Group() *MockTxStore_Group_Call {
	return &MockTxStore_Group_Call{Call: _e.mock.On("Group")}
}

func (_c *MockTxStore_Group_Call) Run(run func()) *MockTxStore_Group_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTxStore_Group_Call) Return(_a0 store.GroupStore) *MockTxStore_Group_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxStore_Group_Call) RunAndReturn(run func() store.GroupStore) *MockTxStore_Group_Call {
	_c.Call.Return(run)
	return _c
}

// Identity provides a mock function with no fields
func (_m *MockTxStore) Identity() store.IdentityStore {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Identity")
	}

	var r0 store.IdentityStore
	if rf, ok := ret.Get(0).(func() store.IdentityStore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.IdentityStore)
		}
	}

	return r0
}

// MockTxStore_Identity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Identity'
type MockTxStore_Identity_Call struct {
	*mock.Call
}

// Identity is a helper method to define mock.On call
func (_e *MockTxStore_Expecter) Identity() *MockTxStore_Identity_Call {
	return &MockTxStore_Identity_Call{Call: _e.mock.On("Identity")}
}

func (_c *MockTxStore_Identity_Call) Run(run func()) *MockTxStore_Identity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTxStore_Identity_Call) Return(_a0 store.IdentityStore) *MockTxStore_Identity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxStore_Identity_Call) RunAndReturn(run func() store.IdentityStore) *MockTxStore_Identity_Call {
	_c.Call.Return(run)
	return _c
}

// IdentityFaceImg provides a mock function with no fields
func (_m *MockTxStore) IdentityFaceImg() store.IdentityFaceImgStore {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IdentityFaceImg")
	}

	var r0 store.IdentityFaceImgStore
	if rf, ok := ret.Get(0).(func() store.IdentityFaceImgStore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.IdentityFaceImgStore)
		}
	}

	return r0
}

// MockTxStore_IdentityFaceImg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IdentityFaceImg'
type MockTxStore_IdentityFaceImg_Call struct {
	*mock.Call
}

// IdentityFaceImg is a helper method to define mock.On call
func (_e *MockTxStore_Expecter) IdentityFaceImg() *MockTxStore_IdentityFaceImg_Call {
	return &MockTxStore_IdentityFaceImg_Call{Call: _e.mock.On("IdentityFaceImg")}
}

func (_c *MockTxStore_IdentityFaceImg_Call) Run(run func()) *MockTxStore_IdentityFaceImg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTxStore_IdentityFaceImg_Call) Return(_a0 store.IdentityFaceImgStore) *MockTxStore_IdentityFaceImg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxStore_IdentityFaceImg_Call) RunAndReturn(run func() store.IdentityFaceImgStore) *MockTxStore_IdentityFaceImg_Call {
	_c.Call.Return(run)
	return _c
}

// InviteToken provides a mock function with no fields
func (_m *MockTxStore) InviteToken() store.InviteTokenStore {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InviteToken")
	}

	var r0 store.InviteTokenStore
	if rf, ok := ret.Get(0).(func() store.InviteTokenStore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.InviteTokenStore)
		}
	}

	return r0
}

// MockTxStore_InviteToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InviteToken'
type MockTxStore_InviteToken_Call struct {
	*mock.Call
}

// InviteToken is a helper method to define mock.On call
func (_e *MockTxStore_Expecter) InviteToken() *MockTxStore_InviteToken_Call {
	return &MockTxStore_InviteToken_Call{Call: _e.mock.On("InviteToken")}
}

func (_c *MockTxStore_InviteToken_Call) Run(run func()) *MockTxStore_InviteToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTxStore_InviteToken_Call) Return(_a0 store.InviteTokenStore) *MockTxStore_InviteToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxStore_InviteToken_Call) RunAndReturn(run func() store.InviteTokenStore) *MockTxStore_InviteToken_Call {
	_c.Call.Return(run)
	return _c
}

// Kid provides a mock function with no fields
func (_m *MockTxStore) Kid() store.KidStore {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Kid")
	}

	var r0 store.KidStore
	if rf, ok := ret.Get(0).(func() store.KidStore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.KidStore)
		}
	}

	return r0
}

// MockTxStore_Kid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kid'
type MockTxStore_Kid_Call struct {
	*mock.Call
}

// Kid is a helper method to define mock.On call
func (_e *MockTxStore_Expecter) Kid() *MockTxStore_Kid_Call {
	return &MockTxStore_Kid_Call{Call: _e.mock.On("Kid")}
}

func (_c *MockTxStore_Kid_Call) Run(run func()) *MockTxStore_Kid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTxStore_Kid_Call) Return(_a0 store.KidStore) *MockTxStore_Kid_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxStore_Kid_Call) RunAndReturn(run func() store.KidStore) *MockTxStore_Kid_Call {
	_c.Call.Return(run)
	return _c
}

// Like provides a mock function with no fields
func (_m *MockTxStore) Like() store.LikeStore {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Like")
	}

	var r0 store.LikeStore
	if rf, ok := ret.Get(0).(func() store.LikeStore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.LikeStore)
		}
	}

	return r0
}

// MockTxStore_Like_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Like'
type MockTxStore_Like_Call struct {
	*mock.Call
}

// Like is a helper method to define mock.On call
func (_e *MockTxStore_Expecter) Like() *MockTxStore_Like_Call {
	return &MockTxStore_Like_Call{Call: _e.mock.On("Like")}
}

func (_c *MockTxStore_Like_Call) Run(run func()) *MockTxStore_Like_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTxStore_Like_Call) Return(_a0 store.LikeStore) *MockTxStore_Like_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxStore_Like_Call) RunAndReturn(run func() store.LikeStore) *MockTxStore_Like_Call {
	_c.Call.Return(run)
	return _c
}

// MediaItem provides a mock function with no fields
func (_m *MockTxStore) MediaItem() store.MediaItemStore {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MediaItem")
	}

	var r0 store.MediaItemStore
	if rf, ok := ret.Get(0).(func() store.MediaItemStore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.MediaItemStore)
		}
	}

	return r0
}

// MockTxStore_MediaItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MediaItem'
type MockTxStore_MediaItem_Call struct {
	*mock.Call
}

// MediaItem is a helper method to define mock.On call
func (_e *MockTxStore_Expecter) MediaItem() *MockTxStore_MediaItem_Call {
	return &MockTxStore_MediaItem_Call{Call: _e.mock.On("MediaItem")}
}

func (_c *MockTxStore_MediaItem_Call) Run(run func()) *MockTxStore_MediaItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTxStore_MediaItem_Call) Return(_a0 store.MediaItemStore) *MockTxStore_MediaItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxStore_MediaItem_Call) RunAndReturn(run func() store.MediaItemStore) *MockTxStore_MediaItem_Call {
	_c.Call.Return(run)
	return _c
}

// Tag provides a mock function with no fields
func (_m *MockTxStore) Tag() store.TagStore {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tag")
	}

	var r0 store.TagStore
	if rf, ok := ret.Get(0).(func() store.TagStore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.TagStore)
		}
	}

	return r0
}

// MockTxStore_Tag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tag'
type MockTxStore_Tag_Call struct {
	*mock.Call
}

// Tag is a helper method to define mock.On call
func (_e *MockTxStore_Expecter) Tag() *MockTxStore_Tag_Call {
	return &MockTxStore_Tag_Call{Call: _e.mock.On("Tag")}
}

func (_c *MockTxStore_Tag_Call) Run(run func()) *MockTxStore_Tag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTxStore_Tag_Call) Return(_a0 store.TagStore) *MockTxStore_Tag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxStore_Tag_Call) RunAndReturn(run func() store.TagStore) *MockTxStore_Tag_Call {
	_c.Call.Return(run)
	return _c
}

// User provides a mock function with no fields
func (_m *MockTxStore) User() store.UserStore {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for User")
	}

	var r0 store.UserStore
	if rf, ok := ret.Get(0).(func() store.UserStore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.UserStore)
		}
	}

	return r0
}

// MockTxStore_User_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'User'
type MockTxStore_User_Call struct {
	*mock.Call
}

// User is a helper method to define mock.On call
func (_e *MockTxStore_Expecter) User() *MockTxStore_User_Call {
	return &MockTxStore_User_Call{Call: _e.mock.On("User")}
}

func (_c *MockTxStore_User_Call) Run(run func()) *MockTxStore_User_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTxStore_User_Call) Return(_a0 store.UserStore) *MockTxStore_User_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxStore_User_Call) RunAndReturn(run func() store.UserStore) *MockTxStore_User_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTxStore creates a new instance of MockTxStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxStore {
	mock := &MockTxStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
