// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "github.com/ywl0806/yuno_kiroku/internal/db"
)

// MockIdentityFaceImgStore is an autogenerated mock type for the IdentityFaceImgStore type
type MockIdentityFaceImgStore struct {
	mock.Mock
}

type MockIdentityFaceImgStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdentityFaceImgStore) EXPECT() *MockIdentityFaceImgStore_Expecter {
	return &MockIdentityFaceImgStore_Expecter{mock: &_m.Mock}
}

// CreateIdentityFaceImg provides a mock function with given fields: ctx, arg
func (_m *MockIdentityFaceImgStore) CreateIdentityFaceImg(ctx context.Context, arg db.CreateIdentityFaceImgParams) (db.IdentityFaceImg, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateIdentityFaceImg")
	}

	var r0 db.IdentityFaceImg
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateIdentityFaceImgParams) (db.IdentityFaceImg, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateIdentityFaceImgParams) db.IdentityFaceImg); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.IdentityFaceImg)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateIdentityFaceImgParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIdentityFaceImgStore_CreateIdentityFaceImg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIdentityFaceImg'
type MockIdentityFaceImgStore_CreateIdentityFaceImg_Call struct {
	*mock.Call
}

// CreateIdentityFaceImg is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateIdentityFaceImgParams
func (_e *MockIdentityFaceImgStore_Expecter) CreateIdentityFaceImg(ctx interface{}, arg interface{}) *MockIdentityFaceImgStore_CreateIdentityFaceImg_Call {
	return &MockIdentityFaceImgStore_CreateIdentityFaceImg_Call{Call: _e.mock.On("CreateIdentityFaceImg", ctx, arg)}
}

func (_c *MockIdentityFaceImgStore_CreateIdentityFaceImg_Call) Run(run func(ctx context.Context, arg db.CreateIdentityFaceImgParams)) *MockIdentityFaceImgStore_CreateIdentityFaceImg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateIdentityFaceImgParams))
	})
	return _c
}

func (_c *MockIdentityFaceImgStore_CreateIdentityFaceImg_Call) Return(_a0 db.IdentityFaceImg, _a1 error) *MockIdentityFaceImgStore_CreateIdentityFaceImg_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIdentityFaceImgStore_CreateIdentityFaceImg_Call) RunAndReturn(run func(context.Context, db.CreateIdentityFaceImgParams) (db.IdentityFaceImg, error)) *MockIdentityFaceImgStore_CreateIdentityFaceImg_Call {
	_c.Call.Return(run)
	return _c
}

// FindNewestIdentityFaceImgByFamilyId provides a mock function with given fields: ctx, arg
func (_m *MockIdentityFaceImgStore) FindNewestIdentityFaceImgByFamilyId(ctx context.Context, arg db.FindNewestIdentityFaceImgByFamilyIdParams) ([]db.FindNewestIdentityFaceImgByFamilyIdRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindNewestIdentityFaceImgByFamilyId")
	}

	var r0 []db.FindNewestIdentityFaceImgByFamilyIdRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.FindNewestIdentityFaceImgByFamilyIdParams) ([]db.FindNewestIdentityFaceImgByFamilyIdRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.FindNewestIdentityFaceImgByFamilyIdParams) []db.FindNewestIdentityFaceImgByFamilyIdRow); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.FindNewestIdentityFaceImgByFamilyIdRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.FindNewestIdentityFaceImgByFamilyIdParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIdentityFaceImgStore_FindNewestIdentityFaceImgByFamilyId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNewestIdentityFaceImgByFamilyId'
type MockIdentityFaceImgStore_FindNewestIdentityFaceImgByFamilyId_Call struct {
	*mock.Call
}

// FindNewestIdentityFaceImgByFamilyId is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.FindNewestIdentityFaceImgByFamilyIdParams
func (_e *MockIdentityFaceImgStore_Expecter) FindNewestIdentityFaceImgByFamilyId(ctx interface{}, arg interface{}) *MockIdentityFaceImgStore_FindNewestIdentityFaceImgByFamilyId_Call {
	return &MockIdentityFaceImgStore_FindNewestIdentityFaceImgByFamilyId_Call{Call: _e.mock.On("FindNewestIdentityFaceImgByFamilyId", ctx, arg)}
}

func (_c *MockIdentityFaceImgStore_FindNewestIdentityFaceImgByFamilyId_Call) Run(run func(ctx context.Context, arg db.FindNewestIdentityFaceImgByFamilyIdParams)) *MockIdentityFaceImgStore_FindNewestIdentityFaceImgByFamilyId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.FindNewestIdentityFaceImgByFamilyIdParams))
	})
	return _c
}

func (_c *MockIdentityFaceImgStore_FindNewestIdentityFaceImgByFamilyId_Call) Return(_a0 []db.FindNewestIdentityFaceImgByFamilyIdRow, _a1 error) *MockIdentityFaceImgStore_FindNewestIdentityFaceImgByFamilyId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIdentityFaceImgStore_FindNewestIdentityFaceImgByFamilyId_Call) RunAndReturn(run func(context.Context, db.FindNewestIdentityFaceImgByFamilyIdParams) ([]db.FindNewestIdentityFaceImgByFamilyIdRow, error)) *MockIdentityFaceImgStore_FindNewestIdentityFaceImgByFamilyId_Call {
	_c.Call.Return(run)
	return _c
}

// HasIdentityFaceImg provides a mock function with given fields: ctx, identityID
func (_m *MockIdentityFaceImgStore) HasIdentityFaceImg(ctx context.Context, identityID int32) (bool, error) {
	ret := _m.Called(ctx, identityID)

	if len(ret) == 0 {
		panic("no return value specified for HasIdentityFaceImg")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (bool, error)); ok {
		return rf(ctx, identityID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) bool); ok {
		r0 = rf(ctx, identityID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, identityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIdentityFaceImgStore_HasIdentityFaceImg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasIdentityFaceImg'
type MockIdentityFaceImgStore_HasIdentityFaceImg_Call struct {
	*mock.Call
}

// HasIdentityFaceImg is a helper method to define mock.On call
//   - ctx context.Context
//   - identityID int32
func (_e *MockIdentityFaceImgStore_Expecter) HasIdentityFaceImg(ctx interface{}, identityID interface{}) *MockIdentityFaceImgStore_HasIdentityFaceImg_Call {
	return &MockIdentityFaceImgStore_HasIdentityFaceImg_Call{Call: _e.mock.On("HasIdentityFaceImg", ctx, identityID)}
}

func (_c *MockIdentityFaceImgStore_HasIdentityFaceImg_Call) Run(run func(ctx context.Context, identityID int32)) *MockIdentityFaceImgStore_HasIdentityFaceImg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockIdentityFaceImgStore_HasIdentityFaceImg_Call) Return(_a0 bool, _a1 error) *MockIdentityFaceImgStore_HasIdentityFaceImg_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIdentityFaceImgStore_HasIdentityFaceImg_Call) RunAndReturn(run func(context.Context, int32) (bool, error)) *MockIdentityFaceImgStore_HasIdentityFaceImg_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIdentityFaceImgStore creates a new instance of MockIdentityFaceImgStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdentityFaceImgStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdentityFaceImgStore {
	mock := &MockIdentityFaceImgStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
