// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "github.com/ywl0806/yuno_kiroku/internal/db"
)

// MockAlbumGroupPermissionStore is an autogenerated mock type for the AlbumGroupPermissionStore type
type MockAlbumGroupPermissionStore struct {
	mock.Mock
}

type MockAlbumGroupPermissionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlbumGroupPermissionStore) EXPECT() *MockAlbumGroupPermissionStore_Expecter {
	return &MockAlbumGroupPermissionStore_Expecter{mock: &_m.Mock}
}

// DeleteAlbumGroupPermissionsByAlbumID provides a mock function with given fields: ctx, albumID
func (_m *MockAlbumGroupPermissionStore) DeleteAlbumGroupPermissionsByAlbumID(ctx context.Context, albumID int32) error {
	ret := _m.Called(ctx, albumID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAlbumGroupPermissionsByAlbumID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, albumID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAlbumGroupPermissionStore_DeleteAlbumGroupPermissionsByAlbumID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAlbumGroupPermissionsByAlbumID'
type MockAlbumGroupPermissionStore_DeleteAlbumGroupPermissionsByAlbumID_Call struct {
	*mock.Call
}

// DeleteAlbumGroupPermissionsByAlbumID is a helper method to define mock.On call
//   - ctx context.Context
//   - albumID int32
func (_e *MockAlbumGroupPermissionStore_Expecter) DeleteAlbumGroupPermissionsByAlbumID(ctx interface{}, albumID interface{}) *MockAlbumGroupPermissionStore_DeleteAlbumGroupPermissionsByAlbumID_Call {
	return &MockAlbumGroupPermissionStore_DeleteAlbumGroupPermissionsByAlbumID_Call{Call: _e.mock.On("DeleteAlbumGroupPermissionsByAlbumID", ctx, albumID)}
}

func (_c *MockAlbumGroupPermissionStore_DeleteAlbumGroupPermissionsByAlbumID_Call) Run(run func(ctx context.Context, albumID int32)) *MockAlbumGroupPermissionStore_DeleteAlbumGroupPermissionsByAlbumID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockAlbumGroupPermissionStore_DeleteAlbumGroupPermissionsByAlbumID_Call) Return(_a0 error) *MockAlbumGroupPermissionStore_DeleteAlbumGroupPermissionsByAlbumID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlbumGroupPermissionStore_DeleteAlbumGroupPermissionsByAlbumID_Call) RunAndReturn(run func(context.Context, int32) error) *MockAlbumGroupPermissionStore_DeleteAlbumGroupPermissionsByAlbumID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlbumGroupPermissions provides a mock function with given fields: ctx, albumID
func (_m *MockAlbumGroupPermissionStore) GetAlbumGroupPermissions(ctx context.Context, albumID int32) ([]db.AlbumGroupsPermission, error) {
	ret := _m.Called(ctx, albumID)

	if len(ret) == 0 {
		panic("no return value specified for GetAlbumGroupPermissions")
	}

	var r0 []db.AlbumGroupsPermission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]db.AlbumGroupsPermission, error)); ok {
		return rf(ctx, albumID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []db.AlbumGroupsPermission); ok {
		r0 = rf(ctx, albumID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.AlbumGroupsPermission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, albumID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlbumGroupPermissionStore_GetAlbumGroupPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlbumGroupPermissions'
type MockAlbumGroupPermissionStore_GetAlbumGroupPermissions_Call struct {
	*mock.Call
}

// GetAlbumGroupPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - albumID int32
func (_e *MockAlbumGroupPermissionStore_Expecter) GetAlbumGroupPermissions(ctx interface{}, albumID interface{}) *MockAlbumGroupPermissionStore_GetAlbumGroupPermissions_Call {
	return &MockAlbumGroupPermissionStore_GetAlbumGroupPermissions_Call{Call: _e.mock.On("GetAlbumGroupPermissions", ctx, albumID)}
}

func (_c *MockAlbumGroupPermissionStore_GetAlbumGroupPermissions_Call) Run(run func(ctx context.Context, albumID int32)) *MockAlbumGroupPermissionStore_GetAlbumGroupPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockAlbumGroupPermissionStore_GetAlbumGroupPermissions_Call) Return(_a0 []db.AlbumGroupsPermission, _a1 error) *MockAlbumGroupPermissionStore_GetAlbumGroupPermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlbumGroupPermissionStore_GetAlbumGroupPermissions_Call) RunAndReturn(run func(context.Context, int32) ([]db.AlbumGroupsPermission, error)) *MockAlbumGroupPermissionStore_GetAlbumGroupPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// InsertAlbumGroupPermission provides a mock function with given fields: ctx, arg
func (_m *MockAlbumGroupPermissionStore) InsertAlbumGroupPermission(ctx context.Context, arg db.InsertAlbumGroupPermissionParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InsertAlbumGroupPermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.InsertAlbumGroupPermissionParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAlbumGroupPermissionStore_InsertAlbumGroupPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertAlbumGroupPermission'
type MockAlbumGroupPermissionStore_InsertAlbumGroupPermission_Call struct {
	*mock.Call
}

// InsertAlbumGroupPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.InsertAlbumGroupPermissionParams
func (_e *MockAlbumGroupPermissionStore_Expecter) InsertAlbumGroupPermission(ctx interface{}, arg interface{}) *MockAlbumGroupPermissionStore_InsertAlbumGroupPermission_Call {
	return &MockAlbumGroupPermissionStore_InsertAlbumGroupPermission_Call{Call: _e.mock.On("InsertAlbumGroupPermission", ctx, arg)}
}

func (_c *MockAlbumGroupPermissionStore_InsertAlbumGroupPermission_Call) Run(run func(ctx context.Context, arg db.InsertAlbumGroupPermissionParams)) *MockAlbumGroupPermissionStore_InsertAlbumGroupPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.InsertAlbumGroupPermissionParams))
	})
	return _c
}

func (_c *MockAlbumGroupPermissionStore_InsertAlbumGroupPermission_Call) Return(_a0 error) *MockAlbumGroupPermissionStore_InsertAlbumGroupPermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlbumGroupPermissionStore_InsertAlbumGroupPermission_Call) RunAndReturn(run func(context.Context, db.InsertAlbumGroupPermissionParams) error) *MockAlbumGroupPermissionStore_InsertAlbumGroupPermission_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAlbumGroupPermissionStore creates a new instance of MockAlbumGroupPermissionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlbumGroupPermissionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlbumGroupPermissionStore {
	mock := &MockAlbumGroupPermissionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
