// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "github.com/ywl0806/yuno_kiroku/internal/db"
)

// MockFaceStore is an autogenerated mock type for the FaceStore type
type MockFaceStore struct {
	mock.Mock
}

type MockFaceStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFaceStore) EXPECT() *MockFaceStore_Expecter {
	return &MockFaceStore_Expecter{mock: &_m.Mock}
}

// CreateFaceDetection provides a mock function with given fields: ctx, arg
func (_m *MockFaceStore) CreateFaceDetection(ctx context.Context, arg db.CreateFaceDetectionParams) (db.FaceDetection, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateFaceDetection")
	}

	var r0 db.FaceDetection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateFaceDetectionParams) (db.FaceDetection, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateFaceDetectionParams) db.FaceDetection); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.FaceDetection)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateFaceDetectionParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFaceStore_CreateFaceDetection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFaceDetection'
type MockFaceStore_CreateFaceDetection_Call struct {
	*mock.Call
}

// CreateFaceDetection is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateFaceDetectionParams
func (_e *MockFaceStore_Expecter) CreateFaceDetection(ctx interface{}, arg interface{}) *MockFaceStore_CreateFaceDetection_Call {
	return &MockFaceStore_CreateFaceDetection_Call{Call: _e.mock.On("CreateFaceDetection", ctx, arg)}
}

func (_c *MockFaceStore_CreateFaceDetection_Call) Run(run func(ctx context.Context, arg db.CreateFaceDetectionParams)) *MockFaceStore_CreateFaceDetection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateFaceDetectionParams))
	})
	return _c
}

func (_c *MockFaceStore_CreateFaceDetection_Call) Return(_a0 db.FaceDetection, _a1 error) *MockFaceStore_CreateFaceDetection_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFaceStore_CreateFaceDetection_Call) RunAndReturn(run func(context.Context, db.CreateFaceDetectionParams) (db.FaceDetection, error)) *MockFaceStore_CreateFaceDetection_Call {
	_c.Call.Return(run)
	return _c
}

// FindMostSimilarFace provides a mock function with given fields: ctx, arg
func (_m *MockFaceStore) FindMostSimilarFace(ctx context.Context, arg db.FindMostSimilarFaceParams) (db.FindMostSimilarFaceRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindMostSimilarFace")
	}

	var r0 db.FindMostSimilarFaceRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.FindMostSimilarFaceParams) (db.FindMostSimilarFaceRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.FindMostSimilarFaceParams) db.FindMostSimilarFaceRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.FindMostSimilarFaceRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.FindMostSimilarFaceParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFaceStore_FindMostSimilarFace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMostSimilarFace'
type MockFaceStore_FindMostSimilarFace_Call struct {
	*mock.Call
}

// FindMostSimilarFace is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.FindMostSimilarFaceParams
func (_e *MockFaceStore_Expecter) FindMostSimilarFace(ctx interface{}, arg interface{}) *MockFaceStore_FindMostSimilarFace_Call {
	return &MockFaceStore_FindMostSimilarFace_Call{Call: _e.mock.On("FindMostSimilarFace", ctx, arg)}
}

func (_c *MockFaceStore_FindMostSimilarFace_Call) Run(run func(ctx context.Context, arg db.FindMostSimilarFaceParams)) *MockFaceStore_FindMostSimilarFace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.FindMostSimilarFaceParams))
	})
	return _c
}

func (_c *MockFaceStore_FindMostSimilarFace_Call) Return(_a0 db.FindMostSimilarFaceRow, _a1 error) *MockFaceStore_FindMostSimilarFace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFaceStore_FindMostSimilarFace_Call) RunAndReturn(run func(context.Context, db.FindMostSimilarFaceParams) (db.FindMostSimilarFaceRow, error)) *MockFaceStore_FindMostSimilarFace_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFaceStore creates a new instance of MockFaceStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFaceStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFaceStore {
	mock := &MockFaceStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
