// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "github.com/ywl0806/yuno_kiroku/internal/db"
)

// MockFamilyStore is an autogenerated mock type for the FamilyStore type
type MockFamilyStore struct {
	mock.Mock
}

type MockFamilyStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFamilyStore) EXPECT() *MockFamilyStore_Expecter {
	return &MockFamilyStore_Expecter{mock: &_m.Mock}
}

// CreateFamily provides a mock function with given fields: ctx, name
func (_m *MockFamilyStore) CreateFamily(ctx context.Context, name string) (db.Family, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateFamily")
	}

	var r0 db.Family
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.Family, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.Family); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(db.Family)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFamilyStore_CreateFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFamily'
type MockFamilyStore_CreateFamily_Call struct {
	*mock.Call
}

// CreateFamily is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockFamilyStore_Expecter) CreateFamily(ctx interface{}, name interface{}) *MockFamilyStore_CreateFamily_Call {
	return &MockFamilyStore_CreateFamily_Call{Call: _e.mock.On("CreateFamily", ctx, name)}
}

func (_c *MockFamilyStore_CreateFamily_Call) Run(run func(ctx context.Context, name string)) *MockFamilyStore_CreateFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFamilyStore_CreateFamily_Call) Return(_a0 db.Family, _a1 error) *MockFamilyStore_CreateFamily_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFamilyStore_CreateFamily_Call) RunAndReturn(run func(context.Context, string) (db.Family, error)) *MockFamilyStore_CreateFamily_Call {
	_c.Call.Return(run)
	return _c
}

// FindFamilyByID provides a mock function with given fields: ctx, id
func (_m *MockFamilyStore) FindFamilyByID(ctx context.Context, id int32) (db.FindFamilyByIDRow, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindFamilyByID")
	}

	var r0 db.FindFamilyByIDRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (db.FindFamilyByIDRow, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) db.FindFamilyByIDRow); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.FindFamilyByIDRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFamilyStore_FindFamilyByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindFamilyByID'
type MockFamilyStore_FindFamilyByID_Call struct {
	*mock.Call
}

// FindFamilyByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockFamilyStore_Expecter) FindFamilyByID(ctx interface{}, id interface{}) *MockFamilyStore_FindFamilyByID_Call {
	return &MockFamilyStore_FindFamilyByID_Call{Call: _e.mock.On("FindFamilyByID", ctx, id)}
}

func (_c *MockFamilyStore_FindFamilyByID_Call) Run(run func(ctx context.Context, id int32)) *MockFamilyStore_FindFamilyByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockFamilyStore_FindFamilyByID_Call) Return(_a0 db.FindFamilyByIDRow, _a1 error) *MockFamilyStore_FindFamilyByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFamilyStore_FindFamilyByID_Call) RunAndReturn(run func(context.Context, int32) (db.FindFamilyByIDRow, error)) *MockFamilyStore_FindFamilyByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFamilyByID provides a mock function with given fields: ctx, id
func (_m *MockFamilyStore) GetFamilyByID(ctx context.Context, id int32) (db.Family, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFamilyByID")
	}

	var r0 db.Family
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (db.Family, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) db.Family); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Family)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFamilyStore_GetFamilyByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFamilyByID'
type MockFamilyStore_GetFamilyByID_Call struct {
	*mock.Call
}

// GetFamilyByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockFamilyStore_Expecter) GetFamilyByID(ctx interface{}, id interface{}) *MockFamilyStore_GetFamilyByID_Call {
	return &MockFamilyStore_GetFamilyByID_Call{Call: _e.mock.On("GetFamilyByID", ctx, id)}
}

func (_c *MockFamilyStore_GetFamilyByID_Call) Run(run func(ctx context.Context, id int32)) *MockFamilyStore_GetFamilyByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockFamilyStore_GetFamilyByID_Call) Return(_a0 db.Family, _a1 error) *MockFamilyStore_GetFamilyByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFamilyStore_GetFamilyByID_Call) RunAndReturn(run func(context.Context, int32) (db.Family, error)) *MockFamilyStore_GetFamilyByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFamilyStore creates a new instance of MockFamilyStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFamilyStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFamilyStore {
	mock := &MockFamilyStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
