// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "github.com/ywl0806/yuno_kiroku/internal/db"
)

// MockIdentityStore is an autogenerated mock type for the IdentityStore type
type MockIdentityStore struct {
	mock.Mock
}

type MockIdentityStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdentityStore) EXPECT() *MockIdentityStore_Expecter {
	return &MockIdentityStore_Expecter{mock: &_m.Mock}
}

// CreateIdentity provides a mock function with given fields: ctx, familyID
func (_m *MockIdentityStore) CreateIdentity(ctx context.Context, familyID int32) (db.Identity, error) {
	ret := _m.Called(ctx, familyID)

	if len(ret) == 0 {
		panic("no return value specified for CreateIdentity")
	}

	var r0 db.Identity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (db.Identity, error)); ok {
		return rf(ctx, familyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) db.Identity); ok {
		r0 = rf(ctx, familyID)
	} else {
		r0 = ret.Get(0).(db.Identity)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, familyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIdentityStore_CreateIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIdentity'
type MockIdentityStore_CreateIdentity_Call struct {
	*mock.Call
}

// CreateIdentity is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID int32
func (_e *MockIdentityStore_Expecter) CreateIdentity(ctx interface{}, familyID interface{}) *MockIdentityStore_CreateIdentity_Call {
	return &MockIdentityStore_CreateIdentity_Call{Call: _e.mock.On("CreateIdentity", ctx, familyID)}
}

func (_c *MockIdentityStore_CreateIdentity_Call) Run(run func(ctx context.Context, familyID int32)) *MockIdentityStore_CreateIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockIdentityStore_CreateIdentity_Call) Return(_a0 db.Identity, _a1 error) *MockIdentityStore_CreateIdentity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIdentityStore_CreateIdentity_Call) RunAndReturn(run func(context.Context, int32) (db.Identity, error)) *MockIdentityStore_CreateIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// FindIdentitiesByFamilyId provides a mock function with given fields: ctx, familyID
func (_m *MockIdentityStore) FindIdentitiesByFamilyId(ctx context.Context, familyID int32) ([]db.Identity, error) {
	ret := _m.Called(ctx, familyID)

	if len(ret) == 0 {
		panic("no return value specified for FindIdentitiesByFamilyId")
	}

	var r0 []db.Identity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]db.Identity, error)); ok {
		return rf(ctx, familyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []db.Identity); ok {
		r0 = rf(ctx, familyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Identity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, familyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIdentityStore_FindIdentitiesByFamilyId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindIdentitiesByFamilyId'
type MockIdentityStore_FindIdentitiesByFamilyId_Call struct {
	*mock.Call
}

// FindIdentitiesByFamilyId is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID int32
func (_e *MockIdentityStore_Expecter) FindIdentitiesByFamilyId(ctx interface{}, familyID interface{}) *MockIdentityStore_FindIdentitiesByFamilyId_Call {
	return &MockIdentityStore_FindIdentitiesByFamilyId_Call{Call: _e.mock.On("FindIdentitiesByFamilyId", ctx, familyID)}
}

func (_c *MockIdentityStore_FindIdentitiesByFamilyId_Call) Run(run func(ctx context.Context, familyID int32)) *MockIdentityStore_FindIdentitiesByFamilyId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockIdentityStore_FindIdentitiesByFamilyId_Call) Return(_a0 []db.Identity, _a1 error) *MockIdentityStore_FindIdentitiesByFamilyId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIdentityStore_FindIdentitiesByFamilyId_Call) RunAndReturn(run func(context.Context, int32) ([]db.Identity, error)) *MockIdentityStore_FindIdentitiesByFamilyId_Call {
	_c.Call.Return(run)
	return _c
}

// FindIdentityByIdAndFamilyId provides a mock function with given fields: ctx, arg
func (_m *MockIdentityStore) FindIdentityByIdAndFamilyId(ctx context.Context, arg db.FindIdentityByIdAndFamilyIdParams) (db.Identity, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindIdentityByIdAndFamilyId")
	}

	var r0 db.Identity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.FindIdentityByIdAndFamilyIdParams) (db.Identity, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.FindIdentityByIdAndFamilyIdParams) db.Identity); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Identity)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.FindIdentityByIdAndFamilyIdParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIdentityStore_FindIdentityByIdAndFamilyId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindIdentityByIdAndFamilyId'
type MockIdentityStore_FindIdentityByIdAndFamilyId_Call struct {
	*mock.Call
}

// FindIdentityByIdAndFamilyId is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.FindIdentityByIdAndFamilyIdParams
func (_e *MockIdentityStore_Expecter) FindIdentityByIdAndFamilyId(ctx interface{}, arg interface{}) *MockIdentityStore_FindIdentityByIdAndFamilyId_Call {
	return &MockIdentityStore_FindIdentityByIdAndFamilyId_Call{Call: _e.mock.On("FindIdentityByIdAndFamilyId", ctx, arg)}
}

func (_c *MockIdentityStore_FindIdentityByIdAndFamilyId_Call) Run(run func(ctx context.Context, arg db.FindIdentityByIdAndFamilyIdParams)) *MockIdentityStore_FindIdentityByIdAndFamilyId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.FindIdentityByIdAndFamilyIdParams))
	})
	return _c
}

func (_c *MockIdentityStore_FindIdentityByIdAndFamilyId_Call) Return(_a0 db.Identity, _a1 error) *MockIdentityStore_FindIdentityByIdAndFamilyId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIdentityStore_FindIdentityByIdAndFamilyId_Call) RunAndReturn(run func(context.Context, db.FindIdentityByIdAndFamilyIdParams) (db.Identity, error)) *MockIdentityStore_FindIdentityByIdAndFamilyId_Call {
	_c.Call.Return(run)
	return _c
}

// GetIdentityOptions provides a mock function with given fields: ctx, familyID
func (_m *MockIdentityStore) GetIdentityOptions(ctx context.Context, familyID int32) ([]db.GetIdentityOptionsRow, error) {
	ret := _m.Called(ctx, familyID)

	if len(ret) == 0 {
		panic("no return value specified for GetIdentityOptions")
	}

	var r0 []db.GetIdentityOptionsRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]db.GetIdentityOptionsRow, error)); ok {
		return rf(ctx, familyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []db.GetIdentityOptionsRow); ok {
		r0 = rf(ctx, familyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetIdentityOptionsRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, familyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIdentityStore_GetIdentityOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIdentityOptions'
type MockIdentityStore_GetIdentityOptions_Call struct {
	*mock.Call
}

// GetIdentityOptions is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID int32
func (_e *MockIdentityStore_Expecter) GetIdentityOptions(ctx interface{}, familyID interface{}) *MockIdentityStore_GetIdentityOptions_Call {
	return &MockIdentityStore_GetIdentityOptions_Call{Call: _e.mock.On("GetIdentityOptions", ctx, familyID)}
}

func (_c *MockIdentityStore_GetIdentityOptions_Call) Run(run func(ctx context.Context, familyID int32)) *MockIdentityStore_GetIdentityOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockIdentityStore_GetIdentityOptions_Call) Return(_a0 []db.GetIdentityOptionsRow, _a1 error) *MockIdentityStore_GetIdentityOptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIdentityStore_GetIdentityOptions_Call) RunAndReturn(run func(context.Context, int32) ([]db.GetIdentityOptionsRow, error)) *MockIdentityStore_GetIdentityOptions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIdentityStore creates a new instance of MockIdentityStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdentityStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdentityStore {
	mock := &MockIdentityStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
