// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "github.com/ywl0806/yuno_kiroku/internal/db"
)

// MockAlbumStore is an autogenerated mock type for the AlbumStore type
type MockAlbumStore struct {
	mock.Mock
}

type MockAlbumStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlbumStore) EXPECT() *MockAlbumStore_Expecter {
	return &MockAlbumStore_Expecter{mock: &_m.Mock}
}

// CreateAlbum provides a mock function with given fields: ctx, arg
func (_m *MockAlbumStore) CreateAlbum(ctx context.Context, arg db.CreateAlbumParams) (db.Album, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateAlbum")
	}

	var r0 db.Album
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateAlbumParams) (db.Album, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateAlbumParams) db.Album); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Album)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateAlbumParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlbumStore_CreateAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAlbum'
type MockAlbumStore_CreateAlbum_Call struct {
	*mock.Call
}

// CreateAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateAlbumParams
func (_e *MockAlbumStore_Expecter) CreateAlbum(ctx interface{}, arg interface{}) *MockAlbumStore_CreateAlbum_Call {
	return &MockAlbumStore_CreateAlbum_Call{Call: _e.mock.On("CreateAlbum", ctx, arg)}
}

func (_c *MockAlbumStore_CreateAlbum_Call) Run(run func(ctx context.Context, arg db.CreateAlbumParams)) *MockAlbumStore_CreateAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateAlbumParams))
	})
	return _c
}

func (_c *MockAlbumStore_CreateAlbum_Call) Return(_a0 db.Album, _a1 error) *MockAlbumStore_CreateAlbum_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlbumStore_CreateAlbum_Call) RunAndReturn(run func(context.Context, db.CreateAlbumParams) (db.Album, error)) *MockAlbumStore_CreateAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAlbum provides a mock function with given fields: ctx, id
func (_m *MockAlbumStore) DeleteAlbum(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAlbum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAlbumStore_DeleteAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAlbum'
type MockAlbumStore_DeleteAlbum_Call struct {
	*mock.Call
}

// DeleteAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockAlbumStore_Expecter) DeleteAlbum(ctx interface{}, id interface{}) *MockAlbumStore_DeleteAlbum_Call {
	return &MockAlbumStore_DeleteAlbum_Call{Call: _e.mock.On("DeleteAlbum", ctx, id)}
}

func (_c *MockAlbumStore_DeleteAlbum_Call) Run(run func(ctx context.Context, id int32)) *MockAlbumStore_DeleteAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockAlbumStore_DeleteAlbum_Call) Return(_a0 error) *MockAlbumStore_DeleteAlbum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlbumStore_DeleteAlbum_Call) RunAndReturn(run func(context.Context, int32) error) *MockAlbumStore_DeleteAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// FindAlbumByID provides a mock function with given fields: ctx, id
func (_m *MockAlbumStore) FindAlbumByID(ctx context.Context, id int32) (db.Album, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindAlbumByID")
	}

	var r0 db.Album
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (db.Album, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) db.Album); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Album)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlbumStore_FindAlbumByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAlbumByID'
type MockAlbumStore_FindAlbumByID_Call struct {
	*mock.Call
}

// FindAlbumByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockAlbumStore_Expecter) FindAlbumByID(ctx interface{}, id interface{}) *MockAlbumStore_FindAlbumByID_Call {
	return &MockAlbumStore_FindAlbumByID_Call{Call: _e.mock.On("FindAlbumByID", ctx, id)}
}

func (_c *MockAlbumStore_FindAlbumByID_Call) Run(run func(ctx context.Context, id int32)) *MockAlbumStore_FindAlbumByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockAlbumStore_FindAlbumByID_Call) Return(_a0 db.Album, _a1 error) *MockAlbumStore_FindAlbumByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlbumStore_FindAlbumByID_Call) RunAndReturn(run func(context.Context, int32) (db.Album, error)) *MockAlbumStore_FindAlbumByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindAlbumsByFamilyID provides a mock function with given fields: ctx, familyID
func (_m *MockAlbumStore) FindAlbumsByFamilyID(ctx context.Context, familyID int32) ([]db.Album, error) {
	ret := _m.Called(ctx, familyID)

	if len(ret) == 0 {
		panic("no return value specified for FindAlbumsByFamilyID")
	}

	var r0 []db.Album
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]db.Album, error)); ok {
		return rf(ctx, familyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []db.Album); ok {
		r0 = rf(ctx, familyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Album)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, familyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlbumStore_FindAlbumsByFamilyID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAlbumsByFamilyID'
type MockAlbumStore_FindAlbumsByFamilyID_Call struct {
	*mock.Call
}

// FindAlbumsByFamilyID is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID int32
func (_e *MockAlbumStore_Expecter) FindAlbumsByFamilyID(ctx interface{}, familyID interface{}) *MockAlbumStore_FindAlbumsByFamilyID_Call {
	return &MockAlbumStore_FindAlbumsByFamilyID_Call{Call: _e.mock.On("FindAlbumsByFamilyID", ctx, familyID)}
}

func (_c *MockAlbumStore_FindAlbumsByFamilyID_Call) Run(run func(ctx context.Context, familyID int32)) *MockAlbumStore_FindAlbumsByFamilyID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockAlbumStore_FindAlbumsByFamilyID_Call) Return(_a0 []db.Album, _a1 error) *MockAlbumStore_FindAlbumsByFamilyID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlbumStore_FindAlbumsByFamilyID_Call) RunAndReturn(run func(context.Context, int32) ([]db.Album, error)) *MockAlbumStore_FindAlbumsByFamilyID_Call {
	_c.Call.Return(run)
	return _c
}

// FindAlbumsForWrite provides a mock function with given fields: ctx, arg
func (_m *MockAlbumStore) FindAlbumsForWrite(ctx context.Context, arg db.FindAlbumsForWriteParams) ([]db.Album, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindAlbumsForWrite")
	}

	var r0 []db.Album
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.FindAlbumsForWriteParams) ([]db.Album, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.FindAlbumsForWriteParams) []db.Album); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Album)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.FindAlbumsForWriteParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlbumStore_FindAlbumsForWrite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAlbumsForWrite'
type MockAlbumStore_FindAlbumsForWrite_Call struct {
	*mock.Call
}

// FindAlbumsForWrite is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.FindAlbumsForWriteParams
func (_e *MockAlbumStore_Expecter) FindAlbumsForWrite(ctx interface{}, arg interface{}) *MockAlbumStore_FindAlbumsForWrite_Call {
	return &MockAlbumStore_FindAlbumsForWrite_Call{Call: _e.mock.On("FindAlbumsForWrite", ctx, arg)}
}

func (_c *MockAlbumStore_FindAlbumsForWrite_Call) Run(run func(ctx context.Context, arg db.FindAlbumsForWriteParams)) *MockAlbumStore_FindAlbumsForWrite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.FindAlbumsForWriteParams))
	})
	return _c
}

func (_c *MockAlbumStore_FindAlbumsForWrite_Call) Return(_a0 []db.Album, _a1 error) *MockAlbumStore_FindAlbumsForWrite_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlbumStore_FindAlbumsForWrite_Call) RunAndReturn(run func(context.Context, db.FindAlbumsForWriteParams) ([]db.Album, error)) *MockAlbumStore_FindAlbumsForWrite_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlbumsOptions provides a mock function with given fields: ctx, familyID, groupID
func (_m *MockAlbumStore) GetAlbumsOptions(ctx context.Context, familyID int32, groupID int32) ([]db.GetAlbumsOptionsRow, error) {
	ret := _m.Called(ctx, familyID, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetAlbumsOptions")
	}

	var r0 []db.GetAlbumsOptionsRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) ([]db.GetAlbumsOptionsRow, error)); ok {
		return rf(ctx, familyID, groupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) []db.GetAlbumsOptionsRow); ok {
		r0 = rf(ctx, familyID, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetAlbumsOptionsRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32) error); ok {
		r1 = rf(ctx, familyID, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlbumStore_GetAlbumsOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlbumsOptions'
type MockAlbumStore_GetAlbumsOptions_Call struct {
	*mock.Call
}

// GetAlbumsOptions is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID int32
//   - groupID int32
func (_e *MockAlbumStore_Expecter) GetAlbumsOptions(ctx interface{}, familyID interface{}, groupID interface{}) *MockAlbumStore_GetAlbumsOptions_Call {
	return &MockAlbumStore_GetAlbumsOptions_Call{Call: _e.mock.On("GetAlbumsOptions", ctx, familyID, groupID)}
}

func (_c *MockAlbumStore_GetAlbumsOptions_Call) Run(run func(ctx context.Context, familyID int32, groupID int32)) *MockAlbumStore_GetAlbumsOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *MockAlbumStore_GetAlbumsOptions_Call) Return(_a0 []db.GetAlbumsOptionsRow, _a1 error) *MockAlbumStore_GetAlbumsOptions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlbumStore_GetAlbumsOptions_Call) RunAndReturn(run func(context.Context, int32, int32) ([]db.GetAlbumsOptionsRow, error)) *MockAlbumStore_GetAlbumsOptions_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAlbum provides a mock function with given fields: ctx, arg
func (_m *MockAlbumStore) UpdateAlbum(ctx context.Context, arg db.UpdateAlbumParams) (db.Album, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAlbum")
	}

	var r0 db.Album
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateAlbumParams) (db.Album, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateAlbumParams) db.Album); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Album)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateAlbumParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlbumStore_UpdateAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAlbum'
type MockAlbumStore_UpdateAlbum_Call struct {
	*mock.Call
}

// UpdateAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateAlbumParams
func (_e *MockAlbumStore_Expecter) UpdateAlbum(ctx interface{}, arg interface{}) *MockAlbumStore_UpdateAlbum_Call {
	return &MockAlbumStore_UpdateAlbum_Call{Call: _e.mock.On("UpdateAlbum", ctx, arg)}
}

func (_c *MockAlbumStore_UpdateAlbum_Call) Run(run func(ctx context.Context, arg db.UpdateAlbumParams)) *MockAlbumStore_UpdateAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateAlbumParams))
	})
	return _c
}

func (_c *MockAlbumStore_UpdateAlbum_Call) Return(_a0 db.Album, _a1 error) *MockAlbumStore_UpdateAlbum_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlbumStore_UpdateAlbum_Call) RunAndReturn(run func(context.Context, db.UpdateAlbumParams) (db.Album, error)) *MockAlbumStore_UpdateAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAlbumStore creates a new instance of MockAlbumStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlbumStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlbumStore {
	mock := &MockAlbumStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
