// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "github.com/ywl0806/yuno_kiroku/internal/db"
)

// MockInviteTokenStore is an autogenerated mock type for the InviteTokenStore type
type MockInviteTokenStore struct {
	mock.Mock
}

type MockInviteTokenStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInviteTokenStore) EXPECT() *MockInviteTokenStore_Expecter {
	return &MockInviteTokenStore_Expecter{mock: &_m.Mock}
}

// CreateInviteToken provides a mock function with given fields: ctx, params
func (_m *MockInviteTokenStore) CreateInviteToken(ctx context.Context, params db.CreateInviteTokenParams) (db.InviteToken, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateInviteToken")
	}

	var r0 db.InviteToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateInviteTokenParams) (db.InviteToken, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateInviteTokenParams) db.InviteToken); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(db.InviteToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateInviteTokenParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInviteTokenStore_CreateInviteToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInviteToken'
type MockInviteTokenStore_CreateInviteToken_Call struct {
	*mock.Call
}

// CreateInviteToken is a helper method to define mock.On call
//   - ctx context.Context
//   - params db.CreateInviteTokenParams
func (_e *MockInviteTokenStore_Expecter) CreateInviteToken(ctx interface{}, params interface{}) *MockInviteTokenStore_CreateInviteToken_Call {
	return &MockInviteTokenStore_CreateInviteToken_Call{Call: _e.mock.On("CreateInviteToken", ctx, params)}
}

func (_c *MockInviteTokenStore_CreateInviteToken_Call) Run(run func(ctx context.Context, params db.CreateInviteTokenParams)) *MockInviteTokenStore_CreateInviteToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateInviteTokenParams))
	})
	return _c
}

func (_c *MockInviteTokenStore_CreateInviteToken_Call) Return(_a0 db.InviteToken, _a1 error) *MockInviteTokenStore_CreateInviteToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInviteTokenStore_CreateInviteToken_Call) RunAndReturn(run func(context.Context, db.CreateInviteTokenParams) (db.InviteToken, error)) *MockInviteTokenStore_CreateInviteToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetInviteTokenByToken provides a mock function with given fields: ctx, token
func (_m *MockInviteTokenStore) GetInviteTokenByToken(ctx context.Context, token string) (db.InviteToken, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetInviteTokenByToken")
	}

	var r0 db.InviteToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.InviteToken, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.InviteToken); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(db.InviteToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInviteTokenStore_GetInviteTokenByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInviteTokenByToken'
type MockInviteTokenStore_GetInviteTokenByToken_Call struct {
	*mock.Call
}

// GetInviteTokenByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockInviteTokenStore_Expecter) GetInviteTokenByToken(ctx interface{}, token interface{}) *MockInviteTokenStore_GetInviteTokenByToken_Call {
	return &MockInviteTokenStore_GetInviteTokenByToken_Call{Call: _e.mock.On("GetInviteTokenByToken", ctx, token)}
}

func (_c *MockInviteTokenStore_GetInviteTokenByToken_Call) Run(run func(ctx context.Context, token string)) *MockInviteTokenStore_GetInviteTokenByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInviteTokenStore_GetInviteTokenByToken_Call) Return(_a0 db.InviteToken, _a1 error) *MockInviteTokenStore_GetInviteTokenByToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInviteTokenStore_GetInviteTokenByToken_Call) RunAndReturn(run func(context.Context, string) (db.InviteToken, error)) *MockInviteTokenStore_GetInviteTokenByToken_Call {
	_c.Call.Return(run)
	return _c
}

// MarkInviteTokenUsed provides a mock function with given fields: ctx, token
func (_m *MockInviteTokenStore) MarkInviteTokenUsed(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for MarkInviteTokenUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInviteTokenStore_MarkInviteTokenUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkInviteTokenUsed'
type MockInviteTokenStore_MarkInviteTokenUsed_Call struct {
	*mock.Call
}

// MarkInviteTokenUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockInviteTokenStore_Expecter) MarkInviteTokenUsed(ctx interface{}, token interface{}) *MockInviteTokenStore_MarkInviteTokenUsed_Call {
	return &MockInviteTokenStore_MarkInviteTokenUsed_Call{Call: _e.mock.On("MarkInviteTokenUsed", ctx, token)}
}

func (_c *MockInviteTokenStore_MarkInviteTokenUsed_Call) Run(run func(ctx context.Context, token string)) *MockInviteTokenStore_MarkInviteTokenUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInviteTokenStore_MarkInviteTokenUsed_Call) Return(_a0 error) *MockInviteTokenStore_MarkInviteTokenUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInviteTokenStore_MarkInviteTokenUsed_Call) RunAndReturn(run func(context.Context, string) error) *MockInviteTokenStore_MarkInviteTokenUsed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInviteTokenStore creates a new instance of MockInviteTokenStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInviteTokenStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInviteTokenStore {
	mock := &MockInviteTokenStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
