// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	store "github.com/ywl0806/yuno_kiroku/internal/store"
)

// MockTransactor is an autogenerated mock type for the Transactor type
type MockTransactor struct {
	mock.Mock
}

type MockTransactor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactor) EXPECT() *MockTransactor_Expecter {
	return &MockTransactor_Expecter{mock: &_m.Mock}
}

// Transact provides a mock function with given fields: ctx, fn
func (_m *MockTransactor) Transact(ctx context.Context, fn func(store.TxStore) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Transact")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(store.TxStore) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactor_Transact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transact'
type MockTransactor_Transact_Call struct {
	*mock.Call
}

// Transact is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(store.TxStore) error
func (_e *MockTransactor_Expecter) Transact(ctx interface{}, fn interface{}) *MockTransactor_Transact_Call {
	return &MockTransactor_Transact_Call{Call: _e.mock.On("Transact", ctx, fn)}
}

func (_c *MockTransactor_Transact_Call) Run(run func(ctx context.Context, fn func(store.TxStore) error)) *MockTransactor_Transact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(store.TxStore) error))
	})
	return _c
}

func (_c *MockTransactor_Transact_Call) Return(_a0 error) *MockTransactor_Transact_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactor_Transact_Call) RunAndReturn(run func(context.Context, func(store.TxStore) error) error) *MockTransactor_Transact_Call {
	_c.Call.Return(run)
	return _c
}

// TransactWithAdvisoryLock provides a mock function with given fields: ctx, key, fn
func (_m *MockTransactor) TransactWithAdvisoryLock(ctx context.Context, key int64, fn func(store.TxStore) error) error {
	ret := _m.Called(ctx, key, fn)

	if len(ret) == 0 {
		panic("no return value specified for TransactWithAdvisoryLock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, func(store.TxStore) error) error); ok {
		r0 = rf(ctx, key, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactor_TransactWithAdvisoryLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransactWithAdvisoryLock'
type MockTransactor_TransactWithAdvisoryLock_Call struct {
	*mock.Call
}

// TransactWithAdvisoryLock is a helper method to define mock.On call
//   - ctx context.Context
//   - key int64
//   - fn func(store.TxStore) error
func (_e *MockTransactor_Expecter) TransactWithAdvisoryLock(ctx interface{}, key interface{}, fn interface{}) *MockTransactor_TransactWithAdvisoryLock_Call {
	return &MockTransactor_TransactWithAdvisoryLock_Call{Call: _e.mock.On("TransactWithAdvisoryLock", ctx, key, fn)}
}

func (_c *MockTransactor_TransactWithAdvisoryLock_Call) Run(run func(ctx context.Context, key int64, fn func(store.TxStore) error)) *MockTransactor_TransactWithAdvisoryLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(func(store.TxStore) error))
	})
	return _c
}

func (_c *MockTransactor_TransactWithAdvisoryLock_Call) Return(_a0 error) *MockTransactor_TransactWithAdvisoryLock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactor_TransactWithAdvisoryLock_Call) RunAndReturn(run func(context.Context, int64, func(store.TxStore) error) error) *MockTransactor_TransactWithAdvisoryLock_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactor creates a new instance of MockTransactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactor {
	mock := &MockTransactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
