// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "github.com/ywl0806/yuno_kiroku/internal/db"
)

// MockLikeStore is an autogenerated mock type for the LikeStore type
type MockLikeStore struct {
	mock.Mock
}

type MockLikeStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLikeStore) EXPECT() *MockLikeStore_Expecter {
	return &MockLikeStore_Expecter{mock: &_m.Mock}
}

// IsMediaItemLiked provides a mock function with given fields: ctx, arg
func (_m *MockLikeStore) IsMediaItemLiked(ctx context.Context, arg db.IsMediaItemLikedParams) (bool, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for IsMediaItemLiked")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.IsMediaItemLikedParams) (bool, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.IsMediaItemLikedParams) bool); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.IsMediaItemLikedParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLikeStore_IsMediaItemLiked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsMediaItemLiked'
type MockLikeStore_IsMediaItemLiked_Call struct {
	*mock.Call
}

// IsMediaItemLiked is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.IsMediaItemLikedParams
func (_e *MockLikeStore_Expecter) IsMediaItemLiked(ctx interface{}, arg interface{}) *MockLikeStore_IsMediaItemLiked_Call {
	return &MockLikeStore_IsMediaItemLiked_Call{Call: _e.mock.On("IsMediaItemLiked", ctx, arg)}
}

func (_c *MockLikeStore_IsMediaItemLiked_Call) Run(run func(ctx context.Context, arg db.IsMediaItemLikedParams)) *MockLikeStore_IsMediaItemLiked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.IsMediaItemLikedParams))
	})
	return _c
}

func (_c *MockLikeStore_IsMediaItemLiked_Call) Return(_a0 bool, _a1 error) *MockLikeStore_IsMediaItemLiked_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLikeStore_IsMediaItemLiked_Call) RunAndReturn(run func(context.Context, db.IsMediaItemLikedParams) (bool, error)) *MockLikeStore_IsMediaItemLiked_Call {
	_c.Call.Return(run)
	return _c
}

// LikeMediaItem provides a mock function with given fields: ctx, arg
func (_m *MockLikeStore) LikeMediaItem(ctx context.Context, arg db.LikeMediaItemParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for LikeMediaItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.LikeMediaItemParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLikeStore_LikeMediaItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LikeMediaItem'
type MockLikeStore_LikeMediaItem_Call struct {
	*mock.Call
}

// LikeMediaItem is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.LikeMediaItemParams
func (_e *MockLikeStore_Expecter) LikeMediaItem(ctx interface{}, arg interface{}) *MockLikeStore_LikeMediaItem_Call {
	return &MockLikeStore_LikeMediaItem_Call{Call: _e.mock.On("LikeMediaItem", ctx, arg)}
}

func (_c *MockLikeStore_LikeMediaItem_Call) Run(run func(ctx context.Context, arg db.LikeMediaItemParams)) *MockLikeStore_LikeMediaItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.LikeMediaItemParams))
	})
	return _c
}

func (_c *MockLikeStore_LikeMediaItem_Call) Return(_a0 error) *MockLikeStore_LikeMediaItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLikeStore_LikeMediaItem_Call) RunAndReturn(run func(context.Context, db.LikeMediaItemParams) error) *MockLikeStore_LikeMediaItem_Call {
	_c.Call.Return(run)
	return _c
}

// UnlikeMediaItem provides a mock function with given fields: ctx, arg
func (_m *MockLikeStore) UnlikeMediaItem(ctx context.Context, arg db.UnlikeMediaItemParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UnlikeMediaItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UnlikeMediaItemParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLikeStore_UnlikeMediaItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlikeMediaItem'
type MockLikeStore_UnlikeMediaItem_Call struct {
	*mock.Call
}

// UnlikeMediaItem is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UnlikeMediaItemParams
func (_e *MockLikeStore_Expecter) UnlikeMediaItem(ctx interface{}, arg interface{}) *MockLikeStore_UnlikeMediaItem_Call {
	return &MockLikeStore_UnlikeMediaItem_Call{Call: _e.mock.On("UnlikeMediaItem", ctx, arg)}
}

func (_c *MockLikeStore_UnlikeMediaItem_Call) Run(run func(ctx context.Context, arg db.UnlikeMediaItemParams)) *MockLikeStore_UnlikeMediaItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UnlikeMediaItemParams))
	})
	return _c
}

func (_c *MockLikeStore_UnlikeMediaItem_Call) Return(_a0 error) *MockLikeStore_UnlikeMediaItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLikeStore_UnlikeMediaItem_Call) RunAndReturn(run func(context.Context, db.UnlikeMediaItemParams) error) *MockLikeStore_UnlikeMediaItem_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLikeStore creates a new instance of MockLikeStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLikeStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLikeStore {
	mock := &MockLikeStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
