// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	db "github.com/ywl0806/yuno_kiroku/internal/db"
)

// MockGroupStore is an autogenerated mock type for the GroupStore type
type MockGroupStore struct {
	mock.Mock
}

type MockGroupStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupStore) EXPECT() *MockGroupStore_Expecter {
	return &MockGroupStore_Expecter{mock: &_m.Mock}
}

// CreateGroup provides a mock function with given fields: ctx, arg
func (_m *MockGroupStore) CreateGroup(ctx context.Context, arg db.CreateGroupParams) (db.Group, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroup")
	}

	var r0 db.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateGroupParams) (db.Group, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateGroupParams) db.Group); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Group)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateGroupParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupStore_CreateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroup'
type MockGroupStore_CreateGroup_Call struct {
	*mock.Call
}

// CreateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateGroupParams
func (_e *MockGroupStore_Expecter) CreateGroup(ctx interface{}, arg interface{}) *MockGroupStore_CreateGroup_Call {
	return &MockGroupStore_CreateGroup_Call{Call: _e.mock.On("CreateGroup", ctx, arg)}
}

func (_c *MockGroupStore_CreateGroup_Call) Run(run func(ctx context.Context, arg db.CreateGroupParams)) *MockGroupStore_CreateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateGroupParams))
	})
	return _c
}

func (_c *MockGroupStore_CreateGroup_Call) Return(_a0 db.Group, _a1 error) *MockGroupStore_CreateGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupStore_CreateGroup_Call) RunAndReturn(run func(context.Context, db.CreateGroupParams) (db.Group, error)) *MockGroupStore_CreateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteGroup provides a mock function with given fields: ctx, id
func (_m *MockGroupStore) DeleteGroup(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupStore_DeleteGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGroup'
type MockGroupStore_DeleteGroup_Call struct {
	*mock.Call
}

// DeleteGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockGroupStore_Expecter) DeleteGroup(ctx interface{}, id interface{}) *MockGroupStore_DeleteGroup_Call {
	return &MockGroupStore_DeleteGroup_Call{Call: _e.mock.On("DeleteGroup", ctx, id)}
}

func (_c *MockGroupStore_DeleteGroup_Call) Run(run func(ctx context.Context, id int32)) *MockGroupStore_DeleteGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockGroupStore_DeleteGroup_Call) Return(_a0 error) *MockGroupStore_DeleteGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupStore_DeleteGroup_Call) RunAndReturn(run func(context.Context, int32) error) *MockGroupStore_DeleteGroup_Call {
	_c.Call.Return(run)
	return _c
}

// FindGroupByID provides a mock function with given fields: ctx, id
func (_m *MockGroupStore) FindGroupByID(ctx context.Context, id int32) (db.FindGroupByIDRow, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindGroupByID")
	}

	var r0 db.FindGroupByIDRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (db.FindGroupByIDRow, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) db.FindGroupByIDRow); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.FindGroupByIDRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupStore_FindGroupByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindGroupByID'
type MockGroupStore_FindGroupByID_Call struct {
	*mock.Call
}

// FindGroupByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockGroupStore_Expecter) FindGroupByID(ctx interface{}, id interface{}) *MockGroupStore_FindGroupByID_Call {
	return &MockGroupStore_FindGroupByID_Call{Call: _e.mock.On("FindGroupByID", ctx, id)}
}

func (_c *MockGroupStore_FindGroupByID_Call) Run(run func(ctx context.Context, id int32)) *MockGroupStore_FindGroupByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockGroupStore_FindGroupByID_Call) Return(_a0 db.FindGroupByIDRow, _a1 error) *MockGroupStore_FindGroupByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupStore_FindGroupByID_Call) RunAndReturn(run func(context.Context, int32) (db.FindGroupByIDRow, error)) *MockGroupStore_FindGroupByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindGroupsByFamilyID provides a mock function with given fields: ctx, familyID
func (_m *MockGroupStore) FindGroupsByFamilyID(ctx context.Context, familyID int32) ([]db.Group, error) {
	ret := _m.Called(ctx, familyID)

	if len(ret) == 0 {
		panic("no return value specified for FindGroupsByFamilyID")
	}

	var r0 []db.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]db.Group, error)); ok {
		return rf(ctx, familyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []db.Group); ok {
		r0 = rf(ctx, familyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, familyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupStore_FindGroupsByFamilyID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindGroupsByFamilyID'
type MockGroupStore_FindGroupsByFamilyID_Call struct {
	*mock.Call
}

// FindGroupsByFamilyID is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID int32
func (_e *MockGroupStore_Expecter) FindGroupsByFamilyID(ctx interface{}, familyID interface{}) *MockGroupStore_FindGroupsByFamilyID_Call {
	return &MockGroupStore_FindGroupsByFamilyID_Call{Call: _e.mock.On("FindGroupsByFamilyID", ctx, familyID)}
}

func (_c *MockGroupStore_FindGroupsByFamilyID_Call) Run(run func(ctx context.Context, familyID int32)) *MockGroupStore_FindGroupsByFamilyID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockGroupStore_FindGroupsByFamilyID_Call) Return(_a0 []db.Group, _a1 error) *MockGroupStore_FindGroupsByFamilyID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupStore_FindGroupsByFamilyID_Call) RunAndReturn(run func(context.Context, int32) ([]db.Group, error)) *MockGroupStore_FindGroupsByFamilyID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGroup provides a mock function with given fields: ctx, arg
func (_m *MockGroupStore) UpdateGroup(ctx context.Context, arg db.UpdateGroupParams) (db.Group, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGroup")
	}

	var r0 db.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateGroupParams) (db.Group, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateGroupParams) db.Group); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Group)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateGroupParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupStore_UpdateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGroup'
type MockGroupStore_UpdateGroup_Call struct {
	*mock.Call
}

// UpdateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateGroupParams
func (_e *MockGroupStore_Expecter) UpdateGroup(ctx interface{}, arg interface{}) *MockGroupStore_UpdateGroup_Call {
	return &MockGroupStore_UpdateGroup_Call{Call: _e.mock.On("UpdateGroup", ctx, arg)}
}

func (_c *MockGroupStore_UpdateGroup_Call) Run(run func(ctx context.Context, arg db.UpdateGroupParams)) *MockGroupStore_UpdateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateGroupParams))
	})
	return _c
}

func (_c *MockGroupStore_UpdateGroup_Call) Return(_a0 db.Group, _a1 error) *MockGroupStore_UpdateGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupStore_UpdateGroup_Call) RunAndReturn(run func(context.Context, db.UpdateGroupParams) (db.Group, error)) *MockGroupStore_UpdateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGroupStore creates a new instance of MockGroupStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupStore {
	mock := &MockGroupStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
