FROM openjdk:slim

RUN set -ex \
    && apt-get update
#     # && apt-get install -y curl \
#     # && curl -sL https://deb.nodesource.com/setup_18.x | bash \
#     # && apt-get install -y nodejs \
#     # && npm install -g firebase-tools@12.2.1

RUN apt-get install -y curl git
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
RUN . $HOME/.nvm/nvm.sh && \
    nvm install 18.17.0 && \
    nvm use 18.17.0 && \
    npm install -g firebase-tools@12.2.1

WORKDIR /app
