// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: albums.sql

package db

import (
	"context"
)

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO
    albums (family_id, name, is_common)
VALUES
    ($1, $2, $3)
RETURNING
    id, family_id, name, is_common, created_at, updated_at
`

type CreateAlbumParams struct {
	FamilyID string
	Name     string
	IsCommon bool
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	row := q.db.QueryRowContext(ctx, createAlbum, arg.FamilyID, arg.Name, arg.IsCommon)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.IsCommon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAlbum = `-- name: DeleteAlbum :exec
DELETE FROM albums
WHERE
    id = $1
`

func (q *Queries) DeleteAlbum(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAlbum, id)
	return err
}

const findAlbumByIDAndFamilyID = `-- name: FindAlbumByIDAndFamilyID :one
SELECT
    id, family_id, name, is_common, created_at, updated_at
FROM
    albums
WHERE
    id = $1
    AND family_id = $2
`

type FindAlbumByIDAndFamilyIDParams struct {
	ID       string
	FamilyID string
}

func (q *Queries) FindAlbumByIDAndFamilyID(ctx context.Context, arg FindAlbumByIDAndFamilyIDParams) (Album, error) {
	row := q.db.QueryRowContext(ctx, findAlbumByIDAndFamilyID, arg.ID, arg.FamilyID)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.IsCommon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findAlbumsByFamilyID = `-- name: FindAlbumsByFamilyID :many
SELECT
    id, family_id, name, is_common, created_at, updated_at
FROM
    albums
WHERE
    family_id = $1
ORDER BY
    id
`

func (q *Queries) FindAlbumsByFamilyID(ctx context.Context, familyID string) ([]Album, error) {
	rows, err := q.db.QueryContext(ctx, findAlbumsByFamilyID, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Name,
			&i.IsCommon,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAlbumsForWrite = `-- name: FindAlbumsForWrite :many
SELECT
    a.id, a.family_id, a.name, a.is_common, a.created_at, a.updated_at
FROM
    albums as a
    INNER JOIN album_groups_permissions as agp on a.id = agp.album_id
    INNER JOIN groups as g on agp.group_id = g.id
WHERE
    a.family_id = $1::uuid
    AND g.id = $2::int
    AND agp.permission = 'W'
UNION
SELECT
    a.id, a.family_id, a.name, a.is_common, a.created_at, a.updated_at
FROM
    albums as a
WHERE
    a.family_id = $1::uuid
    AND a.is_common = TRUE
ORDER BY
    id
`

type FindAlbumsForWriteParams struct {
	FamilyID string
	GroupID  int32
}

func (q *Queries) FindAlbumsForWrite(ctx context.Context, arg FindAlbumsForWriteParams) ([]Album, error) {
	rows, err := q.db.QueryContext(ctx, findAlbumsForWrite, arg.FamilyID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Name,
			&i.IsCommon,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlbumsOptions = `-- name: GetAlbumsOptions :many
SELECT
    a.id,
    a.name,
    a.is_common
FROM
    albums as a
    INNER JOIN album_groups_permissions as agp on a.id = agp.album_id
    INNER JOIN groups as g on agp.group_id = g.id
WHERE
    a.family_id = $1::uuid
    AND g.id = $2::int
    AND agp.permission = 'R'
UNION
SELECT
    a.id,
    a.name,
    a.is_common
FROM
    albums as a
WHERE
    a.family_id = $1::uuid
    AND a.is_common = TRUE
ORDER BY
    id
`

type GetAlbumsOptionsParams struct {
	FamilyID string
	GroupID  int32
}

type GetAlbumsOptionsRow struct {
	ID       string
	Name     string
	IsCommon bool
}

func (q *Queries) GetAlbumsOptions(ctx context.Context, arg GetAlbumsOptionsParams) ([]GetAlbumsOptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAlbumsOptions, arg.FamilyID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAlbumsOptionsRow
	for rows.Next() {
		var i GetAlbumsOptionsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.IsCommon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlbum = `-- name: UpdateAlbum :one
UPDATE albums
SET
    name = $1,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $2
RETURNING
    id, family_id, name, is_common, created_at, updated_at
`

type UpdateAlbumParams struct {
	Name string
	ID   string
}

func (q *Queries) UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) (Album, error) {
	row := q.db.QueryRowContext(ctx, updateAlbum, arg.Name, arg.ID)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.IsCommon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
