// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: album_groups_permissions.sql

package db

import (
	"context"
)

const deleteAlbumGroupPermissionsByAlbumID = `-- name: DeleteAlbumGroupPermissionsByAlbumID :exec
DELETE FROM album_groups_permissions
WHERE
    album_id = $1
`

func (q *Queries) DeleteAlbumGroupPermissionsByAlbumID(ctx context.Context, albumID string) error {
	_, err := q.db.ExecContext(ctx, deleteAlbumGroupPermissionsByAlbumID, albumID)
	return err
}

const getAlbumGroupPermissions = `-- name: GetAlbumGroupPermissions :many
SELECT
    agp.album_id, agp.group_id, agp.permission, agp.created_at, agp.updated_at
FROM
    album_groups_permissions as agp
    INNER JOIN albums as a on agp.album_id = a.id AND a.family_id = $2
WHERE
    agp.album_id = $1
`

type GetAlbumGroupPermissionsParams struct {
	AlbumID  string
	FamilyID string
}

func (q *Queries) GetAlbumGroupPermissions(ctx context.Context, arg GetAlbumGroupPermissionsParams) ([]AlbumGroupsPermission, error) {
	rows, err := q.db.QueryContext(ctx, getAlbumGroupPermissions, arg.AlbumID, arg.FamilyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlbumGroupsPermission
	for rows.Next() {
		var i AlbumGroupsPermission
		if err := rows.Scan(
			&i.AlbumID,
			&i.GroupID,
			&i.Permission,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAlbumGroupPermission = `-- name: InsertAlbumGroupPermission :exec
INSERT INTO
    album_groups_permissions (album_id, group_id, permission)
VALUES
    ($1, $2, $3) ON CONFLICT (album_id, group_id, permission) DO NOTHING
`

type InsertAlbumGroupPermissionParams struct {
	AlbumID    string
	GroupID    int32
	Permission string
}

func (q *Queries) InsertAlbumGroupPermission(ctx context.Context, arg InsertAlbumGroupPermissionParams) error {
	_, err := q.db.ExecContext(ctx, insertAlbumGroupPermission, arg.AlbumID, arg.GroupID, arg.Permission)
	return err
}
