// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: faces.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createFaceDetection = `-- name: CreateFaceDetection :one
INSERT INTO
    face_detections (
        photo_id,
        identity_id,
        location_top,
        location_right,
        location_bottom,
        location_left,
        embedding
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    id, photo_id, identity_id, location_top, location_right, location_bottom, location_left, embedding, created_at, updated_at
`

type CreateFaceDetectionParams struct {
	PhotoID        int32
	IdentityID     int32
	LocationTop    int32
	LocationRight  int32
	LocationBottom int32
	LocationLeft   int32
	Embedding      interface{}
}

func (q *Queries) CreateFaceDetection(ctx context.Context, arg CreateFaceDetectionParams) (FaceDetection, error) {
	row := q.db.QueryRowContext(ctx, createFaceDetection,
		arg.PhotoID,
		arg.IdentityID,
		arg.LocationTop,
		arg.LocationRight,
		arg.LocationBottom,
		arg.LocationLeft,
		arg.Embedding,
	)
	var i FaceDetection
	err := row.Scan(
		&i.ID,
		&i.PhotoID,
		&i.IdentityID,
		&i.LocationTop,
		&i.LocationRight,
		&i.LocationBottom,
		&i.LocationLeft,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findMostSimilarFace = `-- name: FindMostSimilarFace :one
SELECT
    ave.identity_id,
    p.name,
    p.group_id,
    ave.embedding <=> $1::vector AS distance
FROM
    average_face_embeddings AS ave
    INNER JOIN identities AS p ON ave.identity_id = p.id
WHERE
    p.group_id = $2::int
    AND ave.embedding <=> $1::vector < $3::float
ORDER BY
    ave.embedding <=> $1::vector ASC
LIMIT
    1
`

type FindMostSimilarFaceParams struct {
	Embedding           interface{}
	GroupID             int32
	SimilarityThreshold float64
}

type FindMostSimilarFaceRow struct {
	IdentityID int32
	Name       sql.NullString
	GroupID    int32
	Distance   interface{}
}

func (q *Queries) FindMostSimilarFace(ctx context.Context, arg FindMostSimilarFaceParams) (FindMostSimilarFaceRow, error) {
	row := q.db.QueryRowContext(ctx, findMostSimilarFace, arg.Embedding, arg.GroupID, arg.SimilarityThreshold)
	var i FindMostSimilarFaceRow
	err := row.Scan(
		&i.IdentityID,
		&i.Name,
		&i.GroupID,
		&i.Distance,
	)
	return i, err
}

const getFaceDetectionsByEmbeddings = `-- name: GetFaceDetectionsByEmbeddings :one
SELECT
    fd.embedding
FROM
    face_detections AS fd
    JOIN photos AS p ON fd.photo_id = p.id
WHERE
    p.group_id = $1::int
    AND p.album_id = $2::int
    AND fd.embedding = ANY($3::vector[])
`

type GetFaceDetectionsByEmbeddingsParams struct {
	GroupID    int32
	AlbumID    int32
	Embeddings []interface{}
}

func (q *Queries) GetFaceDetectionsByEmbeddings(ctx context.Context, arg GetFaceDetectionsByEmbeddingsParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getFaceDetectionsByEmbeddings, arg.GroupID, arg.AlbumID, pq.Array(arg.Embeddings))
	var embedding interface{}
	err := row.Scan(&embedding)
	return embedding, err
}

const getFaceDetectionsByPhotoId = `-- name: GetFaceDetectionsByPhotoId :many
SELECT
    fd.id,
    fd.photo_id,
    fd.identity_id,
    p.name,
    fd.location_top,
    fd.location_right,
    fd.location_bottom,
    fd.location_left,
    fd.embedding
FROM
    face_detections AS fd
    JOIN identities AS p ON fd.identity_id = p.id
WHERE
    fd.photo_id = $1
`

type GetFaceDetectionsByPhotoIdRow struct {
	ID             int32
	PhotoID        int32
	IdentityID     int32
	Name           sql.NullString
	LocationTop    int32
	LocationRight  int32
	LocationBottom int32
	LocationLeft   int32
	Embedding      interface{}
}

func (q *Queries) GetFaceDetectionsByPhotoId(ctx context.Context, photoID int32) ([]GetFaceDetectionsByPhotoIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getFaceDetectionsByPhotoId, photoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFaceDetectionsByPhotoIdRow
	for rows.Next() {
		var i GetFaceDetectionsByPhotoIdRow
		if err := rows.Scan(
			&i.ID,
			&i.PhotoID,
			&i.IdentityID,
			&i.Name,
			&i.LocationTop,
			&i.LocationRight,
			&i.LocationBottom,
			&i.LocationLeft,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
