// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db

import (
	"context"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO
    groups (name)
VALUES
    ($1)
RETURNING
    id, name, created_at, updated_at
`

func (q *Queries) CreateGroup(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findGroupByID = `-- name: FindGroupByID :one
SELECT
    id,
    name
FROM
    groups
WHERE
    id = $1
`

type FindGroupByIDRow struct {
	ID   int32
	Name string
}

func (q *Queries) FindGroupByID(ctx context.Context, id int32) (FindGroupByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findGroupByID, id)
	var i FindGroupByIDRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
