// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identities.sql

package db

import (
	"context"
)

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO
    identities (family_id)
VALUES
    ($1)
RETURNING
    id, family_id, created_at, updated_at
`

func (q *Queries) CreateIdentity(ctx context.Context, familyID int32) (Identity, error) {
	row := q.db.QueryRowContext(ctx, createIdentity, familyID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findIdentitiesByFamilyId = `-- name: FindIdentitiesByFamilyId :many
SELECT
    id, family_id, created_at, updated_at
FROM
    identities
WHERE
    family_id = $1::int
`

func (q *Queries) FindIdentitiesByFamilyId(ctx context.Context, familyID int32) ([]Identity, error) {
	rows, err := q.db.QueryContext(ctx, findIdentitiesByFamilyId, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Identity
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findIdentityByIdAndFamilyId = `-- name: FindIdentityByIdAndFamilyId :one
SELECT
    id, family_id, created_at, updated_at
FROM
    identities
WHERE
    id = $1::int
    AND family_id = $2::int
`

type FindIdentityByIdAndFamilyIdParams struct {
	ID       int32
	FamilyID int32
}

func (q *Queries) FindIdentityByIdAndFamilyId(ctx context.Context, arg FindIdentityByIdAndFamilyIdParams) (Identity, error) {
	row := q.db.QueryRowContext(ctx, findIdentityByIdAndFamilyId, arg.ID, arg.FamilyID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
