// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identity_face_imgs.sql

package db

import (
	"context"
)

const createIdentityFaceImg = `-- name: CreateIdentityFaceImg :one
INSERT INTO
    identity_face_imgs (identity_id, media_item_id, storage_key)
VALUES
    ($1, $2, $3)
RETURNING
    id, identity_id, media_item_id, storage_key, created_at, updated_at
`

type CreateIdentityFaceImgParams struct {
	IdentityID  int32
	MediaItemID int32
	StorageKey  string
}

func (q *Queries) CreateIdentityFaceImg(ctx context.Context, arg CreateIdentityFaceImgParams) (IdentityFaceImg, error) {
	row := q.db.QueryRowContext(ctx, createIdentityFaceImg, arg.IdentityID, arg.MediaItemID, arg.StorageKey)
	var i IdentityFaceImg
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.MediaItemID,
		&i.StorageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasIdentityFaceImg = `-- name: HasIdentityFaceImg :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            identity_face_imgs
        WHERE
            identity_id = $1
    ) AS exists
`

func (q *Queries) HasIdentityFaceImg(ctx context.Context, identityID int32) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasIdentityFaceImg, identityID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
