// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identities.sql

package db

import (
	"context"
	"database/sql"
)

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO
    identities (family_id)
VALUES
    ($1)
RETURNING
    id, family_id, created_at, updated_at
`

func (q *Queries) CreateIdentity(ctx context.Context, familyID int32) (Identity, error) {
	row := q.db.QueryRowContext(ctx, createIdentity, familyID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findIdentitiesByFamilyId = `-- name: FindIdentitiesByFamilyId :many
SELECT
    id, family_id, created_at, updated_at
FROM
    identities
WHERE
    family_id = $1::int
`

func (q *Queries) FindIdentitiesByFamilyId(ctx context.Context, familyID int32) ([]Identity, error) {
	rows, err := q.db.QueryContext(ctx, findIdentitiesByFamilyId, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Identity
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findIdentityByIdAndFamilyId = `-- name: FindIdentityByIdAndFamilyId :one
SELECT
    id, family_id, created_at, updated_at
FROM
    identities
WHERE
    id = $1::int
    AND family_id = $2::int
`

type FindIdentityByIdAndFamilyIdParams struct {
	ID       int32
	FamilyID int32
}

func (q *Queries) FindIdentityByIdAndFamilyId(ctx context.Context, arg FindIdentityByIdAndFamilyIdParams) (Identity, error) {
	row := q.db.QueryRowContext(ctx, findIdentityByIdAndFamilyId, arg.ID, arg.FamilyID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentityOptions = `-- name: GetIdentityOptions :many
SELECT DISTINCT ON (i.id)
    i.id, 
    k.id AS kid_id,
    k.name AS kid_name,
    u.id AS user_id,
    u.name AS user_name,
    ifi.storage_key
FROM 
    identities AS i
    LEFT JOIN kids AS k ON i.id = k.identity_id
    LEFT JOIN users AS u ON i.id = u.identity_id
    LEFT JOIN identity_face_imgs AS ifi ON i.id = ifi.identity_id
    JOIN media_items AS mi ON ifi.media_item_id = mi.id
WHERE 
    i.family_id = $1
ORDER BY 
    i.id,
    mi.taken_at DESC
`

type GetIdentityOptionsRow struct {
	ID         int32
	KidID      sql.NullInt32
	KidName    sql.NullString
	UserID     sql.NullInt32
	UserName   sql.NullString
	StorageKey sql.NullString
}

func (q *Queries) GetIdentityOptions(ctx context.Context, familyID int32) ([]GetIdentityOptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getIdentityOptions, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIdentityOptionsRow
	for rows.Next() {
		var i GetIdentityOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.KidID,
			&i.KidName,
			&i.UserID,
			&i.UserName,
			&i.StorageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
