// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invite_tokens.sql

package db

import (
	"context"
	"time"
)

const createInviteToken = `-- name: CreateInviteToken :one
INSERT INTO
    invite_tokens (token, group_id, clan_group_id, created_by_user_id, expires_at)
VALUES
    ($1, $2, $3, $4, $5)
RETURNING
    id, token, group_id, clan_group_id, created_by_user_id, expires_at, used_at, created_at
`

type CreateInviteTokenParams struct {
	Token           string
	GroupID         int32
	ClanGroupID     int32
	CreatedByUserID int32
	ExpiresAt       time.Time
}

func (q *Queries) CreateInviteToken(ctx context.Context, arg CreateInviteTokenParams) (InviteToken, error) {
	row := q.db.QueryRowContext(ctx, createInviteToken,
		arg.Token,
		arg.GroupID,
		arg.ClanGroupID,
		arg.CreatedByUserID,
		arg.ExpiresAt,
	)
	var i InviteToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.GroupID,
		&i.ClanGroupID,
		&i.CreatedByUserID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteTokenByToken = `-- name: GetInviteTokenByToken :one
SELECT
    id, token, group_id, clan_group_id, created_by_user_id, expires_at, used_at, created_at
FROM
    invite_tokens
WHERE
    token = $1
    AND (used_at IS NULL)
    AND (expires_at > NOW())
`

func (q *Queries) GetInviteTokenByToken(ctx context.Context, token string) (InviteToken, error) {
	row := q.db.QueryRowContext(ctx, getInviteTokenByToken, token)
	var i InviteToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.GroupID,
		&i.ClanGroupID,
		&i.CreatedByUserID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markInviteTokenUsed = `-- name: MarkInviteTokenUsed :exec
UPDATE
    invite_tokens
SET
    used_at = NOW()
WHERE
    token = $1
`

func (q *Queries) MarkInviteTokenUsed(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, markInviteTokenUsed, token)
	return err
}
