// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kids.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createKid = `-- name: CreateKid :one
INSERT INTO kids (name, birth_date, identity_id, family_id) VALUES ($1, $2, $3, $4) RETURNING id, name, birth_date, identity_id, family_id, created_at, updated_at
`

type CreateKidParams struct {
	Name       sql.NullString
	BirthDate  sql.NullTime
	IdentityID sql.NullInt32
	FamilyID   int32
}

func (q *Queries) CreateKid(ctx context.Context, arg CreateKidParams) (Kid, error) {
	row := q.db.QueryRowContext(ctx, createKid,
		arg.Name,
		arg.BirthDate,
		arg.IdentityID,
		arg.FamilyID,
	)
	var i Kid
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BirthDate,
		&i.IdentityID,
		&i.FamilyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteKid = `-- name: DeleteKid :exec
DELETE FROM kids WHERE id = $1
`

func (q *Queries) DeleteKid(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteKid, id)
	return err
}

const findKidsByFamilyID = `-- name: FindKidsByFamilyID :many
SELECT id, name, birth_date, identity_id, family_id, created_at, updated_at FROM kids WHERE family_id = $1 ORDER BY id
`

func (q *Queries) FindKidsByFamilyID(ctx context.Context, familyID int32) ([]Kid, error) {
	rows, err := q.db.QueryContext(ctx, findKidsByFamilyID, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Kid
	for rows.Next() {
		var i Kid
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BirthDate,
			&i.IdentityID,
			&i.FamilyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKidByID = `-- name: GetKidByID :one
SELECT id, name, birth_date, identity_id, family_id, created_at, updated_at FROM kids WHERE id = $1
`

func (q *Queries) GetKidByID(ctx context.Context, id int32) (Kid, error) {
	row := q.db.QueryRowContext(ctx, getKidByID, id)
	var i Kid
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BirthDate,
		&i.IdentityID,
		&i.FamilyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKidsWithRandomFaceImg = `-- name: GetKidsWithRandomFaceImg :many
SELECT DISTINCT ON (k.id)
    k.id,
    k.name,
    k.birth_date,
    k.identity_id,
    k.family_id,
    ifi.media_item_id,
    ifi.storage_key,
    mi.taken_at
FROM kids AS k 
JOIN identity_face_imgs AS ifi ON k.identity_id = ifi.identity_id
JOIN media_items AS mi ON ifi.media_item_id = mi.id
WHERE k.family_id = $1
    AND CASE WHEN $2::timestamp IS NOT NULL THEN
        mi.taken_at <= $2::timestamp
        ELSE TRUE
    END
    AND CASE WHEN $3::timestamp IS NOT NULL THEN
        mi.taken_at >= $3::timestamp
        ELSE TRUE
    END
ORDER BY k.id, RANDOM()
`

type GetKidsWithRandomFaceImgParams struct {
	FamilyID    int32
	TakenAtTo   sql.NullTime
	TakenAtFrom sql.NullTime
}

type GetKidsWithRandomFaceImgRow struct {
	ID          int32
	Name        sql.NullString
	BirthDate   sql.NullTime
	IdentityID  sql.NullInt32
	FamilyID    int32
	MediaItemID int32
	StorageKey  string
	TakenAt     time.Time
}

func (q *Queries) GetKidsWithRandomFaceImg(ctx context.Context, arg GetKidsWithRandomFaceImgParams) ([]GetKidsWithRandomFaceImgRow, error) {
	rows, err := q.db.QueryContext(ctx, getKidsWithRandomFaceImg, arg.FamilyID, arg.TakenAtTo, arg.TakenAtFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetKidsWithRandomFaceImgRow
	for rows.Next() {
		var i GetKidsWithRandomFaceImgRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BirthDate,
			&i.IdentityID,
			&i.FamilyID,
			&i.MediaItemID,
			&i.StorageKey,
			&i.TakenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKid = `-- name: UpdateKid :one
UPDATE kids SET name = $2, birth_date = $3, identity_id = $4 WHERE id = $1 RETURNING id, name, birth_date, identity_id, family_id, created_at, updated_at
`

type UpdateKidParams struct {
	ID         int32
	Name       sql.NullString
	BirthDate  sql.NullTime
	IdentityID sql.NullInt32
}

func (q *Queries) UpdateKid(ctx context.Context, arg UpdateKidParams) (Kid, error) {
	row := q.db.QueryRowContext(ctx, updateKid,
		arg.ID,
		arg.Name,
		arg.BirthDate,
		arg.IdentityID,
	)
	var i Kid
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BirthDate,
		&i.IdentityID,
		&i.FamilyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
