// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kids.sql

package db

import (
	"context"
)

const findKidsByFamilyID = `-- name: FindKidsByFamilyID :many
SELECT id, name, birth_date, identity_id, family_id, created_at, updated_at FROM kids WHERE family_id = $1 ORDER BY id
`

func (q *Queries) FindKidsByFamilyID(ctx context.Context, familyID int32) ([]Kid, error) {
	rows, err := q.db.QueryContext(ctx, findKidsByFamilyID, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Kid
	for rows.Next() {
		var i Kid
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BirthDate,
			&i.IdentityID,
			&i.FamilyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
