// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: likes.sql

package db

import (
	"context"
)

const isMediaItemLiked = `-- name: IsMediaItemLiked :one
SELECT EXISTS(
    SELECT 1 FROM media_item_likes
    WHERE media_item_id = $1 AND user_id = $2
) AS is_liked
`

type IsMediaItemLikedParams struct {
	MediaItemID int32
	UserID      int32
}

func (q *Queries) IsMediaItemLiked(ctx context.Context, arg IsMediaItemLikedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isMediaItemLiked, arg.MediaItemID, arg.UserID)
	var is_liked bool
	err := row.Scan(&is_liked)
	return is_liked, err
}

const likeMediaItem = `-- name: LikeMediaItem :exec
INSERT INTO media_item_likes (media_item_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LikeMediaItemParams struct {
	MediaItemID int32
	UserID      int32
}

func (q *Queries) LikeMediaItem(ctx context.Context, arg LikeMediaItemParams) error {
	_, err := q.db.ExecContext(ctx, likeMediaItem, arg.MediaItemID, arg.UserID)
	return err
}

const unlikeMediaItem = `-- name: UnlikeMediaItem :exec
DELETE FROM media_item_likes
WHERE media_item_id = $1 AND user_id = $2
`

type UnlikeMediaItemParams struct {
	MediaItemID int32
	UserID      int32
}

func (q *Queries) UnlikeMediaItem(ctx context.Context, arg UnlikeMediaItemParams) error {
	_, err := q.db.ExecContext(ctx, unlikeMediaItem, arg.MediaItemID, arg.UserID)
	return err
}
