// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mediaItems.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const createMediaItem = `-- name: CreateMediaItem :one
INSERT INTO
    media_items (
        group_id,
        album_id,
        taken_at,
        file_name
    )
VALUES
    ($1, $2, $3, $4)
RETURNING
    id,
    group_id,
    album_id,
    taken_at,
    file_name,
    created_at,
    updated_at
`

type CreateMediaItemParams struct {
	GroupID  int32
	AlbumID  int32
	TakenAt  time.Time
	FileName sql.NullString
}

func (q *Queries) CreateMediaItem(ctx context.Context, arg CreateMediaItemParams) (MediaItem, error) {
	row := q.db.QueryRowContext(ctx, createMediaItem,
		arg.GroupID,
		arg.AlbumID,
		arg.TakenAt,
		arg.FileName,
	)
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.AlbumID,
		&i.TakenAt,
		&i.FileName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaItemByFaceDetection = `-- name: GetMediaItemByFaceDetection :one

SELECT
    mi.id, mi.group_id, mi.album_id, mi.taken_at, mi.file_name, mi.created_at, mi.updated_at
FROM
    media_items AS mi
    INNER JOIN face_detections AS fd ON mi.id = fd.media_item_id
WHERE
    mi.group_id = $1::int
    AND fd.embedding = ANY($2::vector[])
GROUP BY
    mi.id
LIMIT 1
`

type GetMediaItemByFaceDetectionParams struct {
	GroupID    int32
	Embeddings []interface{}
}

// -- name: GetIdentityRandomPhoto :one
// SELECT
//
//	p.*,
//	fd.location_top,
//	fd.location_right,
//	fd.location_bottom,
//	fd.location_left
//
// FROM
//
//	(
//	    SELECT photo_id, location_top, location_right, location_bottom, location_left
//	    FROM face_detections
//	    WHERE identity_id = sqlc.arg(identity_id)::int
//	    ORDER BY RANDOM()
//	    LIMIT 1
//	) AS fd
//	INNER JOIN photos AS p ON fd.photo_id = p.id
//	INNER JOIN albums AS a ON p.album_id = a.id
//	INNER JOIN album_clan_groups_permissions AS acgp ON a.id = acgp.album_id
//
// WHERE
//
//	acgp.clan_group_id = sqlc.arg (clan_group_id)::int
//	AND acgp.permission = 'R';
func (q *Queries) GetMediaItemByFaceDetection(ctx context.Context, arg GetMediaItemByFaceDetectionParams) (MediaItem, error) {
	row := q.db.QueryRowContext(ctx, getMediaItemByFaceDetection, arg.GroupID, pq.Array(arg.Embeddings))
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.AlbumID,
		&i.TakenAt,
		&i.FileName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaItemRange = `-- name: GetMediaItemRange :many
SELECT
    EXTRACT(
        YEAR
        FROM
            taken_at
    ) AS year,
    EXTRACT(
        MONTH
        FROM
            taken_at
    ) AS month
FROM
    media_items AS mi
    INNER JOIN albums AS a ON mi.album_id = a.id
    INNER JOIN album_clan_groups_permissions AS acgp ON a.id = acgp.album_id
WHERE
    acgp.clan_group_id = $1::int
    AND acgp.permission = 'R'
GROUP BY
    year,
    month
ORDER BY
    year DESC,
    month DESC
`

type GetMediaItemRangeRow struct {
	Year  string
	Month string
}

func (q *Queries) GetMediaItemRange(ctx context.Context, clanGroupID int32) ([]GetMediaItemRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getMediaItemRange, clanGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMediaItemRangeRow
	for rows.Next() {
		var i GetMediaItemRangeRow
		if err := rows.Scan(&i.Year, &i.Month); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMediaItemsByTakenAt = `-- name: GetMediaItemsByTakenAt :many
SELECT
    mi.id, mi.group_id, mi.album_id, mi.taken_at, mi.file_name, mi.created_at, mi.updated_at,
    original_media_file.storage_key AS original_storage_key,
    thumbnail_media_file.storage_key AS thumbnail_storage_key,
    original_media_file.width AS original_width,
    original_media_file.height AS original_height,
    thumbnail_media_file.width AS thumbnail_width,
    thumbnail_media_file.height AS thumbnail_height
FROM
    media_items AS mi
    INNER JOIN albums AS a ON mi.album_id = a.id
    INNER JOIN album_clan_groups_permissions AS acgp ON a.id = acgp.album_id
    LEFT JOIN LATERAL (
        SELECT storage_key, width, height 
        FROM media_files 
        WHERE media_item_id = mi.id AND role = 'original' 
        LIMIT 1
    ) AS original_media_file ON true
    LEFT JOIN LATERAL (
        SELECT storage_key, width, height 
        FROM media_files 
        WHERE media_item_id = mi.id AND role = 'thumbnail' 
        LIMIT 1
    ) AS thumbnail_media_file ON true
WHERE
    acgp.clan_group_id = $1::int
    AND acgp.permission = 'R'
    AND mi.taken_at >= $2::timestamp
    AND mi.taken_at <= $3::timestamp
ORDER BY
    mi.taken_at DESC
`

type GetMediaItemsByTakenAtParams struct {
	ClanGroupID int32
	TakenAtFrom time.Time
	TakenAtTo   time.Time
}

type GetMediaItemsByTakenAtRow struct {
	ID                  int32
	GroupID             int32
	AlbumID             int32
	TakenAt             time.Time
	FileName            sql.NullString
	CreatedAt           time.Time
	UpdatedAt           time.Time
	OriginalStorageKey  string
	ThumbnailStorageKey string
	OriginalWidth       sql.NullInt32
	OriginalHeight      sql.NullInt32
	ThumbnailWidth      sql.NullInt32
	ThumbnailHeight     sql.NullInt32
}

func (q *Queries) GetMediaItemsByTakenAt(ctx context.Context, arg GetMediaItemsByTakenAtParams) ([]GetMediaItemsByTakenAtRow, error) {
	rows, err := q.db.QueryContext(ctx, getMediaItemsByTakenAt, arg.ClanGroupID, arg.TakenAtFrom, arg.TakenAtTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMediaItemsByTakenAtRow
	for rows.Next() {
		var i GetMediaItemsByTakenAtRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.AlbumID,
			&i.TakenAt,
			&i.FileName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OriginalStorageKey,
			&i.ThumbnailStorageKey,
			&i.OriginalWidth,
			&i.OriginalHeight,
			&i.ThumbnailWidth,
			&i.ThumbnailHeight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
