// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media_file.sql

package db

import (
	"context"
	"database/sql"
)

const createMediaFile = `-- name: CreateMediaFile :one
INSERT INTO
    media_files (
        media_item_id,
        role,
        storage_key,
        width,
        height
    )
VALUES
    ($1, $2, $3, $4, $5)
RETURNING
    id,
    media_item_id,
    role,
    storage_key,
    width,
    height,
    created_at,
    updated_at
`

type CreateMediaFileParams struct {
	MediaItemID string
	Role        string
	StorageKey  string
	Width       sql.NullInt32
	Height      sql.NullInt32
}

func (q *Queries) CreateMediaFile(ctx context.Context, arg CreateMediaFileParams) (MediaFile, error) {
	row := q.db.QueryRowContext(ctx, createMediaFile,
		arg.MediaItemID,
		arg.Role,
		arg.StorageKey,
		arg.Width,
		arg.Height,
	)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.MediaItemID,
		&i.Role,
		&i.StorageKey,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
