// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media_file.sql

package db

import (
	"context"
	"database/sql"
)

const createMediaFile = `-- name: CreateMediaFile :one
INSERT INTO
    media_files (
        media_item_id,
        role,
        storage_key,
        mime_type,
        width,
        height,
        file_size
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    id,
    media_item_id,
    role,
    storage_key,
    mime_type,
    width,
    height,
    file_size,
    created_at,
    updated_at
`

type CreateMediaFileParams struct {
	MediaItemID int32
	Role        string
	StorageKey  string
	MimeType    sql.NullString
	Width       sql.NullInt32
	Height      sql.NullInt32
	FileSize    sql.NullInt64
}

func (q *Queries) CreateMediaFile(ctx context.Context, arg CreateMediaFileParams) (MediaFile, error) {
	row := q.db.QueryRowContext(ctx, createMediaFile,
		arg.MediaItemID,
		arg.Role,
		arg.StorageKey,
		arg.MimeType,
		arg.Width,
		arg.Height,
		arg.FileSize,
	)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.MediaItemID,
		&i.Role,
		&i.StorageKey,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.FileSize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
