// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media_items.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const createMediaItem = `-- name: CreateMediaItem :one
INSERT INTO
    media_items (
        family_id,
        album_id,
        upload_batch_id,
        taken_at,
        file_name,
        taken_location_latitude,
        taken_location_longitude
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    id,
    family_id,
    album_id,
    upload_batch_id,
    upload_status,
    taken_location_latitude,
    taken_location_longitude,
    taken_at,
    file_name,
    created_at,
    updated_at
`

type CreateMediaItemParams struct {
	FamilyID               int32
	AlbumID                int32
	UploadBatchID          int32
	TakenAt                time.Time
	FileName               sql.NullString
	TakenLocationLatitude  sql.NullFloat64
	TakenLocationLongitude sql.NullFloat64
}

func (q *Queries) CreateMediaItem(ctx context.Context, arg CreateMediaItemParams) (MediaItem, error) {
	row := q.db.QueryRowContext(ctx, createMediaItem,
		arg.FamilyID,
		arg.AlbumID,
		arg.UploadBatchID,
		arg.TakenAt,
		arg.FileName,
		arg.TakenLocationLatitude,
		arg.TakenLocationLongitude,
	)
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.AlbumID,
		&i.UploadBatchID,
		&i.UploadStatus,
		&i.TakenLocationLatitude,
		&i.TakenLocationLongitude,
		&i.TakenAt,
		&i.FileName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaItemByFaceDetection = `-- name: GetMediaItemByFaceDetection :one
SELECT
    mi.id, mi.family_id, mi.album_id, mi.upload_batch_id, mi.upload_status, mi.taken_location_latitude, mi.taken_location_longitude, mi.taken_at, mi.file_name, mi.created_at, mi.updated_at
FROM
    media_items AS mi
    INNER JOIN face_detections AS fd ON mi.id = fd.media_item_id
WHERE
    mi.family_id = $1::int
    AND fd.embedding = ANY($2::vector[])
GROUP BY
    mi.id
LIMIT 1
`

type GetMediaItemByFaceDetectionParams struct {
	FamilyID   int32
	Embeddings []interface{}
}

func (q *Queries) GetMediaItemByFaceDetection(ctx context.Context, arg GetMediaItemByFaceDetectionParams) (MediaItem, error) {
	row := q.db.QueryRowContext(ctx, getMediaItemByFaceDetection, arg.FamilyID, pq.Array(arg.Embeddings))
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.AlbumID,
		&i.UploadBatchID,
		&i.UploadStatus,
		&i.TakenLocationLatitude,
		&i.TakenLocationLongitude,
		&i.TakenAt,
		&i.FileName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaItemRange = `-- name: GetMediaItemRange :many
SELECT
    EXTRACT(
        YEAR
        FROM
            taken_at
    ) AS year,
    EXTRACT(
        MONTH
        FROM
            taken_at
    ) AS month
FROM
    media_items AS mi
    INNER JOIN albums AS a ON mi.album_id = a.id
    INNER JOIN album_groups_permissions AS agp ON a.id = agp.album_id
WHERE
    agp.group_id = $1::int
    AND agp.permission = 'R'
GROUP BY
    year,
    month
ORDER BY
    year DESC,
    month DESC
`

type GetMediaItemRangeRow struct {
	Year  string
	Month string
}

func (q *Queries) GetMediaItemRange(ctx context.Context, groupID int32) ([]GetMediaItemRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getMediaItemRange, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMediaItemRangeRow
	for rows.Next() {
		var i GetMediaItemRangeRow
		if err := rows.Scan(&i.Year, &i.Month); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMediaItemsByTakenAt = `-- name: GetMediaItemsByTakenAt :many
SELECT
    mi.id, mi.family_id, mi.album_id, mi.upload_batch_id, mi.upload_status, mi.taken_location_latitude, mi.taken_location_longitude, mi.taken_at, mi.file_name, mi.created_at, mi.updated_at,
    COALESCE(original_media_file.storage_key, '') AS original_storage_key,
    COALESCE(thumbnail_media_file.storage_key, '') AS thumbnail_storage_key,
    COALESCE(view_media_file.storage_key, '') AS view_storage_key,
    COALESCE(original_media_file.width, 0) AS original_width,
    COALESCE(original_media_file.height, 0) AS original_height,
    COALESCE(thumbnail_media_file.width, 0) AS thumbnail_width,
    COALESCE(thumbnail_media_file.height, 0) AS thumbnail_height,
    COALESCE(view_media_file.width, 0) AS view_width,
    COALESCE(view_media_file.height, 0) AS view_height
FROM
    media_items AS mi
    INNER JOIN albums AS a ON mi.album_id = a.id
    INNER JOIN album_groups_permissions AS agp ON a.id = agp.album_id
    LEFT JOIN LATERAL (
        SELECT storage_key, width, height, media_item_id
        FROM media_files
        WHERE role = '01'
    ) AS original_media_file ON original_media_file.media_item_id = mi.id
    LEFT JOIN LATERAL (
        SELECT storage_key, width, height, media_item_id
        FROM media_files
        WHERE role = '02'
    ) AS thumbnail_media_file ON thumbnail_media_file.media_item_id = mi.id
    LEFT JOIN LATERAL (
        SELECT storage_key, width, height, media_item_id
        FROM media_files
        WHERE role = '03'
    ) AS view_media_file ON view_media_file.media_item_id = mi.id
WHERE
    agp.group_id = $1::int
    AND agp.permission = 'R'
    AND mi.taken_at >= $2::timestamp
    AND mi.taken_at <= $3::timestamp
    AND mi.upload_status = '03' -- 03: completed
    AND ($4::int IS NULL OR mi.album_id = $4::int)
    AND (
        cardinality($5::int[]) = 0
        OR EXISTS (
            SELECT 1 FROM face_detections fd
            WHERE fd.media_item_id = mi.id
              AND fd.identity_id = ANY($5::int[])
        )
    )
ORDER BY
    mi.taken_at DESC
`

type GetMediaItemsByTakenAtParams struct {
	GroupID     int32
	TakenAtFrom time.Time
	TakenAtTo   time.Time
	AlbumID     sql.NullInt32
	IdentityIds []int32
}

type GetMediaItemsByTakenAtRow struct {
	ID                     int32
	FamilyID               int32
	AlbumID                int32
	UploadBatchID          int32
	UploadStatus           string
	TakenLocationLatitude  sql.NullFloat64
	TakenLocationLongitude sql.NullFloat64
	TakenAt                time.Time
	FileName               sql.NullString
	CreatedAt              time.Time
	UpdatedAt              time.Time
	OriginalStorageKey     string
	ThumbnailStorageKey    string
	ViewStorageKey         string
	OriginalWidth          int32
	OriginalHeight         int32
	ThumbnailWidth         int32
	ThumbnailHeight        int32
	ViewWidth              int32
	ViewHeight             int32
}

func (q *Queries) GetMediaItemsByTakenAt(ctx context.Context, arg GetMediaItemsByTakenAtParams) ([]GetMediaItemsByTakenAtRow, error) {
	rows, err := q.db.QueryContext(ctx, getMediaItemsByTakenAt,
		arg.GroupID,
		arg.TakenAtFrom,
		arg.TakenAtTo,
		arg.AlbumID,
		pq.Array(arg.IdentityIds),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMediaItemsByTakenAtRow
	for rows.Next() {
		var i GetMediaItemsByTakenAtRow
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.AlbumID,
			&i.UploadBatchID,
			&i.UploadStatus,
			&i.TakenLocationLatitude,
			&i.TakenLocationLongitude,
			&i.TakenAt,
			&i.FileName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OriginalStorageKey,
			&i.ThumbnailStorageKey,
			&i.ViewStorageKey,
			&i.OriginalWidth,
			&i.OriginalHeight,
			&i.ThumbnailWidth,
			&i.ThumbnailHeight,
			&i.ViewWidth,
			&i.ViewHeight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUploadStatuses = `-- name: GetUploadStatuses :many
SELECT
    mi.id,
    mi.upload_status
FROM media_items AS mi
WHERE mi.upload_batch_id = $1
ORDER BY mi.id ASC
`

type GetUploadStatusesRow struct {
	ID           int32
	UploadStatus string
}

func (q *Queries) GetUploadStatuses(ctx context.Context, uploadBatchID int32) ([]GetUploadStatusesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUploadStatuses, uploadBatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUploadStatusesRow
	for rows.Next() {
		var i GetUploadStatusesRow
		if err := rows.Scan(&i.ID, &i.UploadStatus); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaItemUploadStatus = `-- name: UpdateMediaItemUploadStatus :one
UPDATE media_items
SET upload_status = $2
WHERE id = $1
RETURNING id, upload_status, created_at, updated_at
`

type UpdateMediaItemUploadStatusParams struct {
	ID           int32
	UploadStatus string
}

type UpdateMediaItemUploadStatusRow struct {
	ID           int32
	UploadStatus string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) UpdateMediaItemUploadStatus(ctx context.Context, arg UpdateMediaItemUploadStatusParams) (UpdateMediaItemUploadStatusRow, error) {
	row := q.db.QueryRowContext(ctx, updateMediaItemUploadStatus, arg.ID, arg.UploadStatus)
	var i UpdateMediaItemUploadStatusRow
	err := row.Scan(
		&i.ID,
		&i.UploadStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
