// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media_items.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createMediaItem = `-- name: CreateMediaItem :one
INSERT INTO
    media_items (
        family_id,
        album_id,
        upload_batch_id,
        taken_at,
        file_name,
        taken_location_latitude,
        taken_location_longitude
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    id,
    family_id,
    album_id,
    upload_batch_id,
    upload_status,
    failure_reason,
    taken_location_latitude,
    taken_location_longitude,
    taken_at,
    file_name,
    created_at,
    updated_at
`

type CreateMediaItemParams struct {
	FamilyID               string
	AlbumID                string
	UploadBatchID          int32
	TakenAt                time.Time
	FileName               sql.NullString
	TakenLocationLatitude  sql.NullFloat64
	TakenLocationLongitude sql.NullFloat64
}

func (q *Queries) CreateMediaItem(ctx context.Context, arg CreateMediaItemParams) (MediaItem, error) {
	row := q.db.QueryRowContext(ctx, createMediaItem,
		arg.FamilyID,
		arg.AlbumID,
		arg.UploadBatchID,
		arg.TakenAt,
		arg.FileName,
		arg.TakenLocationLatitude,
		arg.TakenLocationLongitude,
	)
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.AlbumID,
		&i.UploadBatchID,
		&i.UploadStatus,
		&i.FailureReason,
		&i.TakenLocationLatitude,
		&i.TakenLocationLongitude,
		&i.TakenAt,
		&i.FileName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMediaItem = `-- name: DeleteMediaItem :exec
DELETE FROM media_items WHERE id = $1
`

func (q *Queries) DeleteMediaItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMediaItem, id)
	return err
}

const getMediaItemByFaceDetection = `-- name: GetMediaItemByFaceDetection :one
SELECT
    mi.id, mi.family_id, mi.album_id, mi.upload_batch_id, mi.upload_status, mi.failure_reason, mi.taken_location_latitude, mi.taken_location_longitude, mi.taken_at, mi.file_name, mi.created_at, mi.updated_at
FROM
    media_items AS mi
    INNER JOIN face_detections AS fd ON mi.id = fd.media_item_id
WHERE
    mi.family_id = $1::uuid
    AND fd.embedding = ANY($2::vector[])
GROUP BY
    mi.id
LIMIT 1
`

type GetMediaItemByFaceDetectionParams struct {
	FamilyID   string
	Embeddings []interface{}
}

func (q *Queries) GetMediaItemByFaceDetection(ctx context.Context, arg GetMediaItemByFaceDetectionParams) (MediaItem, error) {
	row := q.db.QueryRowContext(ctx, getMediaItemByFaceDetection, arg.FamilyID, pq.Array(arg.Embeddings))
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.AlbumID,
		&i.UploadBatchID,
		&i.UploadStatus,
		&i.FailureReason,
		&i.TakenLocationLatitude,
		&i.TakenLocationLongitude,
		&i.TakenAt,
		&i.FileName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaItemByIDAndFamilyID = `-- name: GetMediaItemByIDAndFamilyID :one
SELECT id, family_id, album_id, upload_batch_id, upload_status, failure_reason, taken_location_latitude, taken_location_longitude, taken_at, file_name, created_at, updated_at FROM media_items WHERE id = $1 AND family_id = $2 LIMIT 1
`

type GetMediaItemByIDAndFamilyIDParams struct {
	ID       string
	FamilyID string
}

func (q *Queries) GetMediaItemByIDAndFamilyID(ctx context.Context, arg GetMediaItemByIDAndFamilyIDParams) (MediaItem, error) {
	row := q.db.QueryRowContext(ctx, getMediaItemByIDAndFamilyID, arg.ID, arg.FamilyID)
	var i MediaItem
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.AlbumID,
		&i.UploadBatchID,
		&i.UploadStatus,
		&i.FailureReason,
		&i.TakenLocationLatitude,
		&i.TakenLocationLongitude,
		&i.TakenAt,
		&i.FileName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaItemRange = `-- name: GetMediaItemRange :many
SELECT
    EXTRACT(
        YEAR
        FROM
            taken_at
    ) AS year,
    EXTRACT(
        MONTH
        FROM
            taken_at
    ) AS month
FROM
    media_items AS mi
    INNER JOIN albums AS a ON mi.album_id = a.id
    INNER JOIN album_groups_permissions AS agp ON a.id = agp.album_id
WHERE
    agp.group_id = $1::int
    AND agp.permission = 'R'
GROUP BY
    year,
    month
ORDER BY
    year DESC,
    month DESC
`

type GetMediaItemRangeRow struct {
	Year  string
	Month string
}

func (q *Queries) GetMediaItemRange(ctx context.Context, groupID int32) ([]GetMediaItemRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getMediaItemRange, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMediaItemRangeRow
	for rows.Next() {
		var i GetMediaItemRangeRow
		if err := rows.Scan(&i.Year, &i.Month); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMediaItemThumbnailsByUploadBatchId = `-- name: GetMediaItemThumbnailsByUploadBatchId :many
SELECT
    mi.id, mi.family_id, mi.album_id, mi.upload_batch_id, mi.upload_status, mi.failure_reason, mi.taken_location_latitude, mi.taken_location_longitude, mi.taken_at, mi.file_name, mi.created_at, mi.updated_at,
    mf_orig.storage_key AS original_storage_key,
    mf_thumb.storage_key AS thumbnail_storage_key,
    mf_view.storage_key AS view_storage_key,
    mf_orig.width AS original_width,
    mf_orig.height AS original_height,
    mf_thumb.width AS thumbnail_width,
    mf_thumb.height AS thumbnail_height,
    mf_view.width AS view_width,
    mf_view.height AS view_height
FROM media_items AS mi
LEFT JOIN media_files AS mf_orig  ON mf_orig.media_item_id  = mi.id AND mf_orig.role  = '01'
LEFT JOIN media_files AS mf_thumb ON mf_thumb.media_item_id = mi.id AND mf_thumb.role = '02'
LEFT JOIN media_files AS mf_view  ON mf_view.media_item_id  = mi.id AND mf_view.role  = '03'
WHERE mi.upload_batch_id = $1 AND mi.upload_status = '03'
ORDER BY mi.taken_at ASC
LIMIT 5
`

type GetMediaItemThumbnailsByUploadBatchIdRow struct {
	ID                     string
	FamilyID               string
	AlbumID                string
	UploadBatchID          int32
	UploadStatus           string
	FailureReason          sql.NullString
	TakenLocationLatitude  sql.NullFloat64
	TakenLocationLongitude sql.NullFloat64
	TakenAt                time.Time
	FileName               sql.NullString
	CreatedAt              time.Time
	UpdatedAt              time.Time
	OriginalStorageKey     sql.NullString
	ThumbnailStorageKey    sql.NullString
	ViewStorageKey         sql.NullString
	OriginalWidth          sql.NullInt32
	OriginalHeight         sql.NullInt32
	ThumbnailWidth         sql.NullInt32
	ThumbnailHeight        sql.NullInt32
	ViewWidth              sql.NullInt32
	ViewHeight             sql.NullInt32
}

func (q *Queries) GetMediaItemThumbnailsByUploadBatchId(ctx context.Context, uploadBatchID int32) ([]GetMediaItemThumbnailsByUploadBatchIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getMediaItemThumbnailsByUploadBatchId, uploadBatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMediaItemThumbnailsByUploadBatchIdRow
	for rows.Next() {
		var i GetMediaItemThumbnailsByUploadBatchIdRow
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.AlbumID,
			&i.UploadBatchID,
			&i.UploadStatus,
			&i.FailureReason,
			&i.TakenLocationLatitude,
			&i.TakenLocationLongitude,
			&i.TakenAt,
			&i.FileName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OriginalStorageKey,
			&i.ThumbnailStorageKey,
			&i.ViewStorageKey,
			&i.OriginalWidth,
			&i.OriginalHeight,
			&i.ThumbnailWidth,
			&i.ThumbnailHeight,
			&i.ViewWidth,
			&i.ViewHeight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMediaItemsByTakenAt = `-- name: GetMediaItemsByTakenAt :many
SELECT
    mi.id, mi.family_id, mi.album_id, mi.upload_batch_id, mi.upload_status, mi.failure_reason, mi.taken_location_latitude, mi.taken_location_longitude, mi.taken_at, mi.file_name, mi.created_at, mi.updated_at,
    mf_orig.storage_key AS original_storage_key,
    mf_thumb.storage_key AS thumbnail_storage_key,
    mf_view.storage_key AS view_storage_key,
    mf_video.storage_key AS video_storage_key,
    mf_orig.width AS original_width,
    mf_orig.height AS original_height,
    mf_thumb.width AS thumbnail_width,
    mf_thumb.height AS thumbnail_height,
    mf_view.width AS view_width,
    mf_view.height AS view_height,
    mil.id AS is_liked
FROM
    media_items AS mi
    INNER JOIN albums AS a ON mi.album_id = a.id
    INNER JOIN album_groups_permissions AS agp ON a.id = agp.album_id
    LEFT JOIN media_item_likes AS mil ON mil.media_item_id = mi.id AND mil.user_id = $1::uuid
    LEFT JOIN media_files AS mf_orig  ON mf_orig.media_item_id  = mi.id AND mf_orig.role  = '01'
    LEFT JOIN media_files AS mf_thumb ON mf_thumb.media_item_id = mi.id AND mf_thumb.role = '02'
    LEFT JOIN media_files AS mf_view  ON mf_view.media_item_id  = mi.id AND mf_view.role  = '03'
    LEFT JOIN media_files AS mf_video ON mf_video.media_item_id = mi.id AND mf_video.role = '05'
WHERE
    agp.group_id = $2::int
    AND agp.permission = 'R'
    AND mi.taken_at >= $3::timestamp
    AND mi.taken_at <= $4::timestamp
    AND mi.upload_status = '03'
ORDER BY
    mi.taken_at DESC
`

type GetMediaItemsByTakenAtParams struct {
	UserID      string
	GroupID     int32
	TakenAtFrom time.Time
	TakenAtTo   time.Time
}

type GetMediaItemsByTakenAtRow struct {
	ID                     string
	FamilyID               string
	AlbumID                string
	UploadBatchID          int32
	UploadStatus           string
	FailureReason          sql.NullString
	TakenLocationLatitude  sql.NullFloat64
	TakenLocationLongitude sql.NullFloat64
	TakenAt                time.Time
	FileName               sql.NullString
	CreatedAt              time.Time
	UpdatedAt              time.Time
	OriginalStorageKey     sql.NullString
	ThumbnailStorageKey    sql.NullString
	ViewStorageKey         sql.NullString
	VideoStorageKey        sql.NullString
	OriginalWidth          sql.NullInt32
	OriginalHeight         sql.NullInt32
	ThumbnailWidth         sql.NullInt32
	ThumbnailHeight        sql.NullInt32
	ViewWidth              sql.NullInt32
	ViewHeight             sql.NullInt32
	IsLiked                sql.NullInt32
}

func (q *Queries) GetMediaItemsByTakenAt(ctx context.Context, arg GetMediaItemsByTakenAtParams) ([]GetMediaItemsByTakenAtRow, error) {
	rows, err := q.db.QueryContext(ctx, getMediaItemsByTakenAt,
		arg.UserID,
		arg.GroupID,
		arg.TakenAtFrom,
		arg.TakenAtTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMediaItemsByTakenAtRow
	for rows.Next() {
		var i GetMediaItemsByTakenAtRow
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.AlbumID,
			&i.UploadBatchID,
			&i.UploadStatus,
			&i.FailureReason,
			&i.TakenLocationLatitude,
			&i.TakenLocationLongitude,
			&i.TakenAt,
			&i.FileName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OriginalStorageKey,
			&i.ThumbnailStorageKey,
			&i.ViewStorageKey,
			&i.VideoStorageKey,
			&i.OriginalWidth,
			&i.OriginalHeight,
			&i.ThumbnailWidth,
			&i.ThumbnailHeight,
			&i.ViewWidth,
			&i.ViewHeight,
			&i.IsLiked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMediaItemsByUploadBatchId = `-- name: GetMediaItemsByUploadBatchId :many
SELECT
    mi.id, mi.family_id, mi.album_id, mi.upload_batch_id, mi.upload_status, mi.failure_reason, mi.taken_location_latitude, mi.taken_location_longitude, mi.taken_at, mi.file_name, mi.created_at, mi.updated_at,
    mf_orig.storage_key AS original_storage_key,
    mf_thumb.storage_key AS thumbnail_storage_key,
    mf_view.storage_key AS view_storage_key,
    mf_video.storage_key AS video_storage_key,
    mf_orig.width AS original_width,
    mf_orig.height AS original_height,
    mf_thumb.width AS thumbnail_width,
    mf_thumb.height AS thumbnail_height,
    mf_view.width AS view_width,
    mf_view.height AS view_height,
    mil.id AS is_liked
FROM media_items AS mi
LEFT JOIN media_item_likes AS mil ON mil.media_item_id = mi.id AND mil.user_id = $1::uuid
LEFT JOIN media_files AS mf_orig  ON mf_orig.media_item_id  = mi.id AND mf_orig.role  = '01'
LEFT JOIN media_files AS mf_thumb ON mf_thumb.media_item_id = mi.id AND mf_thumb.role = '02'
LEFT JOIN media_files AS mf_view  ON mf_view.media_item_id  = mi.id AND mf_view.role  = '03'
LEFT JOIN media_files AS mf_video ON mf_video.media_item_id = mi.id AND mf_video.role = '05'
WHERE mi.upload_batch_id = $2::int AND mi.upload_status = '03'
ORDER BY mi.taken_at ASC
LIMIT $4::int
OFFSET $3::int
`

type GetMediaItemsByUploadBatchIdParams struct {
	UserID        string
	UploadBatchID int32
	PageOffset    int32
	PageSize      int32
}

type GetMediaItemsByUploadBatchIdRow struct {
	ID                     string
	FamilyID               string
	AlbumID                string
	UploadBatchID          int32
	UploadStatus           string
	FailureReason          sql.NullString
	TakenLocationLatitude  sql.NullFloat64
	TakenLocationLongitude sql.NullFloat64
	TakenAt                time.Time
	FileName               sql.NullString
	CreatedAt              time.Time
	UpdatedAt              time.Time
	OriginalStorageKey     sql.NullString
	ThumbnailStorageKey    sql.NullString
	ViewStorageKey         sql.NullString
	VideoStorageKey        sql.NullString
	OriginalWidth          sql.NullInt32
	OriginalHeight         sql.NullInt32
	ThumbnailWidth         sql.NullInt32
	ThumbnailHeight        sql.NullInt32
	ViewWidth              sql.NullInt32
	ViewHeight             sql.NullInt32
	IsLiked                sql.NullInt32
}

func (q *Queries) GetMediaItemsByUploadBatchId(ctx context.Context, arg GetMediaItemsByUploadBatchIdParams) ([]GetMediaItemsByUploadBatchIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getMediaItemsByUploadBatchId,
		arg.UserID,
		arg.UploadBatchID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMediaItemsByUploadBatchIdRow
	for rows.Next() {
		var i GetMediaItemsByUploadBatchIdRow
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.AlbumID,
			&i.UploadBatchID,
			&i.UploadStatus,
			&i.FailureReason,
			&i.TakenLocationLatitude,
			&i.TakenLocationLongitude,
			&i.TakenAt,
			&i.FileName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OriginalStorageKey,
			&i.ThumbnailStorageKey,
			&i.ViewStorageKey,
			&i.VideoStorageKey,
			&i.OriginalWidth,
			&i.OriginalHeight,
			&i.ThumbnailWidth,
			&i.ThumbnailHeight,
			&i.ViewWidth,
			&i.ViewHeight,
			&i.IsLiked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUploadBatchWithThumbnails = `-- name: GetUploadBatchWithThumbnails :many
SELECT
    ub.id, ub.album_id,
    mf_thumb.storage_key,
    mf_thumb.width,
    mf_thumb.height,
    mf_thumb.media_item_id
FROM upload_batches AS ub
LEFT JOIN LATERAL (
    SELECT storage_key, width, height, media_item_id
    FROM media_items AS mi
    JOIN media_files AS mf ON mf.media_item_id = mi.id
    WHERE mf.role = '02'
    AND mi.upload_status = '03'
    AND mi.upload_batch_id = ub.id
    ORDER BY mi.taken_at ASC
    LIMIT 5
) AS mf_thumb ON true
WHERE ub.id = ANY($1::int[])
AND mf_thumb.storage_key IS NOT NULL
ORDER BY ub.upload_at DESC
`

type GetUploadBatchWithThumbnailsRow struct {
	ID          int32
	AlbumID     string
	StorageKey  string
	Width       sql.NullInt32
	Height      sql.NullInt32
	MediaItemID string
}

func (q *Queries) GetUploadBatchWithThumbnails(ctx context.Context, batchIds []int32) ([]GetUploadBatchWithThumbnailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUploadBatchWithThumbnails, pq.Array(batchIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUploadBatchWithThumbnailsRow
	for rows.Next() {
		var i GetUploadBatchWithThumbnailsRow
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.StorageKey,
			&i.Width,
			&i.Height,
			&i.MediaItemID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUploadStatuses = `-- name: GetUploadStatuses :many
SELECT
    mi.id,
    mi.upload_status,
    mi.failure_reason
FROM media_items AS mi
WHERE mi.upload_batch_id = $1
ORDER BY mi.id ASC
`

type GetUploadStatusesRow struct {
	ID            string
	UploadStatus  string
	FailureReason sql.NullString
}

func (q *Queries) GetUploadStatuses(ctx context.Context, uploadBatchID int32) ([]GetUploadStatusesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUploadStatuses, uploadBatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUploadStatusesRow
	for rows.Next() {
		var i GetUploadStatusesRow
		if err := rows.Scan(&i.ID, &i.UploadStatus, &i.FailureReason); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMediaItems = `-- name: SearchMediaItems :many
SELECT
    mi.id, mi.family_id, mi.album_id, mi.upload_batch_id, mi.upload_status, mi.failure_reason, mi.taken_location_latitude, mi.taken_location_longitude, mi.taken_at, mi.file_name, mi.created_at, mi.updated_at,
    mf_orig.storage_key AS original_storage_key,
    mf_thumb.storage_key AS thumbnail_storage_key,
    mf_view.storage_key AS view_storage_key,
    mf_video.storage_key AS video_storage_key,
    mf_orig.width AS original_width,
    mf_orig.height AS original_height,
    mf_thumb.width AS thumbnail_width,
    mf_thumb.height AS thumbnail_height,
    mf_view.width AS view_width,
    mf_view.height AS view_height,
    mil.id AS is_liked
FROM
    media_items AS mi
    INNER JOIN albums AS a ON mi.album_id = a.id
    INNER JOIN album_groups_permissions AS agp ON a.id = agp.album_id
    LEFT JOIN media_item_likes AS mil ON mil.media_item_id = mi.id AND mil.user_id = $1::uuid
    LEFT JOIN media_files AS mf_orig  ON mf_orig.media_item_id  = mi.id AND mf_orig.role  = '01'
    LEFT JOIN media_files AS mf_thumb ON mf_thumb.media_item_id = mi.id AND mf_thumb.role = '02'
    LEFT JOIN media_files AS mf_view  ON mf_view.media_item_id  = mi.id AND mf_view.role  = '03'
    LEFT JOIN media_files AS mf_video ON mf_video.media_item_id = mi.id AND mf_video.role = '05'
WHERE
    agp.group_id = $2::int
    AND agp.permission = 'R'
    AND mi.upload_status = '03'
    AND ($3::timestamp IS NULL OR mi.taken_at >= $3::timestamp)
    AND ($4::timestamp IS NULL OR mi.taken_at <= $4::timestamp)
    AND ($5::uuid IS NULL OR mi.album_id = $5::uuid)
    AND (
        cardinality($6::int[]) = 0
        OR EXISTS (
            SELECT 1 FROM face_detections fd
            WHERE fd.media_item_id = mi.id
              AND fd.identity_id = ANY($6::int[])
        )
    )
    AND (
        NOT $7::boolean
        OR EXISTS (
            SELECT 1 FROM media_item_likes mil
            WHERE mil.media_item_id = mi.id
              AND mil.user_id = $1::uuid
        )
    )
    AND (
        cardinality($8::int[]) = 0
        OR EXISTS (
            SELECT 1 FROM media_item_tags mit
            WHERE mit.media_item_id = mi.id
              AND mit.tag_id = ANY($8::int[])
        )
    )
ORDER BY
    mi.taken_at DESC
LIMIT $10::int
OFFSET $9::int
`

type SearchMediaItemsParams struct {
	UserID      string
	GroupID     int32
	TakenAtFrom sql.NullTime
	TakenAtTo   sql.NullTime
	AlbumID     uuid.NullUUID
	IdentityIds []int32
	Liked       bool
	TagIds      []int32
	PageOffset  int32
	PageSize    int32
}

type SearchMediaItemsRow struct {
	ID                     string
	FamilyID               string
	AlbumID                string
	UploadBatchID          int32
	UploadStatus           string
	FailureReason          sql.NullString
	TakenLocationLatitude  sql.NullFloat64
	TakenLocationLongitude sql.NullFloat64
	TakenAt                time.Time
	FileName               sql.NullString
	CreatedAt              time.Time
	UpdatedAt              time.Time
	OriginalStorageKey     sql.NullString
	ThumbnailStorageKey    sql.NullString
	ViewStorageKey         sql.NullString
	VideoStorageKey        sql.NullString
	OriginalWidth          sql.NullInt32
	OriginalHeight         sql.NullInt32
	ThumbnailWidth         sql.NullInt32
	ThumbnailHeight        sql.NullInt32
	ViewWidth              sql.NullInt32
	ViewHeight             sql.NullInt32
	IsLiked                sql.NullInt32
}

func (q *Queries) SearchMediaItems(ctx context.Context, arg SearchMediaItemsParams) ([]SearchMediaItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMediaItems,
		arg.UserID,
		arg.GroupID,
		arg.TakenAtFrom,
		arg.TakenAtTo,
		arg.AlbumID,
		pq.Array(arg.IdentityIds),
		arg.Liked,
		pq.Array(arg.TagIds),
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMediaItemsRow
	for rows.Next() {
		var i SearchMediaItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.AlbumID,
			&i.UploadBatchID,
			&i.UploadStatus,
			&i.FailureReason,
			&i.TakenLocationLatitude,
			&i.TakenLocationLongitude,
			&i.TakenAt,
			&i.FileName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OriginalStorageKey,
			&i.ThumbnailStorageKey,
			&i.ViewStorageKey,
			&i.VideoStorageKey,
			&i.OriginalWidth,
			&i.OriginalHeight,
			&i.ThumbnailWidth,
			&i.ThumbnailHeight,
			&i.ViewWidth,
			&i.ViewHeight,
			&i.IsLiked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaItemAlbum = `-- name: UpdateMediaItemAlbum :exec
UPDATE media_items SET album_id = $2 WHERE id = $1
`

type UpdateMediaItemAlbumParams struct {
	ID      string
	AlbumID string
}

func (q *Queries) UpdateMediaItemAlbum(ctx context.Context, arg UpdateMediaItemAlbumParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaItemAlbum, arg.ID, arg.AlbumID)
	return err
}

const updateMediaItemFailed = `-- name: UpdateMediaItemFailed :exec
UPDATE media_items
SET upload_status = '04',
    failure_reason = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateMediaItemFailedParams struct {
	ID            string
	FailureReason sql.NullString
}

func (q *Queries) UpdateMediaItemFailed(ctx context.Context, arg UpdateMediaItemFailedParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaItemFailed, arg.ID, arg.FailureReason)
	return err
}

const updateMediaItemTakenAt = `-- name: UpdateMediaItemTakenAt :exec
UPDATE media_items
SET taken_at = $2,
    taken_location_latitude = $3,
    taken_location_longitude = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateMediaItemTakenAtParams struct {
	ID                     string
	TakenAt                time.Time
	TakenLocationLatitude  sql.NullFloat64
	TakenLocationLongitude sql.NullFloat64
}

func (q *Queries) UpdateMediaItemTakenAt(ctx context.Context, arg UpdateMediaItemTakenAtParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaItemTakenAt,
		arg.ID,
		arg.TakenAt,
		arg.TakenLocationLatitude,
		arg.TakenLocationLongitude,
	)
	return err
}

const updateMediaItemUploadStatus = `-- name: UpdateMediaItemUploadStatus :one
UPDATE media_items
SET upload_status = $2
WHERE id = $1
RETURNING id, upload_status, created_at, updated_at
`

type UpdateMediaItemUploadStatusParams struct {
	ID           string
	UploadStatus string
}

type UpdateMediaItemUploadStatusRow struct {
	ID           string
	UploadStatus string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) UpdateMediaItemUploadStatus(ctx context.Context, arg UpdateMediaItemUploadStatusParams) (UpdateMediaItemUploadStatusRow, error) {
	row := q.db.QueryRowContext(ctx, updateMediaItemUploadStatus, arg.ID, arg.UploadStatus)
	var i UpdateMediaItemUploadStatusRow
	err := row.Scan(
		&i.ID,
		&i.UploadStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
