// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Album struct {
	ID        string
	FamilyID  string
	Name      string
	IsCommon  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AlbumGroupsPermission struct {
	AlbumID    string
	GroupID    int32
	Permission string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type FaceDetection struct {
	ID             int32
	MediaItemID    string
	IdentityID     int32
	LocationTop    int32
	LocationRight  int32
	LocationBottom int32
	LocationLeft   int32
	Embedding      interface{}
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Family struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Group struct {
	ID        int32
	FamilyID  string
	IsAdmin   bool
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Identity struct {
	ID        int32
	FamilyID  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type IdentityFaceImg struct {
	ID          int32
	IdentityID  int32
	MediaItemID string
	StorageKey  string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type InviteToken struct {
	ID                int32
	Token             string
	FamilyTitle       sql.NullString
	CustomFamilyTitle sql.NullString
	FamilyID          string
	GroupID           int32
	CreatedByUserID   string
	ExpiresAt         time.Time
	UsedAt            sql.NullTime
	CreatedAt         time.Time
}

type Kid struct {
	ID         int32
	Name       sql.NullString
	BirthDate  sql.NullTime
	IdentityID sql.NullInt32
	FamilyID   string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type MediaFile struct {
	ID          int32
	MediaItemID string
	Role        string
	StorageKey  string
	Width       sql.NullInt32
	Height      sql.NullInt32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type MediaItem struct {
	ID                     string
	FamilyID               string
	AlbumID                string
	UploadBatchID          int32
	UploadStatus           string
	FailureReason          sql.NullString
	TakenLocationLatitude  sql.NullFloat64
	TakenLocationLongitude sql.NullFloat64
	TakenAt                time.Time
	FileName               sql.NullString
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

type MediaItemLike struct {
	ID          int32
	MediaItemID string
	UserID      string
	CreatedAt   time.Time
}

type MediaItemTag struct {
	MediaItemID string
	TagID       int32
	TaggedBy    string
	CreatedAt   time.Time
}

type RefreshToken struct {
	ID        int32
	Token     string
	ExpiresAt time.Time
	UserID    string
	CreatedAt time.Time
}

type Tag struct {
	ID        int32
	FamilyID  uuid.NullUUID
	Name      string
	IsPreset  bool
	CreatedBy uuid.NullUUID
	CreatedAt time.Time
}

type UploadBatch struct {
	ID        int32
	AlbumID   string
	UploadAt  time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID                string
	Name              sql.NullString
	Username          string
	FamilyTitle       sql.NullString
	CustomFamilyTitle sql.NullString
	Password          string
	FamilyID          string
	GroupID           int32
	IdentityID        sql.NullInt32
	Provider          sql.NullString
	ProviderUserID    sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
}
