// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type AverageFaceEmbedding struct {
	PersonID  int32
	Embedding interface{}
}

type ClanGroup struct {
	ID        int32
	GroupID   int32
	IsAdmin   bool
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type FaceDetection struct {
	ID             int32
	PhotoID        int32
	PersonID       int32
	LocationTop    int32
	LocationRight  int32
	LocationBottom int32
	LocationLeft   int32
	Embedding      interface{}
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Group struct {
	ID        int32
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Person struct {
	ID        int32
	Name      sql.NullString
	GroupID   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Photo struct {
	ID              int32
	GroupID         int32
	ClanGroupID     sql.NullInt32
	ThumbnailUrl    string
	OriginalUrl     sql.NullString
	LiveUrl         sql.NullString
	OriginalLiveUrl sql.NullString
	Width           int32
	Height          int32
	Orientation     int32
	PhotoCreatedAt  time.Time
	FileName        string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type RefreshToken struct {
	ID        int32
	Token     string
	ExpiresAt time.Time
	UserID    int32
	CreatedAt time.Time
}

type User struct {
	ID          int32
	Name        sql.NullString
	Username    string
	Password    string
	GroupID     int32
	ClanGroupID int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
