// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: people.sql

package db

import (
	"context"
	"database/sql"
)

const createPerson = `-- name: CreatePerson :one
INSERT INTO
    people (name, group_id)
VALUES
    ($1, $2)
RETURNING
    id, name, group_id, created_at, updated_at
`

type CreatePersonParams struct {
	Name    sql.NullString
	GroupID int32
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, createPerson, arg.Name, arg.GroupID)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPersonByID = `-- name: FindPersonByID :one
SELECT
    id,
    name,
    group_id
FROM
    people
WHERE
    id = $1::int
`

type FindPersonByIDRow struct {
	ID      int32
	Name    sql.NullString
	GroupID int32
}

func (q *Queries) FindPersonByID(ctx context.Context, id int32) (FindPersonByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findPersonByID, id)
	var i FindPersonByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.GroupID)
	return i, err
}
