// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photos.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const createPhoto = `-- name: CreatePhoto :one
INSERT INTO
    photos (
        group_id,
        album_id,
        thumbnail_url,
        original_url,
        live_url,
        original_live_url,
        original_width,
        original_height,
        thumbnail_width,
        thumbnail_height,
        photo_created_at,
        file_name
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING
    id,
    group_id,
    album_id,
    thumbnail_url,
    original_url,
    live_url,
    original_live_url,
    original_width,
    original_height,
    thumbnail_width,
    thumbnail_height,
    photo_created_at,
    file_name,
    created_at,
    updated_at
`

type CreatePhotoParams struct {
	GroupID         int32
	AlbumID         int32
	ThumbnailUrl    string
	OriginalUrl     sql.NullString
	LiveUrl         sql.NullString
	OriginalLiveUrl sql.NullString
	OriginalWidth   sql.NullInt32
	OriginalHeight  sql.NullInt32
	ThumbnailWidth  int32
	ThumbnailHeight int32
	PhotoCreatedAt  time.Time
	FileName        string
}

func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error) {
	row := q.db.QueryRowContext(ctx, createPhoto,
		arg.GroupID,
		arg.AlbumID,
		arg.ThumbnailUrl,
		arg.OriginalUrl,
		arg.LiveUrl,
		arg.OriginalLiveUrl,
		arg.OriginalWidth,
		arg.OriginalHeight,
		arg.ThumbnailWidth,
		arg.ThumbnailHeight,
		arg.PhotoCreatedAt,
		arg.FileName,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.AlbumID,
		&i.ThumbnailUrl,
		&i.OriginalUrl,
		&i.LiveUrl,
		&i.OriginalLiveUrl,
		&i.OriginalWidth,
		&i.OriginalHeight,
		&i.ThumbnailWidth,
		&i.ThumbnailHeight,
		&i.PhotoCreatedAt,
		&i.FileName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPhotosByPhotoCreatedAt = `-- name: FindPhotosByPhotoCreatedAt :many
SELECT
    p.id, p.group_id, p.album_id, p.thumbnail_url, p.original_url, p.live_url, p.original_live_url, p.original_width, p.original_height, p.thumbnail_width, p.thumbnail_height, p.photo_created_at, p.file_name, p.created_at, p.updated_at
FROM
    photos AS p
    INNER JOIN albums AS a ON p.album_id = a.id
    INNER JOIN album_clan_groups_permissions AS acgp ON a.id = acgp.album_id
WHERE
    acgp.clan_group_id = $1::int
    AND acgp.permission = 'R'
    AND p.photo_created_at >= $2::timestamp
    AND p.photo_created_at <= $3::timestamp
ORDER BY
    photo_created_at DESC
`

type FindPhotosByPhotoCreatedAtParams struct {
	ClanGroupID        int32
	PhotoCreatedAtFrom time.Time
	PhotoCreatedAtTo   time.Time
}

func (q *Queries) FindPhotosByPhotoCreatedAt(ctx context.Context, arg FindPhotosByPhotoCreatedAtParams) ([]Photo, error) {
	rows, err := q.db.QueryContext(ctx, findPhotosByPhotoCreatedAt, arg.ClanGroupID, arg.PhotoCreatedAtFrom, arg.PhotoCreatedAtTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Photo
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.AlbumID,
			&i.ThumbnailUrl,
			&i.OriginalUrl,
			&i.LiveUrl,
			&i.OriginalLiveUrl,
			&i.OriginalWidth,
			&i.OriginalHeight,
			&i.ThumbnailWidth,
			&i.ThumbnailHeight,
			&i.PhotoCreatedAt,
			&i.FileName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIdentityRandomPhoto = `-- name: GetIdentityRandomPhoto :one
SELECT
    p.id, p.group_id, p.album_id, p.thumbnail_url, p.original_url, p.live_url, p.original_live_url, p.original_width, p.original_height, p.thumbnail_width, p.thumbnail_height, p.photo_created_at, p.file_name, p.created_at, p.updated_at,
    fd.location_top,
    fd.location_right,
    fd.location_bottom,
    fd.location_left
FROM
    (
        SELECT photo_id, location_top, location_right, location_bottom, location_left
        FROM face_detections 
        WHERE identity_id = $1::int
        ORDER BY RANDOM()
        LIMIT 1
    ) AS fd
    INNER JOIN photos AS p ON fd.photo_id = p.id
    INNER JOIN albums AS a ON p.album_id = a.id
    INNER JOIN album_clan_groups_permissions AS acgp ON a.id = acgp.album_id
WHERE
    acgp.clan_group_id = $2::int
    AND acgp.permission = 'R'
`

type GetIdentityRandomPhotoParams struct {
	IdentityID  int32
	ClanGroupID int32
}

type GetIdentityRandomPhotoRow struct {
	ID              int32
	GroupID         int32
	AlbumID         int32
	ThumbnailUrl    string
	OriginalUrl     sql.NullString
	LiveUrl         sql.NullString
	OriginalLiveUrl sql.NullString
	OriginalWidth   sql.NullInt32
	OriginalHeight  sql.NullInt32
	ThumbnailWidth  int32
	ThumbnailHeight int32
	PhotoCreatedAt  time.Time
	FileName        string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	LocationTop     int32
	LocationRight   int32
	LocationBottom  int32
	LocationLeft    int32
}

func (q *Queries) GetIdentityRandomPhoto(ctx context.Context, arg GetIdentityRandomPhotoParams) (GetIdentityRandomPhotoRow, error) {
	row := q.db.QueryRowContext(ctx, getIdentityRandomPhoto, arg.IdentityID, arg.ClanGroupID)
	var i GetIdentityRandomPhotoRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.AlbumID,
		&i.ThumbnailUrl,
		&i.OriginalUrl,
		&i.LiveUrl,
		&i.OriginalLiveUrl,
		&i.OriginalWidth,
		&i.OriginalHeight,
		&i.ThumbnailWidth,
		&i.ThumbnailHeight,
		&i.PhotoCreatedAt,
		&i.FileName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocationTop,
		&i.LocationRight,
		&i.LocationBottom,
		&i.LocationLeft,
	)
	return i, err
}

const getPhotoByFaceDetection = `-- name: GetPhotoByFaceDetection :one
SELECT
    p.id, p.group_id, p.album_id, p.thumbnail_url, p.original_url, p.live_url, p.original_live_url, p.original_width, p.original_height, p.thumbnail_width, p.thumbnail_height, p.photo_created_at, p.file_name, p.created_at, p.updated_at
FROM
    photos AS p
    INNER JOIN face_detections AS fd ON p.id = fd.photo_id
WHERE
    p.group_id = $1::int
    AND fd.embedding = ANY($2::vector[])
GROUP BY
    p.id
LIMIT 1
`

type GetPhotoByFaceDetectionParams struct {
	GroupID    int32
	Embeddings []interface{}
}

func (q *Queries) GetPhotoByFaceDetection(ctx context.Context, arg GetPhotoByFaceDetectionParams) (Photo, error) {
	row := q.db.QueryRowContext(ctx, getPhotoByFaceDetection, arg.GroupID, pq.Array(arg.Embeddings))
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.AlbumID,
		&i.ThumbnailUrl,
		&i.OriginalUrl,
		&i.LiveUrl,
		&i.OriginalLiveUrl,
		&i.OriginalWidth,
		&i.OriginalHeight,
		&i.ThumbnailWidth,
		&i.ThumbnailHeight,
		&i.PhotoCreatedAt,
		&i.FileName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPhotoRange = `-- name: GetPhotoRange :many
SELECT
    EXTRACT(
        YEAR
        FROM
            photo_created_at
    ) AS year,
    EXTRACT(
        MONTH
        FROM
            photo_created_at
    ) AS month
FROM
    photos AS p
    INNER JOIN albums AS a ON p.album_id = a.id
    INNER JOIN album_clan_groups_permissions AS acgp ON a.id = acgp.album_id
WHERE
    acgp.clan_group_id = $1::int
    AND acgp.permission = 'R'
GROUP BY
    year,
    month
ORDER BY
    year DESC,
    month DESC
`

type GetPhotoRangeRow struct {
	Year  string
	Month string
}

func (q *Queries) GetPhotoRange(ctx context.Context, clanGroupID int32) ([]GetPhotoRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getPhotoRange, clanGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPhotoRangeRow
	for rows.Next() {
		var i GetPhotoRangeRow
		if err := rows.Scan(&i.Year, &i.Month); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
