// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photos.sql

package db

import (
	"context"
	"time"
)

const createPhoto = `-- name: CreatePhoto :one
INSERT INTO
    photos (
        group_id,
        clan_group_id,
        thumbnail_url,
        original_url,
        live_url,
        original_live_url,
        width,
        height,
        orientation,
        photo_created_at,
        file_name
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING
    id,
    group_id,
    clan_group_id,
    thumbnail_url,
    original_url,
    live_url,
    original_live_url,
    width,
    height,
    orientation,
    photo_created_at,
    file_name,
    created_at,
    updated_at
`

type CreatePhotoParams struct {
	GroupID         int32
	ClanGroupID     int32
	ThumbnailUrl    string
	OriginalUrl     string
	LiveUrl         string
	OriginalLiveUrl string
	Width           int32
	Height          int32
	Orientation     int32
	PhotoCreatedAt  time.Time
	FileName        string
}

func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error) {
	row := q.db.QueryRowContext(ctx, createPhoto,
		arg.GroupID,
		arg.ClanGroupID,
		arg.ThumbnailUrl,
		arg.OriginalUrl,
		arg.LiveUrl,
		arg.OriginalLiveUrl,
		arg.Width,
		arg.Height,
		arg.Orientation,
		arg.PhotoCreatedAt,
		arg.FileName,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ClanGroupID,
		&i.ThumbnailUrl,
		&i.OriginalUrl,
		&i.LiveUrl,
		&i.OriginalLiveUrl,
		&i.Width,
		&i.Height,
		&i.Orientation,
		&i.PhotoCreatedAt,
		&i.FileName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
