// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photos.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createPhoto = `-- name: CreatePhoto :one
INSERT INTO
    photos (
        group_id,
        clan_group_id,
        thumbnail_url,
        original_url,
        live_url,
        original_live_url,
        width,
        height,
        orientation,
        photo_created_at,
        file_name
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING
    id,
    group_id,
    clan_group_id,
    thumbnail_url,
    original_url,
    live_url,
    original_live_url,
    width,
    height,
    orientation,
    photo_created_at,
    file_name,
    created_at,
    updated_at
`

type CreatePhotoParams struct {
	GroupID         int32
	ClanGroupID     sql.NullInt32
	ThumbnailUrl    string
	OriginalUrl     sql.NullString
	LiveUrl         sql.NullString
	OriginalLiveUrl sql.NullString
	Width           int32
	Height          int32
	Orientation     int32
	PhotoCreatedAt  time.Time
	FileName        string
}

func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error) {
	row := q.db.QueryRowContext(ctx, createPhoto,
		arg.GroupID,
		arg.ClanGroupID,
		arg.ThumbnailUrl,
		arg.OriginalUrl,
		arg.LiveUrl,
		arg.OriginalLiveUrl,
		arg.Width,
		arg.Height,
		arg.Orientation,
		arg.PhotoCreatedAt,
		arg.FileName,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ClanGroupID,
		&i.ThumbnailUrl,
		&i.OriginalUrl,
		&i.LiveUrl,
		&i.OriginalLiveUrl,
		&i.Width,
		&i.Height,
		&i.Orientation,
		&i.PhotoCreatedAt,
		&i.FileName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPhotosByPhotoCreatedAt = `-- name: FindPhotosByPhotoCreatedAt :many
SELECT
    id, group_id, clan_group_id, thumbnail_url, original_url, live_url, original_live_url, width, height, orientation, photo_created_at, file_name, created_at, updated_at
FROM
    photos
WHERE
    group_id = $1::int
    AND photo_created_at >= $2::time
    AND photo_created_at <= $3::time
    AND (
        CASE
            WHEN $4::int IS NOT NULL THEN clan_group_id IS NULL
            OR clan_group_id = $4::int
        END
    )
ORDER BY
    photo_created_at DESC
`

type FindPhotosByPhotoCreatedAtParams struct {
	GroupID            int32
	PhotoCreatedAtFrom time.Time
	PhotoCreatedAtTo   time.Time
	ClanGroupID        sql.NullInt32
}

func (q *Queries) FindPhotosByPhotoCreatedAt(ctx context.Context, arg FindPhotosByPhotoCreatedAtParams) ([]Photo, error) {
	rows, err := q.db.QueryContext(ctx, findPhotosByPhotoCreatedAt,
		arg.GroupID,
		arg.PhotoCreatedAtFrom,
		arg.PhotoCreatedAtTo,
		arg.ClanGroupID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Photo
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.ClanGroupID,
			&i.ThumbnailUrl,
			&i.OriginalUrl,
			&i.LiveUrl,
			&i.OriginalLiveUrl,
			&i.Width,
			&i.Height,
			&i.Orientation,
			&i.PhotoCreatedAt,
			&i.FileName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPhotoRange = `-- name: GetPhotoRange :many
SELECT
    EXTRACT(
        YEAR
        FROM
            photo_created_at
    ) AS year,
    EXTRACT(
        MONTH
        FROM
            photo_created_at
    ) AS month
FROM
    photos
WHERE
    group_id = $1::int
    AND (
        CASE
            WHEN $2::int IS NOT NULL THEN clan_group_id IS NULL
            OR clan_group_id = $2::int
        END
    )
GROUP BY
    year,
    month
ORDER BY
    year DESC,
    month DESC
`

type GetPhotoRangeParams struct {
	GroupID     int32
	ClanGroupID sql.NullInt32
}

type GetPhotoRangeRow struct {
	Year  string
	Month string
}

func (q *Queries) GetPhotoRange(ctx context.Context, arg GetPhotoRangeParams) ([]GetPhotoRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getPhotoRange, arg.GroupID, arg.ClanGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPhotoRangeRow
	for rows.Next() {
		var i GetPhotoRangeRow
		if err := rows.Scan(&i.Year, &i.Month); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
