// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"
	"database/sql"
)

const addTagToMediaItem = `-- name: AddTagToMediaItem :exec
INSERT INTO media_item_tags (media_item_id, tag_id, tagged_by)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddTagToMediaItemParams struct {
	MediaItemID int32
	TagID       int32
	TaggedBy    int32
}

func (q *Queries) AddTagToMediaItem(ctx context.Context, arg AddTagToMediaItemParams) error {
	_, err := q.db.ExecContext(ctx, addTagToMediaItem, arg.MediaItemID, arg.TagID, arg.TaggedBy)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (family_id, name, is_preset, created_by)
VALUES ($1, $2, false, $3)
RETURNING id, family_id, name, is_preset, created_by, created_at
`

type CreateTagParams struct {
	FamilyID  sql.NullInt32
	Name      string
	CreatedBy sql.NullInt32
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, arg.FamilyID, arg.Name, arg.CreatedBy)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.IsPreset,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags
WHERE id = $1 AND family_id = $2
`

type DeleteTagParams struct {
	ID       int32
	FamilyID sql.NullInt32
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.ExecContext(ctx, deleteTag, arg.ID, arg.FamilyID)
	return err
}

const getTagsByFamilyID = `-- name: GetTagsByFamilyID :many
SELECT id, family_id, name, is_preset, created_by, created_at FROM tags
WHERE family_id = $1 OR is_preset = true
ORDER BY is_preset DESC, id ASC
`

func (q *Queries) GetTagsByFamilyID(ctx context.Context, familyID sql.NullInt32) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsByFamilyID, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Name,
			&i.IsPreset,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsForMediaItem = `-- name: GetTagsForMediaItem :many
SELECT t.id, t.family_id, t.name, t.is_preset, t.created_by, t.created_at FROM tags t
JOIN media_item_tags mt ON t.id = mt.tag_id
WHERE mt.media_item_id = $1
ORDER BY t.id ASC
`

func (q *Queries) GetTagsForMediaItem(ctx context.Context, mediaItemID int32) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsForMediaItem, mediaItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Name,
			&i.IsPreset,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromMediaItem = `-- name: RemoveTagFromMediaItem :exec
DELETE FROM media_item_tags
WHERE media_item_id = $1 AND tag_id = $2
`

type RemoveTagFromMediaItemParams struct {
	MediaItemID int32
	TagID       int32
}

func (q *Queries) RemoveTagFromMediaItem(ctx context.Context, arg RemoveTagFromMediaItemParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromMediaItem, arg.MediaItemID, arg.TagID)
	return err
}
