// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upload_batches.sql

package db

import (
	"context"
	"time"
)

const createUploadBatch = `-- name: CreateUploadBatch :one
INSERT INTO upload_batches (
    album_id
)
VALUES ($1)
RETURNING id, album_id, upload_at, created_at, updated_at
`

func (q *Queries) CreateUploadBatch(ctx context.Context, albumID string) (UploadBatch, error) {
	row := q.db.QueryRowContext(ctx, createUploadBatch, albumID)
	var i UploadBatch
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.UploadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUploadBatchesAndMediaItemCounts = `-- name: GetUploadBatchesAndMediaItemCounts :many
SELECT
    ub.id,
    ub.album_id,
    ub.upload_at,
    item_counts.count
FROM upload_batches AS ub
INNER JOIN albums AS a ON a.id = ub.album_id
INNER JOIN album_groups_permissions AS agp ON a.id = agp.album_id
INNER JOIN (
    SELECT upload_batch_id, COUNT(*) AS count
    FROM media_items
    WHERE upload_status = '03'
    GROUP BY upload_batch_id
) AS item_counts ON item_counts.upload_batch_id = ub.id
WHERE
    agp.group_id = $1::int
    AND agp.permission = 'R'
ORDER BY ub.upload_at DESC
LIMIT $3::int
OFFSET $2::int
`

type GetUploadBatchesAndMediaItemCountsParams struct {
	GroupID    int32
	PageOffset int32
	PageSize   int32
}

type GetUploadBatchesAndMediaItemCountsRow struct {
	ID       int32
	AlbumID  string
	UploadAt time.Time
	Count    int64
}

func (q *Queries) GetUploadBatchesAndMediaItemCounts(ctx context.Context, arg GetUploadBatchesAndMediaItemCountsParams) ([]GetUploadBatchesAndMediaItemCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUploadBatchesAndMediaItemCounts, arg.GroupID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUploadBatchesAndMediaItemCountsRow
	for rows.Next() {
		var i GetUploadBatchesAndMediaItemCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.UploadAt,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
