// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (name, username, password, family_id, group_id)
VALUES
    ($1, $2, $3, $4, $5)
RETURNING
    id, name, username, family_title, custom_family_title, password, family_id, group_id, identity_id, provider, provider_user_id, created_at, updated_at
`

type CreateUserParams struct {
	Name     sql.NullString
	Username string
	Password string
	FamilyID int32
	GroupID  int32
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Username,
		arg.Password,
		arg.FamilyID,
		arg.GroupID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.FamilyTitle,
		&i.CustomFamilyTitle,
		&i.Password,
		&i.FamilyID,
		&i.GroupID,
		&i.IdentityID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserOAuth = `-- name: CreateUserOAuth :one
INSERT INTO
    users (name, username, password, family_id, group_id, provider, provider_user_id, family_title, custom_family_title)
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING
    id, name, username, family_title, custom_family_title, password, family_id, group_id, identity_id, provider, provider_user_id, created_at, updated_at
`

type CreateUserOAuthParams struct {
	Name              sql.NullString
	Username          string
	Password          string
	FamilyID          int32
	GroupID           int32
	Provider          sql.NullString
	ProviderUserID    sql.NullString
	FamilyTitle       sql.NullString
	CustomFamilyTitle sql.NullString
}

func (q *Queries) CreateUserOAuth(ctx context.Context, arg CreateUserOAuthParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUserOAuth,
		arg.Name,
		arg.Username,
		arg.Password,
		arg.FamilyID,
		arg.GroupID,
		arg.Provider,
		arg.ProviderUserID,
		arg.FamilyTitle,
		arg.CustomFamilyTitle,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.FamilyTitle,
		&i.CustomFamilyTitle,
		&i.Password,
		&i.FamilyID,
		&i.GroupID,
		&i.IdentityID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findMembersByFamilyID = `-- name: FindMembersByFamilyID :many
SELECT
    id, name, username, family_title, custom_family_title, password, family_id, group_id, identity_id, provider, provider_user_id, created_at, updated_at
FROM
    users
WHERE
    family_id = $1
ORDER BY
    id
`

func (q *Queries) FindMembersByFamilyID(ctx context.Context, familyID int32) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, findMembersByFamilyID, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.FamilyTitle,
			&i.CustomFamilyTitle,
			&i.Password,
			&i.FamilyID,
			&i.GroupID,
			&i.IdentityID,
			&i.Provider,
			&i.ProviderUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserByID = `-- name: FindUserByID :one
SELECT
    id, name, username, family_title, custom_family_title, password, family_id, group_id, identity_id, provider, provider_user_id, created_at, updated_at
FROM
    users
WHERE
    id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.FamilyTitle,
		&i.CustomFamilyTitle,
		&i.Password,
		&i.FamilyID,
		&i.GroupID,
		&i.IdentityID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByIDAndFamilyID = `-- name: FindUserByIDAndFamilyID :one
SELECT
    id, name, username, family_title, custom_family_title, password, family_id, group_id, identity_id, provider, provider_user_id, created_at, updated_at
FROM
    users
WHERE
    id = $1
    AND family_id = $2
`

type FindUserByIDAndFamilyIDParams struct {
	ID       int32
	FamilyID int32
}

func (q *Queries) FindUserByIDAndFamilyID(ctx context.Context, arg FindUserByIDAndFamilyIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByIDAndFamilyID, arg.ID, arg.FamilyID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.FamilyTitle,
		&i.CustomFamilyTitle,
		&i.Password,
		&i.FamilyID,
		&i.GroupID,
		&i.IdentityID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByProvider = `-- name: FindUserByProvider :one
SELECT
    id, name, username, family_title, custom_family_title, password, family_id, group_id, identity_id, provider, provider_user_id, created_at, updated_at
FROM
    users
WHERE
    provider = $1
    AND provider_user_id = $2
`

type FindUserByProviderParams struct {
	Provider       sql.NullString
	ProviderUserID sql.NullString
}

func (q *Queries) FindUserByProvider(ctx context.Context, arg FindUserByProviderParams) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByProvider, arg.Provider, arg.ProviderUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.FamilyTitle,
		&i.CustomFamilyTitle,
		&i.Password,
		&i.FamilyID,
		&i.GroupID,
		&i.IdentityID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT
    id, name, username, family_title, custom_family_title, password, family_id, group_id, identity_id, provider, provider_user_id, created_at, updated_at
FROM
    users
WHERE
    username = $1
`

func (q *Queries) FindUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.FamilyTitle,
		&i.CustomFamilyTitle,
		&i.Password,
		&i.FamilyID,
		&i.GroupID,
		&i.IdentityID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUsers = `-- name: FindUsers :many
SELECT
    id,
    name,
    username,
    family_id,
    group_id
FROM
    users
`

type FindUsersRow struct {
	ID       int32
	Name     sql.NullString
	Username string
	FamilyID int32
	GroupID  int32
}

func (q *Queries) FindUsers(ctx context.Context) ([]FindUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, findUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindUsersRow
	for rows.Next() {
		var i FindUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.FamilyID,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMember = `-- name: UpdateMember :one
UPDATE users
SET
    group_id = $1,
    family_title = $2,
    custom_family_title = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $4
    AND family_id = $5
RETURNING
    id, name, username, family_title, custom_family_title, password, family_id, group_id, identity_id, provider, provider_user_id, created_at, updated_at
`

type UpdateMemberParams struct {
	GroupID           int32
	FamilyTitle       sql.NullString
	CustomFamilyTitle sql.NullString
	ID                int32
	FamilyID          int32
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateMember,
		arg.GroupID,
		arg.FamilyTitle,
		arg.CustomFamilyTitle,
		arg.ID,
		arg.FamilyID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.FamilyTitle,
		&i.CustomFamilyTitle,
		&i.Password,
		&i.FamilyID,
		&i.GroupID,
		&i.IdentityID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users
SET
    name = $1,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $2
RETURNING
    id, name, username, family_title, custom_family_title, password, family_id, group_id, identity_id, provider, provider_user_id, created_at, updated_at
`

type UpdateUserNameParams struct {
	Name sql.NullString
	ID   int32
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserName, arg.Name, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.FamilyTitle,
		&i.CustomFamilyTitle,
		&i.Password,
		&i.FamilyID,
		&i.GroupID,
		&i.IdentityID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
