// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, username, password, group_id, clan_group_id) VALUES ($1, $2, $3, $4, $5) RETURNING id, name, username, password, group_id, clan_group_id, created_at, updated_at
`

type CreateUserParams struct {
	Name        sql.NullString
	Username    string
	Password    string
	GroupID     int32
	ClanGroupID int32
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Username,
		arg.Password,
		arg.GroupID,
		arg.ClanGroupID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.GroupID,
		&i.ClanGroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, name, username, password, group_id, clan_group_id, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) FindUserByEmail(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByEmail, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.GroupID,
		&i.ClanGroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUsers = `-- name: FindUsers :many
SELECT id, name, username, password, group_id, clan_group_id, created_at, updated_at FROM users
`

func (q *Queries) FindUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, findUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Password,
			&i.GroupID,
			&i.ClanGroupID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
