basePath: /api
info:
  contact: {}
paths:
  /photo/upload:
    post:
      consumes:
      - multipart/form-data
      description: upload photo
      parameters:
      - description: file
        in: formData
        name: file
        required: true
        type: file
      responses: {}
swagger: "2.0"
