basePath: /api
info:
  contact: {}
paths:
  /photo:
    get:
      description: get photo list
      parameters:
      - description: limit
        in: query
        name: limit
        type: integer
      - description: skip
        in: query
        name: skip
        type: integer
      responses: {}
  /photo/first:
    get:
      description: get first photo
      responses:
        "200":
          description: OK
  /photo/group:
    get:
      description: get photo group by date
      parameters:
      - description: from
        example: "2024-01-01T00:00:00Z"
        format: date-time
        in: query
        name: from
        type: string
      - description: to
        example: "2024-05-01T00:00:00Z"
        format: date-time
        in: query
        name: to
        type: string
      responses: {}
  /photo/range:
    get:
      description: get photo range
      responses: {}
  /photo/upload:
    post:
      consumes:
      - multipart/form-data
      description: upload photo
      parameters:
      - description: file
        in: formData
        name: file
        required: true
        type: file
      responses: {}
  /photo/upload-live:
    post:
      consumes:
      - multipart/form-data
      description: upload live photo
      parameters:
      - description: photo
        in: formData
        name: photo
        required: true
        type: file
      - description: live
        in: formData
        name: live
        required: true
        type: file
      responses: {}
swagger: "2.0"
